### ISSUE TITLE
InternalServerException

### ISSUE THREAD

**Issue by Levesque7** [trydis/FIFA-Ultimate-Team-Toolkit#133]
I keep getting InternalServerException with one of my accounts but not the other. It happens less than 5 requests in to my session.

Anyone else had this issue that was able to resolve it?

EDIT: It happens on a SearchAsync()

**Comment by Levesque7** [comment]
I figured it out. Didn't play enough on the secondary account to access the transfer market.

**Comment by sipahis** [comment]
What was the problem?
I get the same Error on SearchAsyn().
