### ISSUE TITLE
FUT16

### ISSUE THREAD

**Issue by ChamBr** [trydis/FIFA-Ultimate-Team-Toolkit#135]
You think about upgrading to the 2016 version?

**Comment by trydis** [comment]
The [2016](https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/tree/2016) branch should work. I was planning on merging it into master yesterday and create a NuGet package, but didn't have time. Will try again tonight.

**Comment by ChamBr** [comment]
OK.

I have done tests in python: https://github.com/oczkers/fut
Has worked well, I was curious about his version for the simple issue of GUI.

I thank the attention.

**Comment by trydis** [comment]
I've merged the 2016 branch into master and created a NuGet package.
