### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by shullp** [trydis/FIFA-Ultimate-Team-Toolkit#136]
Couldn't find EASW_ID while login in. Has anybody faced with this issue?

**Comment by jonnydowe** [comment]
Having the same issue. Help would be appreciated.

**Comment by ulrickpsp** [comment]
Same issue here. I'll try to find out what's going on this evening.

**Comment by jvianafec** [comment]
also wanted to address this, can someone help?

**Comment by ulrickpsp** [comment]
It's very strange. I've been able to login with one account but others crashed at looking for the session ID.
