### ISSUE TITLE
Login verification

### ISSUE THREAD

**Issue by eupantof** [trydis/FIFA-Ultimate-Team-Toolkit#137]
Just wanted to let you guys know that Login verification is back. But now the email that we receive changed the format a bit:
- sender is "EA" now, before it was "Origin"
- the code is between \<h1\> tags now, before it was between \<strong\> tags (e.g.    20px;margin-left: 0;text-align: left" class="h1">XXXXXX\</h1\>)

EDIT:
I see that for me, at least, there is a new page loaded after code verification is sent. It's an advertise to use the App Authenticator. So I had to change LoginRequest.cs like this:

        private async Task SetTwoFactorCodeAsync(HttpResponseMessage loginResponse)
        {
            var tfCode = await _twoFactorCodeProvider.GetTwoFactorCodeAsync();

            var responseContent = await loginResponse.Content.ReadAsStringAsync();

            AddReferrerHeader(loginResponse.RequestMessage.RequestUri.ToString());

            var codeResponseMessage = await HttpClient.PostAsync(loginResponse.RequestMessage.RequestUri, new FormUrlEncodedContent(
                        new[]
                            {
                                new KeyValuePair<string, string>(responseContent.Contains("twofactorCode") ? "twofactorCode" : "twoFactorCode", tfCode),
                                new KeyValuePair<string, string>("_eventId", "submit"),
                                new KeyValuePair<string, string>("_trustThisDevice", "on"),
                                new KeyValuePair<string, string>("trustThisDevice", "on")
                            }));

            codeResponseMessage.EnsureSuccessStatusCode();

            var contentData = await codeResponseMessage.Content.ReadAsStringAsync();

            if (contentData.Contains("Incorrect code entered"))
                throw new FutException("Incorrect TwoFactorCode entered.");

            if (contentData.Contains("Tired of waiting for your code?"))
                await SkipAuthenticatorAdvertise(codeResponseMessage);
        }

        private async Task SkipAuthenticatorAdvertise(HttpResponseMessage codeResponse)
        {
            var responseContent = await codeResponse.Content.ReadAsStringAsync();

            AddReferrerHeader(codeResponse.RequestMessage.RequestUri.ToString());

            var authenticatorResponseMessage = await HttpClient.PostAsync(codeResponse.RequestMessage.RequestUri, new FormUrlEncodedContent(
                        new[]
                            {
                                new KeyValuePair<string, string>("_eventId", "cancel"),
                                new KeyValuePair<string, string>("appDevice", "ANDROID"),
                            }));

            authenticatorResponseMessage.EnsureSuccessStatusCode();

            var contentData = await authenticatorResponseMessage.Content.ReadAsStringAsync();
        }

Works for me.

Happy farming!

**Comment by vhrustic** [comment]
Well I am getting "FutRequestBase threw an exception" every time(when calling LoginAsync method).  It is System.TypeInitializationException Exception. Can't figure it out why. 

Code isn't event sent to my e-mail.

**Comment by Levesque7** [comment]
@meshoe  What is the new regex pattern? Thanks for the pre-emptive work on this.

**Comment by meshoe** [comment]
@vhrustic can you debug the code and let us know which line causes the exception? can you also capture the HTTP responses with fiddler and print them here?

@Levesque7 you need another pair of parenthesis to return the code as a var
var regex = new Regex(@"((?<=class=""h1"">)\d{6})");

**Comment by xtheokles** [comment]
Thanks @meshoe ! My two factor code provider is working now :)

**Comment by Levesque7** [comment]
Mine is working too now. Thanks again for the share @eupantof (DId you just change your username? lol)

**Comment by tringler** [comment]
Could someone help me out to implement this interface? I tried this simple/test implementation:
     class Authenticator:ITwoFactorCodeProvider
    {
        MainForm mainForm = new MainForm();
        TextBox otpText = new TextBox();
        

        public Authenticator()
        {
        }

        public async Task<string> GetTwoFactorCodeAsync()
        {
            await Task.FromResult<string>(mainForm.TXT_Auth.Text);

            throw new NotImplementedException();
        }
    }

But when I call:

var loginDetails = new LoginDetails(loadedAppdata.User, loadedAppdata.Password, loadedAppdata.SecurityQuestion, loadedAppdata.Platform);
Helper.Authenticator otpHelper = new Helper.Authenticator();
var loginResponse = await futClient.LoginAsync(loginDetails, otpHelper);

I need to wait for the e-mail and the OTP String is empty. How can I wait for the -mail, fill the string, and login then with the correct OTP string?

Thanks a lot for every hint :)

**Comment by vhrustic** [comment]
@eupantof 
Fiddler doesn't capture any traffic at all. And exception is thrown at LoginRequest constructor, which is derived from FutRequestBase class.
 public LoginRequest(LoginDetails loginDetails, ITwoFactorCodeProvider twoFactorCodeProvider)

**Comment by eupantof** [comment]
@vhrustic maybe you have empty login details? can't really tell unless you're pasting here your code. it should be something like this:

                var loginDetails = new LoginDetails(Email, Password, SecretAnswer, Platform);
                ITwoFactorCodeProvider provider = new ImapTwoFactorCodeProvider(...);
                var loginResponse = await Client.LoginAsync(loginDetails, provider);

**Comment by vhrustic** [comment]
@eupantof . I managed to successufly login. Thank you for your interest.
When i search players I get exception: Additional information: Could not find member 'nation' on object of type 'ItemData'. Path 'auctionInfo[0].itemData.nation', line 1, position 984.

It's simple search

 var searchParameters = new PlayerSearchParameters
            {
                Page = 1,
                Level = Level.Gold,
            };

            var searchResponse = await client.SearchAsync(searchParameters);

I tried with nation as parameter, but still same error.

**Comment by eupantof** [comment]
@vhrustic 
The data model was extended for fut16. You have to get the latest code from this repository, which was enhanced by this pull request: https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/pull/134
It should work with those changes.

**Comment by vhrustic** [comment]
@eupantof Yes, I figured out that. I set up everything, now it is working, I am already buying players from market.
Thank you again

**Comment by jvianafec** [comment]
please,

I'm starting and I can not understand how to do much work. I have a problem login ("unabled login") right here:


 var nucleusId = Regex.Match(await nucleusResponseMessage.Content.ReadAsStringAsync(), "EASW_ID = '\\d+'")
                .Value
                .Split(new[] { " = " }, StringSplitOptions.RemoveEmptyEntries)[1]
                .Replace("'", string.Empty);


I would like to ask a model that can see and study what is working.

since already, thank you.

**Comment by JoaoFelipePego** [comment]
@jvianafec I am facing the same problem , you quickly found lguma Solution ?

**Comment by craigbaines** [comment]
Im skipping reading the above comments so forgive me if this already got mentioned, but one thing i thought id drop in rearguards the h1 tag the codes within, the English / other lang emails vary slightly, im not sure what language it was / if its all but English but the space between <h1 and class= had an extra space in.... 

If you have a situation that you might be receiving emails in two languages, look out for that!

**Comment by bradders591** [comment]
Did anyone have to add anything special to their gmail account to allow for IMAP connections? I've enabled imap in the settings but still not having any luck logging into gmail from my app.

**Comment by jvianafec** [comment]
Yes @JoaoFelipePego, is Brazillian? I can help!

Enviado do meu iPhone

**Comment by JoaoFelipePego** [comment]
@jvianafec yes I'm brazilian! Have managed to solve this problem .. please contact me :)

**Comment by mlepron** [comment]
How can I edit LoginRequest.cs ? I installed the package with NuGet directly into my visual studio project and i can't open the package.. 

Thank you in advance.

**Comment by AMG-michal** [comment]
@mlepron One of the possibilities: download and extract the zip. Add an existing project to the solution.  You can then edit the file. 

If you are planning on commiting then have a read about forking.

**Comment by mlepron** [comment]
Thank you @AMG-michal  for your response.
Using your solution, I get an error when loading the project in Visual Studio 2013.
<< C:\Users\name\Desktop\FIFA-Ultimate-Team-Toolkit-master\UltimateTeam.Toolkit\UltimateTeam.Toolkit.csproj : error  : Unable to open the project file 'UltimateTeam.Toolkit'. >>

**Comment by jaumhc** [comment]
@jvianafec hey, I am brazilian too, can you help me? Can you add me on skype or email me?

Skype: jaumpump
Email: jaum_hc@yahoo.com.br

Thanks!

**Comment by luizfnunesmarques** [comment]
just extending @AMG-michal answer, u can configure to build all projects and the toolkit first.

**Comment by craigpbrown** [comment]
Is there a way to log in without the verification email being generated each time? For example, can I use a browser to log in and grab the nxmpcid from that and hard code that so it's being submitted with the necessary requests?

**Comment by luizfnunesmarques** [comment]
every login you do with "toolkit" is a session. Your login inside the browser runs separely; Plus, if u logged on ut while trying to run your "toolkit", you'll got "already logged on console or pc"

regards

**Comment by luizfnunesmarques** [comment]
if you concerning about get the message, ask by console and made your twofactor to class to return this value

**Comment by Guih-sistemas** [comment]
Always return: WaitForActivation

and I personally logged by the site, does not send e-mail with a code

that I'm missing?




 var loginDetails = new LoginDetails("myUser", "myPassword", "keyWord", Platform.Ps4);
            ITwoFactorCodeProvider provider = new ImapTwoFactorCodeProvider("MyEmail", "MyPassowordEmail", "imap.gmail.com", 993, false);
            var loginResponse = client.LoginAsync(loginDetails, provider);



public Task<string> GetTwoFactorCodeAsync()
        {
            return Task.Run(async () =>
            {
                
                var regex = new Regex(@"((?<=class=""h1"">)\d{6})");

                using (
                    var client = new ImapClient(_hostName, _username, _password, AuthMethods.Login, _port, _useUseSsl))
                {
                    for (var i = 0; i < 5; i++)
                    {
                        var messages =
                            client.SearchMessages(SearchCondition.Unseen().And(SearchCondition.From("EA")));
                        foreach (
                            var match in
                                messages.Select(message => regex.Match(message.Value.Body))
                                    .Where(match => match.Success))
                        {
                            return match.Value;
                        }
                        await Task.Delay(5000);
                    }
                }
                throw new FutException("Unable to find the two-factor authentication code.");
            });
        }

**Comment by luizfnunesmarques** [comment]
don't forget to set a security question on console, and play few games, and later you'll be able to enter market. New accounts have restricted access by default
