### ISSUE TITLE
Requests not working ?

### ISSUE THREAD

**Issue by DjTrilogic** [trydis/FIFA-Ultimate-Team-Toolkit#139]
Hey everyone, I'm encountring a problem where I receive this response from all requests (except login):

{"debug":"","string":"","code":"404","reason":""}

Do you guys have a hint please ?

**Comment by eupantof** [comment]
Have you updated Resources.cs file with the fut16 links?

**Comment by xtheokles** [comment]
It can be for sniping while trading? It happened to me, but I haven't analized the requests.
The sympthoms were the same, can login but cannot search players on the market. I saw on the net that it is a temporary ban for sniping BIN players. After aprox. 8 hours got unbanned and it's working again.

**Comment by rodwill** [comment]
I'm having the same problem... Search Request doesn't work.... Trade list work....
Tree days with the same way... after a few hours from my bot running the problem start... Internal Server Error on searchs request.

**Comment by tringler** [comment]
This issue is regarding 404 (Page not found) Errors, not 500 (InternalServerErrors) Erros - I created a new issue about that issue. @DjTrilogic Do you still have the issues after updating the toolkit? Pls close if solved.

**Comment by DjTrilogic** [comment]
Problem solved, I was using wrong platform >_<'
