### ISSUE TITLE
GetItemAsync

### ISSUE THREAD

**Issue by A-VORONKIN** [trydis/FIFA-Ultimate-Team-Toolkit#141]
GetItemAsync is not working! I have HttpRequestException when I tried to use it.

P.S. GetPlayerImageAsync also not working.

**Comment by tringler** [comment]
I'm working on a fix - You can fix it by change this in auctioninfo.cs:

```
        public long CalculateBaseId()
        {
            return ItemData.AssetId;
        }
```

**Comment by A-VORONKIN** [comment]
It's working fine now. Thanks!

**Comment by tringler** [comment]
Should be fixed with https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/pull/144
