### ISSUE TITLE
Login failed: Session ID

### ISSUE THREAD

**Issue by ulrickpsp** [trydis/FIFA-Ultimate-Team-Toolkit#142]
My program says "Unable to login" after this instruction is executed:

var sessionId = Regex.Match(await authResponseMessage.Content.ReadAsStringAsync(), "\"sid\":\"\\S+\"")
                .Value
                .Split(new[] { ':' })[1]
                .Replace("\"", string.Empty);

ANyone having this issue?

**Comment by Nicorad** [comment]
Same problem...

**Comment by ulrickpsp** [comment]
I've checked  authResponseMessage.Content  and it's equal to:  

Content - Length: 49
Content - Type: text / plain; charset = utf - 8
Expires: Mon, 28 Sep 2015 13:06:16 GMT


Nothing else.

**Comment by kauefelipe** [comment]
Same problem here...

[IndexOutOfRangeException: Index was outside the bounds of the array.]
   UltimateTeam.Toolkit.Requests.<GetNucleusIdAsync>d__30.MoveNext() +474
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) +25
   UltimateTeam.Toolkit.Requests.<PerformRequestAsync>d__0.MoveNext() +966

[FutException: Unable to login]
   UltimateTeam.Toolkit.Requests.<PerformRequestAsync>d__0.MoveNext() +1959
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   UltimateTeam.Toolkit.<LoginAsync>d__0.MoveNext() +203
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58

**Comment by ulrickpsp** [comment]
Solved by re-downloading the latest version of the toolkit and adding the code that #137 suggested. Thanks.
