### ISSUE TITLE
InternalServerError

### ISSUE THREAD

**Issue by tringler** [trydis/FIFA-Ultimate-Team-Toolkit#143]
Hello,

I'm getting InternalServerError after WatchlistRequests or Searchrequests - I keep the requests at 50 RPM. Does anyone have the same issue? It's working for a while (about 500 requests) and then I get the InternalServerErrors 

Thanks, Thomas

**Comment by xtheokles** [comment]
@tringler Peraphs you are sending too much request, I keep mine ~20 RPM and disconnecting every ~35min and then reconnecting after 5-10 min. 
For the moment it's working.

**Comment by tringler** [comment]
Ok - Do we have only this limit per minute or do we have also a limit between the requests?

**Comment by xtheokles** [comment]
@tringler Not sure, just speculations. I'm not checking the request results everytime but a few days ago it happened to me, after 15-20 minutes buying players, my bot wasn't finding any players on the market. After close and reopen the bot, it worked again.

Now I wait some minutes every certain time and it seems to work.

**Comment by tringler** [comment]
Thanks a lot - I'm "stable" now with 50 RPM and 2 seconds between search requests

**Comment by Levesque7** [comment]
@xtheokles How are you implementing the disconnect? I just have a 5 minute sleep every 5-10 minutes. Do you have a better method?

**Comment by tringler** [comment]
This is not a disconnect - You just sleeping the thread - You need to null your futclient object and then login again

**Comment by Levesque7** [comment]
@tringler I know it's not a disconnect. That's why I asked.

**Comment by DjTrilogic** [comment]
Is it normal that i'm getting internal server error after 12 hours from the last botting session ( it was the first one ... 12 hours non-stop ) . Please ensure me :(

--
BENSLIMANE Abdessamad
Téléphone: +33 6 05 56 47 27

**Comment by Spettacolo83** [comment]
I have the same InternalServerError when I call PlaceBidAsync().
Is not a problem of RPM. I tried to disconnect and riconnect and do an interval of 3 sec between an operation and another. It's the same error.
Any suggestions?

**Comment by tringler** [comment]
Everytime or randomly? I'd catch the FUTExceptions and just relogin.

**Comment by Spettacolo83** [comment]
Yesterday works well. Today everytime. I tried to disconnect and reconnect but nothing! The same problem. I can tried also to connect by iOS app and i can buy and sell there.
What can I try?

**Comment by Levesque7** [comment]
@Spettacolo83 I'm pretty sure it gives you a temporary ban from the market. I've heard speculation they can be up to 18 hours long. None of this is concrete information, though. Only from what I've gathered myself and heard second hand. 

I had this problem myself, waited a few hours and it worked again.

**Comment by Spettacolo83** [comment]
Ok i will try to wait some hours but I can't understand why the iOS app works well!
Anyway, thankyou!

**Comment by Spettacolo83** [comment]
Now it works again! I believe that Levesque7 was right. It seems a little ban!
Beware guys!

**Comment by Spettacolo83** [comment]
I can't understand what is the limit for avoid InternalServerError.
I do bid with 4 seconds of interval between one and another.
I disconnect after 25 minutes of starting operation and i wait 10 minutes after disconnection for reconnect. After 1 day, i have again the InternalServerError.
What is your expirience about that?
Do you have found the right timing?

**Comment by ulrickpsp** [comment]
I've just started to suffer from this..

**Comment by A-VORONKIN** [comment]
I have 3 seconds between requests and disconnecting every ~30min and then reconnecting after 15 min but I still have this problem every day. Searching in web-app also not working.

**Comment by tringler** [comment]
Did you tarce this via Fiddler? After which Requests you got the error and are you pretty sure these requests are valid? Maybe you can share the Fiddler log and we can have a look at it.

**Comment by A-VORONKIN** [comment]
Ok, I will trace this errors later. People from ultimatebot forum have the same errors, it is ban in web app. they reccomend to set 10 rpm.

**Comment by Spettacolo83** [comment]
I tried 10 rpm, in other words 6000 milliseconds to an operation and another.
I have InternalServerError after any minutes.

**Comment by A-VORONKIN** [comment]
With 10 rpm I have no problems with InternalServerError

**Comment by Spettacolo83** [comment]
@A-VORONKIN can you try 10 rpm without disconnection every 30min?

**Comment by craigbaines** [comment]
ive heard rumours of a 5k daily request limit, iv'e not bothered to test anything but staying within that does stop me from getting the annoying search bugs. A second point to that which will make a few of you happy im sure is when your account seems to hit the limit / searches fail. Switch to mobile login, it will work... so i assume if there is such a limit, its separate on each login. 

I rotate my accounts every hour between web app > mobile app > sleep time. at 10 rpm, i calculate that 4800 requests per login per day, no issues so far with it :)

**Comment by A-VORONKIN** [comment]
@Spettacolo83 I didn`t do diconnection every 30 min, I just stop bot every 4 hours for 1 hour and everything works fine (with 10 rpm).

**Comment by A-VORONKIN** [comment]
@craigbaines how you get 4800 request with 10 rpm? 10 rpm = 14400 requests per day if bot will work without pauses.

**Comment by Spettacolo83** [comment]
What type of requests i need to check? Only bid?
Because with the temporary ban i can re-list, search but not bid.

**Comment by A-VORONKIN** [comment]
At 30 rpm I have been banned after 2093 request (didin`t used my bot before for 2 days).

**Comment by sansobarcelo** [comment]
Permanent ban? 
EA blocked my accounts two days ago, and I am waiting his response. They are investing my case.

**Comment by A-VORONKIN** [comment]
temporary ban in web app

**Comment by A-VORONKIN** [comment]
@craigbaines what sleep time you are using and when? and are you using both android and ios login? or if you get ban on ios, you will be also baned on android?

**Comment by tringler** [comment]
In my experience it's also important you wait at least one second between each request to avoid InternalServerErrors

**Comment by tringler** [comment]
Just for information, I'm temp. banned after about 8500 requests within about 10h of bot use.

**Comment by sipahis** [comment]
I'm also temp. banned with 5-20 rpm.
I do a priceCheck every 20 minutes with PageSize = 49.
Maybe that ist the Problem.

**Comment by tringler** [comment]
My experience so far without getting banned:
* Maximum is 60 Requests per Minute
* At least 1 Seconds between each request
* Maximum is between 6000-8000 Requests per Day (I don't know when they reset the counter)

**Comment by A-VORONKIN** [comment]
@tringler are you counting all requests or only transfer market search?

**Comment by tringler** [comment]
I'm counting all requests

**Comment by sipahis** [comment]
@tringler with your settings do you stop your AB after 2-3 hours?

**Comment by tringler** [comment]
No, I only stop if I reached my maximum requests per day counter - Then I go into "passive" mode and just relist all my items until the maximum request per day counter is resetted (after 24h)

**Comment by sipahis** [comment]
Ok, I calculated 2-3 hours. 60rpm x 60 = 3600 rph x 2 = 7200 -> reached max. request a day. So you can search and buy for 2 hours and have to wait 22h. Right?

**Comment by tringler** [comment]
Basically yes, but this would be a horrible way to let your bot work I would say :)

**Comment by ulrickpsp** [comment]
any progress here?

**Comment by tringler** [comment]
Any Progress on what? I would say the question about Internal Server errors / temp. BANs are answered.
