### ISSUE TITLE
Player.json

### ISSUE THREAD

**Issue by ulrickpsp** [trydis/FIFA-Ultimate-Team-Toolkit#145]
Hi mates! I remember last year there was a file called "player.json" with all players in the game. I was triying to obtain that database for this FIFA16, but I'm quite new on that. Could anybody point me out the right direction?

I've been trying to obtain the file from EA website or Futhead but my knowlegde seems to be insufficient. Thanks in advance.

**Comment by bradders591** [comment]
Im sure i posted a file on the original issue for when we started this again, have a look there.

**Comment by ulrickpsp** [comment]
Thanks @bradders591 ! May I ask you how did you get that info? I'd like to learn about it :)

**Comment by xtheokles** [comment]
And how can a player be found by it's id from @bradders591  players.json?
Actually I can do it by debugging the auctions and adding 4026531840 to the negative ResourceId, but it's tedious..

**Comment by xtheokles** [comment]
Ok, silly me, asking before test it.. -.- Solved, thanks!

**Comment by kauefelipe** [comment]
Where can i find the @bradders591 json file?

**Comment by ulrickpsp** [comment]
Here: http://www.filedropper.com/playerstar

Thanks to @bradders591

**Comment by A-VORONKIN** [comment]
How to get resourse id from this file?

**Comment by ulrickpsp** [comment]
There's a field called ID. That's what I used.

**Comment by A-VORONKIN** [comment]
But it is baseid, you can use it for normal cards but you can`t only search informs with it.
