### ISSUE TITLE
Error in GetClubItemsAsync() with FUT16.

### ISSUE THREAD

**Issue by Spettacolo83** [trydis/FIFA-Ultimate-Team-Toolkit#146]
I can connect to FUT16 with new UltimateTeamToolkit. I can retrive my credit and the other thinks
I have not problem when i call GetPileSizeAsync() and GetPurchasedItemsAsync()
but when i call GetClubItemsAsync() the connection lost and the error is:

"Could not find member 'loans' on object of type 'ItemData'. Path 'itemData[0].loans', line 1, position 883."

Any suggestions?

**Comment by xtheokles** [comment]
Here is https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/pull/134

**Comment by Spettacolo83** [comment]
Thank you so much! Now works!

**Comment by Gamer3** [comment]
xtheokles or spettacolo83 do you have Skype? I am trying to get access to player data from the web app and need to discuss if possible. Thanks

**Comment by Spettacolo83** [comment]
I notice that the function GetClubItemsAsync() last year returned All Club's items (players, contract, ecc..)
This year, this function returns only the player.
Any suggestion for returning all club's items as the last year?
