### ISSUE TITLE
Mobile Login

### ISSUE THREAD

**Issue by DjTrilogic** [trydis/FIFA-Ultimate-Team-Toolkit#147]
I figured out that after having the internal server error (due to big botting sessions/ high RPM). Webapp won't work for a long period, but the companion on mobile still work fine and able to make all requests.

So, do you guys know how to login through the mobile platform ? (i'm sure it's possible and needs only the loginRequest to be changed...

**Comment by DjTrilogic** [comment]
After a short capturing session of the traffic of my phone I deduced that all requests are the same exception the login process, I need someone tonight to talk with and discover this together through Skype!

**Comment by Levesque7** [comment]
Let us know what you find out, would be great to be rid of the Internal Server Error

**Comment by ulrickpsp** [comment]
@DjTrilogic I started to suffer from this. Have you made any progress? If you need help, let me know.

**Comment by DjTrilogic** [comment]
I had a look at requests sent between my phone and the server but I didn’t analyze them yet, I’m in lack of time, but basically it’s quite easy to make it work.

 

De : ulrickpsp [mailto:notifications@github.com] 
Envoyé : Tuesday, October 6, 2015 11:20 AM
À : trydis/FIFA-Ultimate-Team-Toolkit <FIFA-Ultimate-Team-Toolkit@noreply.github.com>
Cc : DjTrilogic <abdessamad.benslimane@gmail.com>
Objet : Re: [FIFA-Ultimate-Team-Toolkit] Mobile Login (#147)

 

@DjTrilogic <https://github.com/DjTrilogic>  I started to suffer from this. Have you made any progress? If you need help, let me know.

**Comment by craigbaines** [comment]
I can confirm the login works fine with mobile when the web app bugs, but mobile will eventually bug the same way, it does allow you to rotate between them though an stop yourself from getting bugged at all.

**Comment by ulrickpsp** [comment]
@craigbaines , which are the differences frommobile login to pc login? I'm triying to implement that functionality to avoid Internal Server Errors..

**Comment by A-VORONKIN** [comment]
I also tried to implement mobile login and no succes for now. I don`t understand why it is not working...

**Comment by ulrickpsp** [comment]
@A-VORONKIN did you manage to implement mobile login? I've been quite busy this past days..hopefully i can inplement it soon.

**Comment by ulrickpsp** [comment]
I'm really stuck with mobile login. I haven't been able to implement it yet. I'm quite bad inspecting http requests. Any help would be really appreciated.

**Comment by tringler** [comment]
any progress here?

**Comment by DjTrilogic** [comment]
Still no one made this ?

**Comment by tringler** [comment]
I had a look into this and the login process seems to be completely different to the WebApp plus the requests inside the companion seems to be also very difficult to WebApp requests, so it seems to be many hours of Fiddlering and coding all these new requests and login process :-/

**Comment by DjTrilogic** [comment]
i'm sure there are people using this repository who have it implemented...



On Thu, Dec 24, 2015 at 12:17 PM, tringler <notifications@github.com> wrote:

> I had a look into this and the login process seems to be completely
> different to the WebApp plus the requests inside the companion seems to be
> also very difficult to WebApp requests, so it seems to be many hours of
> Fiddlering and coding all these new requests and login process :-/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/issues/147#issuecomment-167094996>
> .
>



-- 
*Abdessamad Benslimane*
Email: Abdessamad.Benslimane@gmail.com
Téléphone: +33 6 05 56 47 27

**Comment by ulrickpsp** [comment]
Certainly I have some time these days to try to implement this, but I would like to know which are the advantages of mobile login. Thanks.

**Comment by DjTrilogic** [comment]
It will allow us to swap between the web-app login and mobile login when
the account is bugged. This mean we can increase the RPM without fearing
the long time (6 hours long) bug.

On Wed, Dec 30, 2015 at 7:45 AM, ulrickpsp <notifications@github.com> wrote:

> Certainly I have some time these days to try to implement this, but I
> would like to know which are the advantages of mobile login. Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/issues/147#issuecomment-167946352>
> .
>



-- 
*Abdessamad Benslimane*
Email: Abdessamad.Benslimane@gmail.com
Téléphone: +33 6 05 56 47 27

**Comment by ulrickpsp** [comment]
Thanks mate. I'll try to get it to work and share it with you.

**Comment by DjTrilogic** [comment]
I will give you an interesting Fiddler Session from another bot, it may
make things simple for you (i'll send you via mail if you want)

On Wed, Dec 30, 2015 at 9:20 AM, ulrickpsp <notifications@github.com> wrote:

> Thanks mate. I'll try to get it to work and share it with you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/issues/147#issuecomment-167956135>
> .
>



-- 
*Abdessamad Benslimane*
Email: Abdessamad.Benslimane@gmail.com
Téléphone: +33 6 05 56 47 27

**Comment by ulrickpsp** [comment]
Sure! I've sent you an email using your public address. Thanks.

**Comment by A-VORONKIN** [comment]
https://github.com/oczkers/fut has mobile login. maybe someone can check it and implement same in this toolkit.

**Comment by bbday** [comment]
Yes but is not very good (can also work), cause if you debug mobile call is bit different from web app:

no refer
extra tag in call
ecc ...

**Comment by tringler** [comment]
I took a look into https://github.com/oczkers/fut - All I can see he that the headers are changed. I cannot imagine this will work. Can anybody confirm this?

```
        if emulate == 'and':
            self.r.headers = headers_and.copy()  # i'm android now ;-)
        elif emulate == 'ios':
            self.r.headers = headers_ios.copy()  # i'm ios phone now ;-)
        else:
            self.r.headers = headers.copy()  # i'm chrome browser now ;-)
        self.urls = urls(platform)
```

**Comment by bbday** [comment]
the main problem is login not other requests.
fut project don't emulate mobile login, but only requests, it is very dangerous do this cause for ea is very easy check if you do something that can't do with app (fake login).
Sniff data with mobile companion and you will see login is different (set http proxy on your android mobile)

**Comment by tringler** [comment]
Yes, but I think the EA API is even not recognizing if the user agent is Windows, Android, etc. - I think it's not changing anything on the behaviour.

I'm currently working on mobile login and it seems not to complicated. I will update the comment later that day.

**Comment by A-VORONKIN** [comment]
there is not only headers. i tried to implement it few months ago but no  success. I`m bad in python :)

**Comment by tringler** [comment]
That's not a problem, because we're in a C# solution here :)

As far as I can see it's like this:

Login: 

```
GET /connect/auth?client_id=FIFA-16-MOBILE-COMPANION&response_type=code&display=web2/login&scope=basic.identity+offline+signin&locale=de_DE&prompt=login&machineProfileKey=_PUTYOURMACHINEKEYHERE_
````

You get redirected to the login page (You can try it in a browser of your choice without Android)

Put in Username/Password/EA Code you will get your Companion Code.

**Comment by lorenzh** [comment]
I think the login process is the same you need to change the headers, sku and the clientversion.

**Comment by tringler** [comment]
Sounds too easy :D

**Comment by A-VORONKIN** [comment]
Any progress?

**Comment by tringler** [comment]
Not so far - Maybe this evening

**Comment by tringler** [comment]
I was able to reproduce the mobile login until I got the code from the companion app:
![unbenannt](https://cloud.githubusercontent.com/assets/4985268/13619165/ed769e94-e587-11e5-9973-81b00a2ee4ab.PNG)

The whole post login procedure is still missing:

![Uploading Unbenannt1.PNG…]()

In addition to this it looks like we need to attach the timestamp on each request:
![unbenannt3](https://cloud.githubusercontent.com/assets/4985268/13620269/b497f378-e58e-11e5-8966-cddf10ed21b1.PNG)

**Comment by tringler** [comment]
Anyone with a smart C# solution how to add attach the timestamp to each request without changing too much code?

**Comment by trydis** [comment]
You could create a method that creates the timestamp and add it to the URL's in https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/blob/master/UltimateTeam.Toolkit/Requests/HttpClientWrapper.cs  -> Get-/PostAsync

**Comment by tringler** [comment]
Mobile Login is 98% done, but I'm struggling at this point:

```
POST https://utas.s2.fut.ea.com/ut/game/fifa16/phishing/validate HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/29.0.1547.62 Safari/537.36
Accept-Encoding: gzip, deflate, sdch
Referer: https://signin.ea.com/p/web2/login?execution=e1491572055s2&initref=https:%2F%2Faccounts.ea.com:443%2Fconnect%2Fauth%3Fscope%3Dbasic.identity%2Boffline%2Bsignin%26locale%3Den_EN%26display%3Dweb2%252Flogin%26machineProfileKey%3D%257B0%257D%26response_type%3Dcode%26prompt%3Dlogin%26client_id%3DFIFA-16-MOBILE-COMPANION
Authorization: Bearer QVQwOjEuMDozLjA6NjA6VXdrUGZHNVdPazBLM2JuVmxFWGVQMHFLNmE5U2dHNktXbEs6NjIxNTpuNWJjYQ
X-UT-SID: 66f280c2-4ef1-4248-a854-b310571xxxxx
X-POW-SID: 66f280c2-4ef1-4248-a854-b31057xxxxx
Easw-Session-Data-Nucleus-Id: 2336406xxx
Content-Type: application/x-www-form-urlencoded
Host: utas.s2.fut.ea.com
Content-Length: 39

answer=8b8f7cedde86419fb30a31xxxxxx
```

I'm getting:

```
HTTP/1.1 401 Unauthorized
Content-Type: application/json;charset=utf-8
Content-Length: 54
X-UnzippedLength: 54
Server: Jetty(8.0.0.M2)

{"reason":"expired session","code":401,"message":null}
````

Any ideas?

**Comment by bbday** [comment]
Don't have refer second function
first use X-POW-SID second X-UT-PHISHING-TOKEN

**Comment by tringler** [comment]
Sorry - I traced again and you have X-UT-PHISHING-TOKEN only if you have a cookie and already answered the question. This is the app output without a cookie:

```
POST https://utas.s2.fut.ea.com/ut/game/fifa16/phishing/validate?answer=8b8f7cedde86419fb30a31b82cf1xxx HTTP/1.1
Host: utas.s2.fut.ea.com
Connection: keep-alive
Content-Length: 32
Accept: text/plain, */*; q=0.01
X-UT-SID: e57414a2-8f68-4c3f-95ad-f57b09f9dxxx
Easw-Session-Data-Nucleus-Id: 2336406xxx
Origin: file://
CSP: active
User-Agent: Mozilla/5.0 (Linux; Android 4.2.2; AndyWin Build/JDQ39E) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 Crosswalk/14.43.343.25 Safari/537.36
Content-Type: application/json
Accept-Encoding: gzip, deflate
Accept-Language: en-us,en

8b8f7cedde86419fb30a31b82cf1fxxx
```

**Comment by tringler** [comment]
I think I found the problem - I just forgot a call to https://utas.s2.fut.ea.com/ut/auth?timestamp=_TIMESTAMP_

Unfortunately I have now problems to understand the whole login process :(

**Comment by tringler** [comment]
[https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/pull/238](url)

**Comment by A-VORONKIN** [comment]
awesome!

**Comment by tringler** [comment]
The mobile headers and the timestamps are still missing, but it seems to be working without it.

**Comment by tringler** [comment]
Who can confirm, that the login via cookieContainer is not working?

**Comment by mtdx** [comment]
is the vnext version ready to test the mobile login? I know there was an issue with the headers on the Web App requests, relisting an item.

**Comment by tringler** [comment]
Trydis is currently refactoring my code - It's basically ready to use - Testing and bug reporting is highly appreciated! I documented two known errors here:

https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/pull/238

**Comment by mtdx** [comment]
Does your mobile login branch work? did you fixed the typo and the headers, I don't know which to try, I see a vnext branch, and a WIP branch and then yours.

**Comment by tringler** [comment]
a) You can use my mobile branch and correct the typo and the headers by yourself
b) Wait until trydis refactored the code

AFAIK:
vnext branch = testing branch for new PRs
WIP branch = branch trydis is using for refactoring

**Comment by solorinka** [comment]
error 400, i guess you set _code wrong
```
           authenticatorResponseMessage.EnsureSuccessStatusCode();

            var contentData = await authenticatorResponseMessage.Content.ReadAsStringAsync();
            _code = contentData;


```
now the mobile login works for me

**Comment by tringler** [comment]
The patch for this bug is in that PR: https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/pull/251

**Comment by tringler** [comment]
@trydis : Please close as the feature is in master branch now.
