### ISSUE TITLE
"Unable to login" problem

### ISSUE THREAD

**Issue by sesey** [trydis/FIFA-Ultimate-Team-Toolkit#149]
Hi
Where is the problem?

        private async void button_Click(object sender, RoutedEventArgs e)
        {
            var client = new FutClient();
            LoginResponse response = await Login(client);
        }
        public async Task<LoginResponse> Login(FutClient client)
        {
            var loginDetails = new LoginDetails("test@gmail.com", "test", "test", Platform.Pc);
            ITwoFactorCodeProvider provider = new ImapTwoFactorCodeProvider("test@gmail.com"", "test", "imap.googlemail.com", 993, true);

            LoginResponse loginResponse = await client.LoginAsync(loginDetails, provider);
            return loginResponse;
        }
       public class ImapTwoFactorCodeProvider : ITwoFactorCodeProvider
       {
        private readonly string _username;
        private readonly string _password;
        private readonly string _hostName;
        private readonly int _port;
        private readonly bool _useUseSsl;

        public ImapTwoFactorCodeProvider(string username, string password, string hostname, int port, bool useSsl)
        {
            _username = username;
            _password = password;
            _hostName = hostname;
            _port = port;
            _useUseSsl = useSsl;
        }
        public Task<string> GetTwoFactorCodeAsync()
        {
            return Task.Run(async () =>
            {
                var regex = new Regex(@"((?<=class=""h1"">)\d{6})");

                using (var client = new ImapClient(_hostName, _username, _password, AuthMethods.Login, _port, _useUseSsl))
                {
                    for (var i = 0; i < 5; i++)
                    {
                        var messages = client.SearchMessages(SearchCondition.Unseen().And(SearchCondition.From("EA")));
                        foreach (var match in messages.Select(message => regex.Match(message.Value.Body)).Where(match => match.Success))
                        {
                            return match.Value;
                        }
                        await Task.Delay(5000);
                    }
                }
                throw new FutException("Unable to find the two-factor authentication code.");
            });
        }
    }

**Comment by ulrickpsp** [comment]
Where does your program crash? Set breakpoints..debug..etc. Otherwise it's quite difficult to help you.

**Comment by Nicorad** [comment]
Same error this morning, was working fine yesterday afternoon... Maybe it's not your code...

**Comment by ulrickpsp** [comment]
Do you both have bought the game? If not you won't be able to access webapp.

**Comment by Nicorad** [comment]
yes, I have it.
Yesterday I was able to re-list all the players in the trade pile through my app. Stop the dev (I didn't even close Visual Studio, juste lock the computer). Today, I unlcok it, test again before continuing the dev, impossible to log in...

**Comment by Nicorad** [comment]
My bad, you're right, never connected on the PS4 with the account I'm using for test...
EA stops today the "early access". @sesey, maybe it's the same problem.
Just tested with the account I use to play, working fine...

**Comment by sesey** [comment]
I bought fifa 16.I can access the webapp application.
but "Unable to login" error vs 2015
error image
<a href="http://tinypic.com?ref=6qbczk" target="_blank"><img src="http://i61.tinypic.com/6qbczk.png" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by sansobarcelo** [comment]
I have the samer error
Still not working? Or you solved it?
Thanks

**Comment by sesey** [comment]
the problem continues.

**Comment by tringler** [comment]
Why you don't catch the error and show us the exception?

**Comment by JoaoFelipePego** [comment]
I STAND WITH THE SAME PROBLEM !

**Comment by tringler** [comment]
Just let us know the inner exception

**Comment by sesey** [comment]
<a href="http://tinypic.com?ref=vosivq" target="_blank"><img src="http://i59.tinypic.com/vosivq.png" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by tringler** [comment]
Looks like your IMAP code throws an exception, it's not FUT toolkit related.

**Comment by sesey** [comment]
"using" delete the problem was solved.


return Task.Run(async () =>
            {
                var regex = new Regex(@"((?<=class=""h1"">)\d{6})");
                ImapClient client;
                for (var i = 0; i < 5; i++)
                {
                    client = new ImapClient(_hostName, _username, _password, AuthMethods.Login, _port, _useUseSsl);
                    var messages = client.SearchMessages(SearchCondition.Unseen().And(SearchCondition.From("EA")));
                    foreach (var match in messages.Select(message => regex.Match(message.Value.Body)).Where(match => match.Success))
                    {
                        return match.Value;
                    }
                    await Task.Delay(5000);
                }
                throw new FutException("Unable to find the two-factor authentication code.");
            });
