### ISSUE TITLE
Account bans. "Your account was locked to protect your information.."

### ISSUE THREAD

**Issue by xtheokles** [trydis/FIFA-Ultimate-Team-Toolkit#151]
Hey guys, this messaged appeared to me 2 days ago, and I'm not available to do nothing in web app(I can log but I wait forever in a blank page), cannot login in my origin account from PSN and even from Android mobile APP.

I haven't recieved yet a message telling I'm banned, I'm waiting for an answer from EAdisputes to see why I cannot access to my account.
Haven't bought any coins, just botting at less than 15 RPM and periods of max 10 hours and I've made 700k in less than a week :|

Someone have been banned too? I searched on other forums(UTBot) and it looks that is common on there to be banned just like me.
I'm not sure if it's a common problem or i'm having bad luck.

**Comment by tringler** [comment]
Why you don't contact the support and ask what is wrong with the account?

**Comment by DjTrilogic** [comment]
Is your account unlocked now ?

**Comment by JoaoFelipePego** [comment]
Friend you could help me by providing their used code ? I believe I can help you with that ..

**Comment by tringler** [comment]
Any update? What happened to your account?

**Comment by sansobarcelo** [comment]
Today I get this message...
