### ISSUE TITLE
Permission denied when listing item from "Unassigned pile"

### ISSUE THREAD

**Issue by ulrickpsp** [trydis/FIFA-Ultimate-Team-Toolkit#152]
Hi mates! I'm trying to list a player but i'm getting "permission denied" every time. My code is as follows:

var auctionDetails = new AuctionDetails(purchasedItemsResponse.ItemData[0].AssetId,
                                      AuctionDuration.OneHour, minBuy, buyNow);
var listAuctionResponse = await client.ListAuctionAsync(auctionDetails);

Any idea? Thanks a lot.

**Comment by DjTrilogic** [comment]
Move it to tradepile first man !

 

De : ulrickpsp [mailto:notifications@github.com] 
Envoyé : Thursday, October 1, 2015 5:25 PM
À : trydis/FIFA-Ultimate-Team-Toolkit <FIFA-Ultimate-Team-Toolkit@noreply.github.com>
Objet : [FIFA-Ultimate-Team-Toolkit] Permission denied when listing item from "Unassigned pile" (#152)

 

Hi mates! I'm trying to list a player but i'm getting "permission denied" every time. My code is as follows:

var auctionDetails = new AuctionDetails(purchasedItemsResponse.ItemData[0].AssetId,
AuctionDuration.OneHour, minBuy, buyNow);
var listAuctionResponse = await client.ListAuctionAsync(auctionDetails);

**Comment by ulrickpsp** [comment]
Thanks mate. Actually i've also tried what you suggest and same problem :(
