### ISSUE TITLE
GetPlayerImageAsync is not working

### ISSUE THREAD

**Issue by A-VORONKIN** [trydis/FIFA-Ultimate-Team-Toolkit#154]
await client.GetPlayerImageAsync(auctionInfo) is not working. I have HttpRequestException when I tried to use it. I changed CalculateBaseId to

            public long CalculateBaseId()
            {
                 return ItemData.AssetId;
            }

but it didn`t help...

**Comment by sansobarcelo** [comment]
Can you login?, Or do you have de "Unable to login" error?

**Comment by A-VORONKIN** [comment]
I can login and my bot works fine.

**Comment by A-VORONKIN** [comment]
Problem solved!
Just replace 
     public const string PlayerImage = "http://fifa15.content.easports.com/fifa/fifa/fltOnlineAssets/B488919F-23B5-497F-9FC0-CACFB38863D0/2016/fut/items/images/players/web/{0}.png";

 with 

     public const string PlayerImage = "http://fifa15.content.easports.com/fifa/fltOnlineAssets/B488919F-23B5-497F-9FC0-CACFB38863D0/2016/fut/items/images/players/web/{0}.png";
