### ISSUE TITLE
Search by ResourceId

### ISSUE THREAD

**Issue by sparkzi** [trydis/FIFA-Ultimate-Team-Toolkit#157]
Hello,
can anyone exmplain how to search FUT for exact player? After reading discussions here i was sure that i must find ResourceId for player and use it in PlayerSearchParameters like this:

                    var searchParameters = new PlayerSearchParameters
                    {
                        Page = 1,
                        Level = Level.Gold,
                        ChemistryStyle = ChemistryStyle.All,
                        ResourceId = -2147295496  // Ramires ?
                    };

But i recive many different players with many different resourceId. Can anyone help me and exmplain how to search for concrete player? Or maybe i have wrong ResourceId?

**Comment by tringler** [comment]
Hello,

I do it like this:

```
                            var searchParameters = new PlayerSearchParameters
                            {
                                Page = 1,
                                ResourceId = ResID
                            };
```

**Comment by sparkzi** [comment]
Thanks! I will check it today :)

**Comment by craigbaines** [comment]
The resource id's ea are displaying are false, or at least not what they were before. 

Take the resource id you get from them an add 4026531840) to it. 

That should bring it to the real resource id, then use that in your search. should work no problem.

**Comment by tringler** [comment]
Or just work with the AssetID instead of ResourceID

**Comment by craigbaines** [comment]
definition id is better

**Comment by tringler** [comment]
Which definition id?

**Comment by craigpbrown** [comment]
Do you know how they are calculating the negative Resource ID?

Take Messi for example:

His Asset ID is 158023.
The Resource ID returned from EA is -2147325625.

Adding 4026531840 to this is 1879206215 but when using this to search using either maskedDefId or definitionId then nothing is returned.

**Comment by tringler** [comment]
I still don't understand why you don't use the AssetID for the Searches

**Comment by craigpbrown** [comment]
What if you're wanting to Ronaldo's IF or Hero cards?

**Comment by tringler** [comment]
You cannot search after hero cards / IFs -. There is even no possibility to search after these in the Web App

**Comment by bradders591** [comment]
Nope, you can. Check again. Under quality i think

**Comment by tringler** [comment]
Nope you cannot :) You can search after for instance Ronaldo and then filter all cards with Rarity IF/IF2/... - But you cannot search especially for IF cards - They have not his own Asset ID

**Comment by bradders591** [comment]
Same difference though? :p

**Comment by craigpbrown** [comment]
They do not have their own asset ID but they have their own resource ID and definition ID and you can use the latter to search for their specific card :)

**Comment by tringler** [comment]
OK - Can someone give m an explanation of: AssetID, ResourceID (I thought it's always -2..... this year and not used by EA anymore) and DefinitionID?

**Comment by craigpbrown** [comment]
Asset ID is the base ID so regardless of how many IFs a player gets this will always be the same.

Resource ID is the ID of each specific IF card.

Definition ID is a value calculated based on Asset ID and card version that can be used to return only that specific Resource.

Not sure how EA are calculating Resource IDs this year though. Anyone know?

**Comment by tringler** [comment]
Thanks - Where I can find the definition ID in the JSON answer? I know Asset ID (like player ID), Trade ID (identifies the actual trade) and the ID in ItemData which keeps the same when you buy a player, send the player from watchlist to tradepile, relist the player, etc.

**Comment by tringler** [comment]
by the way ResourceID is just -2147483648 + AssetID - Am I wrong?

**Comment by kauefelipe** [comment]
Someone discovered how to perform the search by id? 

The resourceId is a big negative number and can´t be used in url... BaseId and AssetId is returning diferent players...

In the toolkit the search url is
```
if (ResourceId > 0)
  uriString += "&maskedDefId=" + ResourceId.CalculateBaseId(); // previously was "&definitionId="
```
