### ISSUE TITLE
Special card type to search players

### ISSUE THREAD

**Issue by A-VORONKIN** [trydis/FIFA-Ultimate-Team-Toolkit#158]
You can choose special card type to search players in web app. How to add it to Toolkit?

**Comment by JoaoFelipePego** [comment]
Hello, you have some email so I can contact you?

**Comment by A-VORONKIN** [comment]
Kobzar666@gmail.com

**Comment by tringler** [comment]
Search the special cards you want to in WebApp, trace it via Fiddler and Commit a pull request - You need to customize this part in RareType.cs:

```
namespace UltimateTeam.Toolkit.Models
{
    public enum RareType : byte
    {
        Regular = 0,
        Shiny = 1,
        InForm = 3,
        TeamOfTheYear = 5,
        TeamOfTheYear2 = 6,
        ManOfTheMatch = 8,
        TeamOfTheSeason = 11
    }
}
```

**Comment by tringler** [comment]
Pls close if solved.

**Comment by A-VORONKIN** [comment]
For now we can search only bronze, silver and gold card. how to add special card like this:
https://gyazo.com/16ba87a4f32d814736e04ea1b74b0c2b

**Comment by eupantof** [comment]
Actually, special cards are marked with a string, not a number.
We have to append "&rare=SP" to the link of the query (below is for IF Ozil):

    https://utas.s2.fut.ea.com/ut/game/fifa16/transfermarket?type=player&rare=SP&num=16&maskedDefId=176635&start=0

**Comment by A-VORONKIN** [comment]
Thanks, solved!
