### ISSUE TITLE
Keep getting Unable to Login error

### ISSUE THREAD

**Issue by thijsvanbloemendaal** [trydis/FIFA-Ultimate-Team-Toolkit#161]
Hi all,

I'm new to this toolkit, but I have managed to get the verification code from my mail. I use outlook to read the mail.

I'm getting the error:
+		e	{"Unable to login"}	System.Exception {UltimateTeam.Toolkit.Exceptions.FutException}
 +		e.InnerException	{"Index was outside the bounds of the array."}	System.Exception {System.IndexOutOfRangeException}

on this code:
ITwoFactorCodeProvider provider = new ImapTwoFactorCodeProvider();
                LoginResponse respons = await FC.LoginAsync(loginDetails, provider);
                return respons;

Any suggestions? Thanks!

**Comment by JoaoFelipePego** [comment]
Try use the same solution used here :)
https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/issues/149

**Comment by thijsvanbloemendaal** [comment]
Thanks for the tip, but I already check that one. My mail account doesn't support the Imap connection so I solved it differently.
Here is a snippet (I checked it while debugging, it get the the code from my outlook and returns it!):
    public Task<string> GetTwoFactorCodeAsync()
            {
                return Task.Run(async () =>
                {
                    await Task.Delay(10000);
                    var regex = new Regex(@"\d{6}");


                    for (var i = 0; i < 7; i++)
                    {
                        Microsoft.Office.Interop.Outlook.Application myApp = new Microsoft.Office.Interop.Outlook.Application();
                        var ns = myApp.Session;
                        var folders = ns.Folders[1].Folders[2];

                        var myInbox = folders.Items.Restrict("[Unread]=true"); 
                        if (myInbox.Count > 0)
                        {
                            for (int m = myInbox.Count; m > 0; m--)
                            {
                                int item = m;

                                // Grab the Body
                                var mail = (Microsoft.Office.Interop.Outlook.MailItem)myInbox[item];
                                string body = mail.Body;
                                // Sender Name
                                string sender = mail.SenderName;
                                if (sender == "EA")
                                {
                                    Match match = regex.Match(body);
                                    if (match.Success)
                                    {
                                        mail.UnRead = true;
                                        return match.Value;
                                    }
                                }
                            }
                        }

                            await Task.Delay(5000);
                        }



                        throw new FutException("Unable to find the two-factor authentication code.");
                    });
                }

**Comment by sesey** [comment]
e-mail account, log in again at each cycle.

**Comment by thijsvanbloemendaal** [comment]
What do you mean?

**Comment by thijsvanbloemendaal** [comment]
Ok I changed it to a gmail account so I can use imap now. (withoud the using statement)
Use the code like below, but keep getting the index out of bounds error

public Task<string> GetTwoFactorCodeAsync()
    {
        return Task.Run(async () =>
        {
            var regex = new Regex(@"((?<=class=""h1"">)\d{6})");

            var client = new ImapClient(_hostName, _username, _password, AuthMethods.Login, _port, _useUseSsl);
            
                for (var i = 0; i < 5; i++)
                {
                    var messages = client.SearchMessages(SearchCondition.Unseen().And(SearchCondition.From("EA")));
                    foreach (var match in messages.Select(message => regex.Match(message.Value.Body)).Where(match => match.Success))
                    {
                        return match.Value;
                    }
                    await Task.Delay(5000);
                }
            
            throw new FutException("Unable to find the two-factor authentication code.");
        });
    }

**Comment by nexiaz** [comment]
I have a SO too. Loginrequests.cs Row 170

**Comment by nexiaz** [comment]
https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/issues/137

Fixed the Issue for me!

**Comment by thijsvanbloemendaal** [comment]
Worked for me as well!
