### ISSUE TITLE
"PlayerSearch" error

### ISSUE THREAD

**Issue by sesey** [trydis/FIFA-Ultimate-Team-Toolkit#162]
After logging in, I do players search.

        private async void button_Click(object sender, RoutedEventArgs e)
        {
            try
            {
                var searchParameters = new PlayerSearchParameters
                {
                    Page = 1,
                    Level = Level.Gold,
                    League = League.BarclaysPremierLeague,
                    Nation = Nation.England,
                    Position = Position.Attackers,
                    Team = Team.ManchesterUnited,
                };
                var searchResponse = await client.SearchAsync(searchParameters);
                foreach (var auctionInfo in searchResponse.AuctionInfo)
                {
                    // Handle auction data
                }
            }
            catch (Exception exception)
            {
                MessageBox.Show(exception.ToString());
            }
            
        }

erros is here.
"deserializedObject = JsonConvert.DeserializeObject<T>(messageContent, JsonSerializerSettings);"
"messageContent" It is listed players but "deserializedObject" is null.

       protected static async Task<T> Deserialize<T>(HttpResponseMessage message) where T :class
        {
            message.EnsureSuccessStatusCode();
            var messageContent = await message.Content.ReadAsStringAsync();
            T deserializedObject = null;  
            try
            {
                deserializedObject = JsonConvert.DeserializeObject<T>(messageContent, JsonSerializerSettings);
            }
            catch (JsonSerializationException serializationException)
            {
                try
                {
                    var futError = JsonConvert.DeserializeObject<FutError>(messageContent, JsonSerializerSettings);
                    MapAndThrowException(serializationException, futError);
                }
                catch (JsonSerializationException)
                {
                    throw serializationException;
                }
            }

            return deserializedObject;
        }

error message
<a href="http://tinypic.com?ref=207km4y" target="_blank"><img src="http://i57.tinypic.com/207km4y.png" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by sansobarcelo** [comment]
If you quit all search parameters, do you have the same error?

**Comment by sesey** [comment]
I got the same error.

**Comment by tringler** [comment]
Cannot confirm - This is working:

```
                    var searchParameters = new PlayerSearchParameters
                    {
                        Page = cycle,
                        Level = (Level)DRP_Level.SelectedValue,
                        Nation = Convert.ToUInt16(DRP_Nation.SelectedValue),
                        Team = Convert.ToUInt16(DRP_Club.SelectedValue),
                        Position = DRP_Position.SelectedValue.ToString()
                    };
```

**Comment by trydis** [comment]
@sesey You're probably using an older version of the code, that doesn't include the `Nation` property in the `ItemData` class. Pull down the latest version or use the [nuget package](https://www.nuget.org/packages/UltimateTeam.Toolkit/).

**Comment by tringler** [comment]
Right - I remember I added the property manually.
