### ISSUE TITLE
GetTradePileAsync() Error

### ISSUE THREAD

**Issue by sansobarcelo** [trydis/FIFA-Ultimate-Team-Toolkit#163]
Hi, since tihs morning, when I use:

var tradePileResponse = await client.GetTradePileAsync();

I have this error:

Newtonsoft.Json.JsonSerializationException: Could not find member 'coinsProcessed' on object of type 'AuctionInfo'. Path 'auctionInfo[0].coinsProcessed', line 1, position 1251

EDIT: I only have this error some times

**Comment by trydis** [comment]
Are you able to grab an example using Fiddler?

Adding this to `AuctionInfo` will probably do the trick, although you may need to change `uint` depending on the actual values you're getting:
```
public uint CoinsProcessed { get; set; }
```

I'll add it to the toolkit code once we know what the values are.

**Comment by eupantof** [comment]
It may be null as well, so it's
       public uint? CoinsProcessed { get; set; }

**Comment by trydis** [comment]
Thanks @eupantof, I'll add it

**Comment by sansobarcelo** [comment]
The problem was solved with eupanof and trydis's solution. Thanks
