### ISSUE TITLE
InternalServerError in SearchAsync()

### ISSUE THREAD

**Issue by JoaoFelipePego** [trydis/FIFA-Ultimate-Team-Toolkit#164]
When trying to search for players InternalServerError error appears.
``Could not find member 'debug' on object of type 'AuctionResponse'. Path 'debug', line 1, position 9.``
  `` Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   em Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   em Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   em Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   em Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   em Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   em Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   em UltimateTeam.Toolkit.Requests.FutRequestBase.<Deserialize>d__22`1.MoveNext() ``

My code:
```C#
var searchParameters = new PlayerSearchParameters
            {
                Page = 1,
                Level = Level.Gold,
                ChemistryStyle = ChemistryStyle.Sniper,
                League = League.BarclaysPremierLeague,
                Nation = Nation.Norway,
                Position = Position.Striker,
                Team = Team.ManchesterUnited
            };

            var searchResponse = await client.SearchAsync(searchParameters);

```

All other methods work normally , only that ``SearchAsync`` gives error .

**Comment by trydis** [comment]
Take a look at #143. Are you searching too many times per minute? Also, the example in the README file is bad, since there are no norwegian strikers in manchester united anymore :smile:

**Comment by JoaoFelipePego** [comment]
I 'm trying to connect with the recently created account , to access the Transfers Market by WEB APP me on my browser displays this message ...
![capturar](https://cloud.githubusercontent.com/assets/5121313/10419134/f8622b20-7043-11e5-92cf-393dea0f98df.PNG)

I think that's the problem ... Has anyone experienced this same problem ?

**Comment by Lockedd** [comment]
You must continue to play FUT on your console, then the market will unlock when they verify your account.

**Comment by JoaoFelipePego** [comment]
I was using a newly created account and had not played the required amount of matches to unlock access to tranferencia market, therefore the error was occurring.
