### ISSUE TITLE
Unable to Login

### ISSUE THREAD

**Issue by ShrekIII** [trydis/FIFA-Ultimate-Team-Toolkit#165]
I know there are plenty of threads from ppl who got problems to log in.
I myself was able to let the system send me an email, get the code out of the email, but I still got an error every time I try to login.
Additional Information:
1. I bought Fifa 16
2. I am using it on PS4
3. I can run the Webapp, login and trade players that I see in my PS4 account.

`UltimateTeam.Toolkit.Exceptions.FutException: Unable to login ---> System.IndexOutOfRangeException: Der Index war außerhalb des Arraybereichs.
   bei UltimateTeam.Toolkit.Requests.LoginRequest.<GetNucleusIdAsync>d__16.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei UltimateTeam.Toolkit.Requests.LoginRequest.<PerformRequestAsync>d__8.MoveNext()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei UltimateTeam.Toolkit.Requests.LoginRequest.<PerformRequestAsync>d__8.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei UltimateTeam.Toolkit.FutClient.<LoginAsync>d__5.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter``1.GetResult()
   bei FUTCoinCollector.Form1.<Login>d__3.MoveNext() in C:\Users\Lars\Documents\Visual Studio 2015\Projects\FUTCoinCollector\FUTCoinCollector\Form1.cs:Zeile 50.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter``.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter``1.GetResult()
   bei FUTCoinCollector.Form1.<Login_button_Click>d__2.MoveNext() in C:\Users\Lars\Documents\Visual Studio 2015\Projects\FUTCoinCollector\FUTCoinCollector\Form1.cs:Zeile 37.
`

And here is the code snippet I use:

    public partial class Form1 : Form
    {

        public Form1()
        {
            InitializeComponent();
        }

        private void AddStatus(string msg)
        {
            StatusMemo.AppendText(msg + "\n");
            StatusMemo.Refresh();
        }

        private async void Login_button_Click(object sender, EventArgs e)
        {
            Login_button.Enabled = false;
            var client = new FutClient();
            AddStatus("Trying to login with " + LoginFifaAccountnameEdit.Text);
            try
            {
                var response = await Login(client);
            }
            catch (Exception ex)
            {
                AddStatus(ex.ToString());
            }
            Login_button.Enabled = true;
        }

        public async Task<LoginResponse> Login(FutClient client)
        {
            var loginDetails = new LoginDetails(LoginFifaAccountnameEdit.Text, LoginFifaAccountPasswordEdit.Text, LoginFifaSecretAnswerEdit.Text, Platform.Ps4);
            ITwoFactorCodeProvider provider = new ImapTwoFactorCodeProvider(LoginEmailAdressEdit.Text, LoginEmailPasswordEdit.Text, LoginEmailPop3Edit.Text, 993, true);
            var loginResponse = await client.LoginAsync(loginDetails, provider);
            return loginResponse;
        }
    }

I really do not know, what's going wrong.
Any help is greatly appreciated.

Thanks in advance

**Comment by trydis** [comment]
Take a look at the `SkipAuthenticatorAdvertise` in https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/issues/137. I'll look at adding that part to the toolkit soon.

**Comment by ShrekIII** [comment]
Thank you very much - that solved my problem!
