### ISSUE TITLE
Get Min and Max Price Ranges

### ISSUE THREAD

**Issue by A-VORONKIN** [trydis/FIFA-Ultimate-Team-Toolkit#167]
How to get Min and Max Price Ranges?

**Comment by eupantof** [comment]
POST: https://utas.s2.fut.ea.com/ut/game/fifa16/marketdata/item/pricelimits?itemIdList=242819554449

Response:
[{"source":"ITEM_DEFINITION","defId":188388,"itemId":242819554449,"minPrice":350,"maxPrice":10000}]
