### ISSUE TITLE
Get Players names?

### ISSUE THREAD

**Issue by ShrekIII** [trydis/FIFA-Ultimate-Team-Toolkit#168]
Hm, would like to get the player names, but I don't know where to find a file like in #23.
I really would prefer reading the names from a file (table) rather than getting them online.

Anyone knows where to get this kind of file for Fifa 16?

**Comment by tringler** [comment]
Here you are: https://fifa15.content.easports.com//fifa/fltOnlineAssets/B488919F-23B5-497F-9FC0-CACFB38863D0/2016/fut/items/web/players.json

**Comment by ShrekIII** [comment]
Thank you very much!
Really appreciate your contribution.
