### ISSUE TITLE
Accesing data in separate forms

### ISSUE THREAD

**Issue by RandomCodeGuy** [trydis/FIFA-Ultimate-Team-Toolkit#171]
How can I access the client in my main form from another form that is in the same namespace?

Greatly appreciated.

**Comment by trydis** [comment]
Pass a reference to the client to the form(s) that need access to it. 

[Passing Reference-Type Parameters -> Passing Reference Types by Value
](https://msdn.microsoft.com/en-us/library/s6938f28.aspx#Anchor_0)

**Comment by RandomCodeGuy** [comment]
Thank you very much. 
Forgive my lack of knowledge but why do we have to retrieve the Verification code every time. Can't we somehow use Origin's "Remember me"  ?

Also, do you have skype or maybe even an IRC chat?
