### ISSUE TITLE
List auction - Code: PermissionDenied, Reason: Incorrect parameters

### ISSUE THREAD

**Issue by jvianafec** [trydis/FIFA-Ultimate-Team-Toolkit#175]
Hello guys,

I have a problem when listing a card fitness...

you guys are going through it?

My code:
<code>var auctionDetails = new AuctionDetails(item.ItemData.Id, AuctionDuration.ThreeHours, 1200, 1300);
var listAuctionResponse = await f.ListAuctionAsync(auctionDetails);
</code>

Excepetion Message:
PermissionDenied, Reason: Incorrect parameter

StackTrace:
<code>
   em Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   em Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   em Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   em Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   em Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   em Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   em Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   em UltimateTeam.Toolkit.Requests.FutRequestBase.<Deserialize>d__0`1.MoveNext() na e:\fifa-ut\FIFA-Ultimate-Team-Toolkit-b412809bc8c45ed3df853a084b7ebbd93fbaec29\UltimateTeam.Toolkit\Requests\FutRequestBase.cs:linha 104
</code>

**Comment by tringler** [comment]
A fiddler log would help us

**Comment by jvianafec** [comment]
Thank you. This problem is because he could not directly sell the watch list, so I transferred to the market list and it worked!
