### ISSUE TITLE
Temprorary ban for selling or buying cards

### ISSUE THREAD

**Issue by A-VORONKIN** [trydis/FIFA-Ultimate-Team-Toolkit#183]
Sometimes I have temprorary bans for selling (listing) or buying cards. One time I even had this ban in game (I couldn't list any card because I sold too many cards). Also when it heppens in web app sometimes everything works fine and sometimes I also can't list/buy cards (depend of ban type). And when I have ban for buying cards I can search it on transfer market but can`t buy anything. Does anyone know how to avoid it?

**Comment by watcherize** [comment]
What kind of cards you're buying?

**Comment by A-VORONKIN** [comment]
consumables (contracts, fitness, healing)

**Comment by A-VORONKIN** [comment]
there is same problem with UltimateBot
https://ultimatebot.net/forum/showthread.php?tid=3628

**Comment by watcherize** [comment]
Well - It is very clear that they've updated the api A ALOT, now you cannot figure out the type of the card till you buy it, and they added some (actually cool) validations, so far you can avoid that buy making less rpm and for less total trading time.

**Comment by tringler** [comment]
Yes, I'm actually in a SELL/BUY BAN, too - Would be useful to know how many cards I can SELL/BUY until run into this temp BAN.

**Comment by tringler** [comment]
Is anyone able to determine when we get this sell ban? I have no idea :(

**Comment by jvianafec** [comment]
Yesterday I could not sell and purchase. This morning returned to normal.I recommend checking your RPM

**Comment by omrihaviv** [comment]
I think it's also related to total time running and not only RPM.
I use pretty low RPM (a request every 5-8 seconds) and still get a ban from time to time.

Anyone had luck with similar RPM when resting from time to time?

**Comment by D4NNY1000000** [comment]
I search every 5-8 seconds and it can run until a certain number of requests then a ban occurs.  That's with timed delays of 2 minutes every 250 requests.  Even if I logout and then resume later it will hit max requests and ban.

**Comment by tringler** [comment]
As far as I know you it's like this:

* too high RPM --> Expired Session
* too many transfermarket requests per Day (more than 5000 AFAIK) --> Transfermarket BAN
* too many SOLDs --> SELL BAN

**Comment by tringler** [comment]
There seems to be a 4th ban "BID BAN"

**Comment by StevenMcD** [comment]
How many "mini-bans" before a perma-ban? I used to auto-trade contracts in FIFA 14 and never got one and then with FIFA 15 they said that they would start banning. 

I used to keep my RPM pretty low as well. Would hate to get a perma-ban :cry:

**Comment by tringler** [comment]
I had at least 50 temp bans so far - No perma ban

**Comment by Bltfast** [comment]
Sadly I have to inform you that I receive a perm ban for my account. Initially I thought it was because I bought a player from another account of mine breaking EA terms. Right now another account has been banned and this one I used only with this tool. Is just me to be banned using Futbud?

**Comment by tringler** [comment]
Sorry to hear this - Maybe they found a connection between the accounts and banned them all? I think they have kinda coin seller detection (If you buy a low rated player for a very high price) implemented - I had the same in FIFA15.

**Comment by tringler** [comment]
I think this issue should be closed.
