### ISSUE TITLE
How to get the name of my club

### ISSUE THREAD

**Issue by JoaoFelipePego** [trydis/FIFA-Ultimate-Team-Toolkit#185]
I wonder somehow to be getting the club name I'm doing login?

**Comment by jvianafec** [comment]
<code>
var loginResponse = await fut.LoginAsync(loginDetails, provider);
</code>
<code>
var clubName = loginResponse.UserAccounts.UserAccountInfo.Personas.Select(s => s.UserClubList.Select(se => se.ClubName).FirstOrDefault()).FirstOrDefault();

</code>

**Comment by JoaoFelipePego** [comment]
thanks! work!
