### ISSUE TITLE
Code: Conflict

### ISSUE THREAD

**Issue by tringler** [trydis/FIFA-Ultimate-Team-Toolkit#187]
Hello,

could anyone explain to me what means Conflict as FUT Error code and how I can avoid? Thanks in Advance.

**Comment by trydis** [comment]
https://github.com/trydis/FIFA-Ultimate-Team-2014-Toolkit/issues?utf8=%E2%9C%93&q=conflict

**Comment by tringler** [comment]
Ok - Sorry - I will search before I post in future
