### ISSUE TITLE
Visual Studio Version Error

### ISSUE THREAD

**Issue by Bogenschuetze** [trydis/FIFA-Ultimate-Team-Toolkit#188]
Hey guys, which version of Visual Studio do you actually use? Im unable to use this toolkit in my visualstudio edition..

**Comment by trydis** [comment]
It would be nice to know which version you're using :smile: 

I've only checked that it works with 2013 Premium and 2015 Enterprise. I'm guessing 2013 Communtity  edition or newer/better should work.

**Comment by jvianafec** [comment]
> 2015 Enterprise and 2013 Communtity works
> 

Enviado do meu iPhone

**Comment by tringler** [comment]
Any errormessage which you can provide?

**Comment by Bogenschuetze** [comment]
https://gyazo.com/8d6bb19542de59db38dd32acff47f298
If i try to compile

**Comment by trydis** [comment]
You still haven't said anything about what version of Visual Studio you're using.

Anyway, you need to update Visual Studio to support "portable class libraries":
https://msdn.microsoft.com/en-us/library/gg597391(v=vs.110).aspx

**Comment by Bogenschuetze** [comment]
Im using the Visual Studio 2013 Express Version.
