### ISSUE TITLE
Expires always > 15?

### ISSUE THREAD

**Issue by MaxCaulfield** [trydis/FIFA-Ultimate-Team-Toolkit#190]
When I run the SearchAsync method with Page = 1, it seems there is never an item returned with Expires > 15 (seconds). If I refresh every second, any item that previously had an Expires property of 15 or 16 then disappears.

Do I need to treat the items differently when they are in their final seconds? Or is there an offset on this value?

**Comment by jvianafec** [comment]
No, when you search for page only, it will bring all results that are expiring, I recommend you use more as filters for example by League or Level

**Comment by MaxCaulfield** [comment]
Ok, thanks for the help!
