### ISSUE TITLE
Cookie container

### ISSUE THREAD

**Issue by grantw1991** [trydis/FIFA-Ultimate-Team-Toolkit#192]
Hi,

I'm new to this toolkit and I have been logging in and testing it out. Has anyone got the cookie container functionality working? I'd assume that it would be done automatically once you log in but each time the application requires the EA verification code. 

Thanks

**Comment by kauefelipe** [comment]
Did u find?

**Comment by grantw1991** [comment]
I thought I did after reading a post but not working as I thought.

It is saving the cookie and reading the cooking just not sure what to do to login using the cookie, I thought it would have determined it based on the code but doesn't seem to.

Just need an example of how someone is logging in using the TwoFactorCode from the cookie

**Comment by kauefelipe** [comment]
Look #137
