### ISSUE TITLE
Player Image

### ISSUE THREAD

**Issue by aleix10kst** [trydis/FIFA-Ultimate-Team-Toolkit#194]
Hi, I have some problems trying to get the player Image, could you help me please?
I've started now with c# and I'm not used to :)
Thx

**Comment by jvianafec** [comment]
<code>var imageBytes = await client.GetPlayerImageAsync(auctionInfo);</code>

:+1:

**Comment by aleix10kst** [comment]
Yes, that's what I've found, but I don't know how to use it TT

**Comment by bbday** [comment]
lol > byte[] > Format: PNG
Then you can choice to save byte[] to file or display it on your application.

**Comment by tringler** [comment]
I do it like this without the toolkit:

```
string futdbplayerImage = @"https://fifa15.content.easports.com//fifa/fltOnlineAssets/B488919F-23B5-497F-9FC0-CACFB38863D0/2016/fut/items/images/players/web/";

WebClient client = new WebClient();
Image playerImage = GetImage(futdbplayerImage + playerStrings[1] + ".png");
PIC_Player.Image = playerImage;
```
