### ISSUE TITLE
AE .Net Mail    Help needed, how to mark mails.

### ISSUE THREAD

**Issue by Bogenschuetze** [trydis/FIFA-Ultimate-Team-Toolkit#196]
Hey guys, do you know how to mark email as read in AE .Net Mail?

My Snippet looks like the following..Somebody knows how to mark the mails as read there?
And i also get alot of Session Expired... You know how to fix this? Sending each 3 sec's a coin request for example? Thanks in advance!!

           return Task.Run(async () =>
                {
                    var regex = new Regex(@"((?<=class=""h1"">)\d{6})");
                    await Task.Delay(60000);
                    string code="";
                    using (var client = new ImapClient(_hostName, _username, _password, AuthMethods.Login, _port, _useUseSsl))
                    {
                        for (var i = 0; i < 10; i++) 
                        {
                            var messages = client.SearchMessages(SearchCondition.Unseen().And(SearchCondition.From("EA")));
                            foreach (var match in messages.Select(message => regex.Match(message.Value.Body)).Where(match => match.Success))
                            {
                               code= match.Value;
                            }
                        }
                        return code;
                    }
                    throw new FutException("Unable to find the two-factor authentication code.");
                });

**Comment by kauefelipe** [comment]
....
  var messages = client.SearchMessages(SearchCondition.Unseen().And(                              SearchCondition.From("EA")), true, true);
....
  foreach (var message in messages)
...
    client.AddFlags(Flags.Seen, message.Value);
    client.AddFlags(Flags.Deleted, message.Value);
.....

**Comment by Bogenschuetze** [comment]
Thanks i will test it out ! :)
