### ISSUE TITLE
Keeping up the Session

### ISSUE THREAD

**Issue by Bogenschuetze** [trydis/FIFA-Ultimate-Team-Toolkit#198]
Hey guys, 
do you know how i can keep up the current session? Because i often get "session expired" if i delay some seconds.. 
Thanks in advance!

**Comment by tringler** [comment]
Define "some seconds" - I cannot confirm a few seconds, just when I send no requests a few minutes I need to relogin.

**Comment by Bogenschuetze** [comment]
I tried with sending coinUpdate request each 10 seconds, but after the third request i got session expired.. Which requests do you send?

**Comment by tringler** [comment]
can you send me the code of your coinrequest? The session should not expire.

**Comment by tringler** [comment]
Pls close if solved
