### ISSUE TITLE
Searching at the hour mark.

### ISSUE THREAD

**Issue by Levesque7** [trydis/FIFA-Ultimate-Team-Toolkit#200]
Just wondering if I'm doing something wrong. I'm searching at the hour mark for all players from a specific team, but there should be just over one card posted every second, and I'm not seeing anywhere close to that many. Probably about 1/20th of that, maybe less.

It seems that the app has issues refreshing the hour mark. Do you all just resort to sniping, or have you found a way to effectively refresh the hour mark?

**Comment by ipsq** [comment]
Change parameters to disable the cache.
