### ISSUE TITLE
login issue

### ISSUE THREAD

**Issue by a7medit** [trydis/FIFA-Ultimate-Team-Toolkit#202]
I'm always get {"debug":"","string":"","code":"500","reason":""} as a response when trying to get user account

**Comment by bbday** [comment]
I don't have this problem, 
Did you get ban?

**Comment by converge** [comment]
this is a temporary ban message

**Comment by a7medit** [comment]
I did get ban, as i can login normally.

**Comment by a7medit** [comment]
tried with different account and got the same response.

**Comment by bbday** [comment]
Maybe you have some problem with your code / account, cause nobody have same problem.

**Comment by a7medit** [comment]
May you provide a full code sample?, so that i can test it.

**Comment by jvianafec** [comment]
An error occurred while sending the request. when trying to log in, someone is having this problem?

**Comment by a7medit** [comment]
One more thing, I'm always get 0 as a nucleusId

**Comment by aboo** [comment]
I have the same issue. 
I created a new account and the result is the same.
I also tried on UltimateBot. The first account get error message straight away and the second one   (new account) shows the second factor authentication code but fails right after.

**Comment by lorenzh** [comment]
i think the two factor authentication was successfull. 
EA added a new Page after the two factor code authentication where you can update the authentication method.

you have to send a POST to cancel the update of authentication method

**Comment by kauefelipe** [comment]
Same problem here... 

Someone implemented this "post to cancel"...

```  LoginRequest.cs...
```                var shards = await GetShardsAsync(nucleusId);
```               var userAccounts = await GetUserAccountsAsync(_loginDetails.Platform);

I hope this must be included between this two lines...

**Comment by lorenzh** [comment]
i will create a pull request today with the "post to cancel"

**Comment by aboo** [comment]
Thanks @lorenzh 
I will try it out and will update here if the problem is solved by that change or not.

**Comment by trydis** [comment]
Closing, almost a month without any activity.
