### ISSUE TITLE
An error occurred while sending the request - try login

### ISSUE THREAD

**Issue by jvianafec** [trydis/FIFA-Ultimate-Team-Toolkit#204]
Hi,

Today, I started to get this error when trying to login.

"An error occurred while sending the request"

Someone goes through it too?

**Comment by JoaoFelipePego** [comment]
@jvianafec 

This error usually occurs due an interruption in your Internet connection. Try creating a HttpRequestException treatment making sure that the connection of your machine remains active.

Example:
```javascript
...
   catch(HttpRequestException){
           if(!System.Net.NetworkInformation.NetworkInterface.GetIsNetworkAvailable()){
           //Internet off
           }
           else{
           //Internet on
          }
    }
```

**Comment by jvianafec** [comment]
Valeu JoaoFelipe, realmente o request estava sendo barrado no firewall.

Valeu!
