### ISSUE TITLE
Search by ResourceId

### ISSUE THREAD

**Issue by kauefelipe** [trydis/FIFA-Ultimate-Team-Toolkit#207]
Hi guys.

The issue #157 was closed but i don´t discover how to use Search player by id.

i tried use ResourceId (-2096978694) or AssetID (173306)
```
 var search = new PlayerSearchParameters
                        {
                            Page = 1,
                            ResourceId = 173306 // Ansaldi -2096978694
                        };
```
But this is returning all different players...
I see in firebug (Firefox Plugin) at WebSite that the request url was:
https://utas.s2.fut.ea.com/ut/game/fifa16/transfermarket?type=player&start=0&maskedDefId=173306&num=16

This is similar url that toolkit is generating... maybe something different in the header? Anyone could help?

**Comment by kauefelipe** [comment]
Very strange... i tried another players like Rafinha (assetId 201400) and works...

Some player like this ansaldi had problem in his JSON (his club and league are wrong) response and search by ID doensn´t works... I don´t know how WebApp this search works...

**Comment by jvianafec** [comment]
mano,
Fiz uma pesquisa com o AssetID (173306) e retornou o Cristian Ansaldi.

O ResourceID não pode ser negativo.

Está apresentando erro somente quando você pesquisa com esse assetID?

**Comment by kauefelipe** [comment]
Opa,
realmente com o assetId esta funcionando... testei agora novamente.

Solved.
The real number is AssetId, not ResourceId.

Thanks
