### ISSUE TITLE
How get daily gift ?

### ISSUE THREAD

**Issue by kauefelipe** [trydis/FIFA-Ultimate-Team-Toolkit#209]
I´m trying to implement to BOT receive the daily gift (pack or money).

This was mentioned in #78 by @Spettacolo83

Like Spettacolo show in that issue, the first request is to show gifts is a post to:
https://utas.s2.fut.ea.com/ut/game/fifa16/activeMessage/

i could capture the response of this like:
{"Message":null,"Id":7,"Type":"displayOnce","Time":null,"StartTime":null,"RewardValue":"801","RewardType":"pack","Read":null}

This ID (7) should be use in the second request, that should be this:
https://utas.s2.fut.ea.com/ut/game/fifa16/activeMessage/7

Monitoring the requests (in fiddler or firebug) i could see that the second request don´t have any answer. Looks like that is only a post but in my implementation that doesn´t works...

I hope that the daily gifts will be offered until 4 january...

Someone could help me?

**Comment by kauefelipe** [comment]
Nobody ...?

The code is here:
https://github.com/kauefelipe/FIFA-Ultimate-Team-Toolkit-With-Gifts

To list gifts
```
            var giftsResponse = await _client.GetGiftsListAsync();
            var sb = new StringBuilder();
            
            foreach (var g in giftsResponse.ActiveMessage)
                sb.AppendLine(JsonConvert.SerializeObject(g));
            
            return sb.ToString();
```

To get gift
```
            var giftsResponse = await _client.GetGiftsListAsync();

            foreach (var g in giftsResponse.ActiveMessage)
            {
                var id = await _client.GetGiftAsync(g.Id);
            }
```

But this second (GetGiftAsync) doesn´t work...

**Comment by JoaoFelipePego** [comment]
Very good!

**Comment by kauefelipe** [comment]
The idea is good, but unfortunately not working ... lol

**Comment by kauefelipe** [comment]
@trydis could u help me? any idea?

The request of get detailed:
![headers](https://cloud.githubusercontent.com/assets/5603132/11988396/21bb38ec-a9d6-11e5-952f-062f1b186b56.png)
![cookies](https://cloud.githubusercontent.com/assets/5603132/11988402/366652cc-a9d6-11e5-93da-1c4758818b85.png)
![params](https://cloud.githubusercontent.com/assets/5603132/11988404/3d119636-a9d6-11e5-968b-244788a49fbf.png)
![response](https://cloud.githubusercontent.com/assets/5603132/11988405/40f99bf4-a9d6-11e5-85d8-b95c1df7d9e4.png)
![security](https://cloud.githubusercontent.com/assets/5603132/11988406/449ce3b0-a9d6-11e5-874c-62af74ea90a0.png)

**Comment by DjTrilogic** [comment]
As you can see, getting a gift is done through an Http Post with
X-Http-Methode-Override => "Delete"


On Thu, Dec 24, 2015 at 3:36 AM, kauefelipe <notifications@github.com>
wrote:

> @trydis <https://github.com/trydis> could u help me? any idea?
>
> The request of get detailed:
> [image: headers]
> <https://cloud.githubusercontent.com/assets/5603132/11988396/21bb38ec-a9d6-11e5-952f-062f1b186b56.png>
> [image: cookies]
> <https://cloud.githubusercontent.com/assets/5603132/11988402/366652cc-a9d6-11e5-93da-1c4758818b85.png>
> [image: params]
> <https://cloud.githubusercontent.com/assets/5603132/11988404/3d119636-a9d6-11e5-968b-244788a49fbf.png>
> [image: response]
> <https://cloud.githubusercontent.com/assets/5603132/11988405/40f99bf4-a9d6-11e5-85d8-b95c1df7d9e4.png>
> [image: security]
> <https://cloud.githubusercontent.com/assets/5603132/11988406/449ce3b0-a9d6-11e5-874c-62af74ea90a0.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/issues/209#issuecomment-167028203>
> .
>



-- 
*Abdessamad Benslimane*
Email: Abdessamad.Benslimane@gmail.com
Téléphone: +33 6 05 56 47 27

**Comment by DjTrilogic** [comment]
I've something like this:

---



        public async Task<byte> PerformRequestAsync()        {
   AddMethodOverrideHeader(HttpMethod.Delete);
AddCommonHeaders();            var activeMessageRedeemResponseMessage
= await HttpClient
.PostAsync(string.Format(Resources.ActiveMessages + "/"
+_activeMessage.Id),new StringContent(" "))
.ConfigureAwait(false);
activeMessageRedeemResponseMessage.EnsureSuccessStatusCode();
  return 0;        }

**Comment by kauefelipe** [comment]
Great! Works fine!

Thank you @DjTrilogic !

**Comment by tringler** [comment]
Can you pls send this as pull request?

**Comment by kauefelipe** [comment]
Yes,
I will do this soon...

**Comment by kauefelipe** [comment]
Daily gift #212
