### ISSUE TITLE
I can't sell my items

### ISSUE THREAD

**Issue by Bltfast** [trydis/FIFA-Ultimate-Team-Toolkit#210]
I receive this exception: 

Code: PermissionDenied, Reason: Incorrect parameters

but I use the code shown in your documentation.

Here is the code:

            var watchlistResponse = await _client.GetWatchlistAsync();

            IEnumerable<AuctionInfo> wonBids = watchlistResponse.AuctionInfo.Where(o => o.TradeState.Contains("closed") && o.BidState.Contains("highest"));
            foreach (AuctionInfo item in wonBids)
            {
                if (item.ItemData != null)
                {
                    var auctionDetails = new AuctionDetails(item.ItemData.Id,
                                                            AuctionDuration.OneHour,
                                                            SELL_MIN_VALUE,
                                                            SELL_BUYNOW);

                    try
                    {
                        await _client.ListAuctionAsync(auctionDetails);
                    }
                    catch (Exception ex)
                    {
                        // manage exception
                    }
                }
            }

There is an inner excpetion too:

Could not find member 'debug' on object of type 'ListAuctionResponse'. Path 'debug', line 1, position 9.

Please help me, what is wrong here?

**Comment by tringler** [comment]
You need to send your item to tradepile before list the auction.

**Comment by tringler** [comment]
Pls close if solved
