### ISSUE TITLE
Database of all players of FIFA 16 UT.

### ISSUE THREAD

**Issue by JoaoFelipePego** [trydis/FIFA-Ultimate-Team-Toolkit#211]
Can anyone help me find a database file that contains all players of FIFA 16 UT, and also the club, nationality and all characteristics of the players?

I'm using http://cdn.content.easports.com/fifa/fltOnlineAssets/B488919F-23B5-497F-9FC0-CACFB38863D0/2016/fut/items/web/players.json file to the list of players, but this file does not contain more detailed information from players such as club, PAC, SHO ... :(

**Comment by bbday** [comment]
there isn't any db that have this information, you must call each item to get info about them, like EA do on web search.

**Comment by kauefelipe** [comment]
I´m using the json of #145 
Thanks to @bradders591

**Comment by JoaoFelipePego** [comment]
@kauefelipe 
The available link in issue #145 (http://www.filedropper.com/playerstar) does not work, could make its json file players?

**Comment by kauefelipe** [comment]
Fala teu email que eu te mando...

**Comment by JoaoFelipePego** [comment]
@kauefelipe 
joaofelipepego1995@hotmail.com

**Comment by kauefelipe** [comment]
Mandei la para vc

**Comment by JoaoFelipePego** [comment]
Thanks!

**Comment by Extremeg** [comment]
@kauefelipe 
Do you can send me the mail too pls?

peter.nather@aol.com

**Comment by kauefelipe** [comment]
@Extremeg: Sent to your mail...

**Comment by benbartels** [comment]
Hi can you please sent me this json too?
i do a test php project for my eleven years old son.
Thank you very much 
sent it to benbartels@googlemail.com

**Comment by kauefelipe** [comment]
@benbartels : Sent...

**Comment by a7medit** [comment]
@kauefelipe 

may i get this json too? 

a7medit@hotmail.com
