### ISSUE TITLE
Exception on login

### ISSUE THREAD

**Issue by lkuklis** [trydis/FIFA-Ultimate-Team-Toolkit#214]
Hi,
I have problem when trying to login.

```
            var path = @"C:\Temp\cookie.cont";
            var cookieContainer = CookieManager.Read(path);
            client= new FutClient(cookieContainer);
            var loginDetails = new LoginDetails(....);
            ITwoFactorCodeProvider provider = new PopupTwoFactorCodeProvider();
            var loginResponse = await client.LoginAsync(loginDetails, provider);
```
When I provide code from email I receive.
```
{"Could not find member 'debug' on object of type 'UserAccounts'. Path 'debug', line 1, position 9."}
```
When 'cookieContainer' does not exists (first time login) it returns "return new CookieContainer();`'
Popup properly return Code.
My account is activated.

Has anyone any ideas what is wrong whit my approach ?

**Comment by kauefelipe** [comment]
Resolved in #202

**Comment by lkuklis** [comment]
Ok, Thank You. I switch to your repo and it works great.

**Comment by kauefelipe** [comment]
Ok, but it´s not my repo...

It´s a @lorenzh 's repo
