### ISSUE TITLE
Need help testing v2.2.0-rc2

### ISSUE THREAD

**Issue by trydis** [trydis/FIFA-Ultimate-Team-Toolkit#218]
Would be great if someone could try out the changes in the upcoming version, before i push "the real deal".

Thanks.

Changes:
https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/pull/217
https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/pull/216
https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/pull/213

NuGet package: https://www.nuget.org/packages/UltimateTeam.Toolkit/2.2.0-rc2

**Comment by Lululuz** [comment]
https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/pull/216
Please see comment :)

**Comment by trydis** [comment]
Thanks for the testing/feedback @Lululuz. I'm depending on the community to test things this year, since i haven't touched ultimate team in ages. Will update this issue with the new prerelease when it's ready.

**Comment by trydis** [comment]
Pushed rc2, I'll leave this open a few days, unless i get a :+1: from someone before that.
