### ISSUE TITLE
Help with search please 

### ISSUE THREAD

**Issue by markc939** [trydis/FIFA-Ultimate-Team-Toolkit#222]
Hi,

Could somebody please tell me how I setup a search for shiny gold contract cards only, or at least how I tell a searched card is shiny gold ?

I've scoured the code and tried various things to no avail.

I know i need to search for gold and developmenttype.contract 
but what can I check to make sure its a shiny gold card please ?

Is it to do with subcardtype ?

Thanks in advance, sorry if I should not have raised this as an issue.
Regards
Mark.

**Comment by tringler** [comment]
If you describe how you would do this directly in the WebApp we can help you, but as far as I know there is no way to find shiny contracts.

**Comment by markc939** [comment]
It's ok I;ve worked out what i need to do thanks.
