### ISSUE TITLE
GitHub error

### ISSUE THREAD

**Issue by tringler** [trydis/FIFA-Ultimate-Team-Toolkit#223]
Hello,

for my next pull request I refreshed my forked master from this master, created a new branch and now I have this in IFutClient.cs:
 
```
<<<<<<< HEAD
=======
        Task<DefinitionResponse> GetDefinitionsAsync(long baseId);
       
>>>>>>> refs/remotes/trydis/master
        Task<List<PriceRange>> GetPriceRangesAsync(IEnumerable<long> itemIds);
    }
 ```

Any ideas how to fix?

Thanks, Thomas

**Comment by trydis** [comment]
That's a Git merge conflict. Loads of info if you google for it.

An easy way to avoid those is to never commit directly to your master, only to "feature branches". Then every pull from my master to your master will be a fast-forward.

**Comment by tringler** [comment]
Ok - Thanks.
