### ISSUE TITLE
Login broken

### ISSUE THREAD

**Issue by tringler** [trydis/FIFA-Ultimate-Team-Toolkit#225]
Hello,

can anyone confirm the login is currently broken? - I'm not able to get my two factor code - Even not via the WebApp in the browser.

**Comment by mtdx** [comment]
They ban bots without pin requests.

**Comment by tringler** [comment]
The account still works in-game - It is a temp. web app ban or it is a permament?

**Comment by tringler** [comment]
EA reported it's a known issue which will be solved within the next 24h. It's not a BAN.
