### ISSUE TITLE
Could not find member "tradeIdStr"

### ISSUE THREAD

**Issue by A-VORONKIN** [trydis/FIFA-Ultimate-Team-Toolkit#227]
I have JsonSerializationException: Could not find member "tradeIdStr" on object of type 'AuctionInfo'.

**Comment by gladtbx** [comment]
Same here

**Comment by gladtbx** [comment]
Fixed

Add line "        public string TradeIdStr { get; set; }" to File AuctionInfo.cs under public class AuctionInfo.

Line 37 if you are not sure where to add it.

**Comment by Spettacolo83** [comment]
Thanks gladtbx! Works perfect!

**Comment by gladtbx** [comment]
Also, if you are trying to list, add line "public string idStr { get; set; }" to File ListAuctionResponse.cs as well. Line 6 would be good.

**Comment by Spettacolo83** [comment]
Thanks! Done it!
