### ISSUE TITLE
Add JSON attribute to AuctionInfo

### ISSUE THREAD

**Issue by boikamlott** [trydis/FIFA-Ultimate-Team-Toolkit#228]
Hi,

Since this afternoon, my bot complains about about a missing 'tradeIdStr' in the JSON response AuctionInfo object.
If any of you had the same issue, you just need to add: `public string TradeIdStr { get; set; }`
to the `AuctionInfo` class.
After trying to sell a player it complains about a missing 'idStr' field in `ListAuctionResponse`.
I did not fix this one yet but I'm sure we just need to add `public string IdStr {get; set;}` as well.
It's just the response parsing which fails for this one so it does matter much, player is sucessfully for sold but your logs might be polluted a bit.
I hope EA has not put 'Str' fields in JSON response everywere.
If so maybe it's easier to change JSON deserializator settings to allow missing field in the toolkit model classes...
I wanted to do a PR but I'm such a newbie with windows devlopment tools that I wont do.
Should be quite straight forward to fix anyway.

**Comment by gladtbx** [comment]
The idStr fix is mentioned in:
https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/issues/227

**Comment by boikamlott** [comment]
ok sorry, issue closed.
