### ISSUE TITLE
Get a Players name

### ISSUE THREAD

**Issue by CoverJ** [trydis/FIFA-Ultimate-Team-Toolkit#23]
Hi guys,

firstly to trydis, thank you very much man. An epic effort to get all this together and to share it :)

now onto the question, how can I get a players name? I was getting their resourceID and using the api at 
http://www.fut15players.com/ which doesn't work for me anymore and they are prompting me to buy the database. So I was wondering if there was a way to get it from the toolkit?

From the readme I seen var item = await client.GetItemAsync(auctionInfo); but I could not find a way to extract the name from item.

Thanks for any help :)

**Comment by pulkitsharma** [comment]
Can somebody send me the link for mapping of assetIds and Manager/Coach Name for staff cards like it is there for players.json. I already tried substituting staff.json
