### ISSUE TITLE
New error?

### ISSUE THREAD

**Issue by Bltfast** [trydis/FIFA-Ultimate-Team-Toolkit#230]
Calling GetWatchlistAsync() method but even others I get this error:

Could not find member 'tradeIdStr' on object of type 'AuctionInfo'. Path 'auctionInfo[0].tradeIdStr', line 1, position 1047.

Cheers

**Comment by trydis** [comment]
Take a look at [this](https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/pull/229/files), will include the changes asap.

**Comment by Bltfast** [comment]
ok solved! thanks a lot
