### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by vhrustic** [trydis/FIFA-Ultimate-Team-Toolkit#231]
About 10 days ago I started to have problems with login(actually I can't login at all). Everything was flawless, as I used this toolkit sucessufuly for  4 months. I am using well known ImapTwoFactorCodeProvider which didn't have any problems with reading my mail and getting EA's code. I tried to change regex which capture security code, and I managed to get code without problem(I debugged an aplication and code was okay). I just get generic exception 'Unable to Login'. Can't figure it out why.. My web app works without problem, PC game also, it's just I can't login anymore.

Has anyone encountered same problem? Basicly my login suddenly stopped working, my friend also have a same problem.

**Comment by A-VORONKIN** [comment]
Sometimes I have a same problem

**Comment by tringler** [comment]
Did you check with fiddler what your toolkit doing and compared it with the fiddler log the webapp created?

**Comment by gladtbx** [comment]
Similar problem happens, but after a few tries you can login. I think it probably is the issue on the EA server side.

**Comment by vhrustic** [comment]
After extensive search I managed to fix the problem and it was my fault. After all it was problem in my regex. Thank you all for your help. Issue can be closed.
