### ISSUE TITLE
Unassigned Items

### ISSUE THREAD

**Issue by DarkVador101** [trydis/FIFA-Ultimate-Team-Toolkit#234]
can we send all Unassigned items to club through this toolkit with one request?

**Comment by kauefelipe** [comment]
No....

**Comment by DarkVador101** [comment]
thanks, I guess I will just have to loop through the list.

**Comment by kauefelipe** [comment]
Yes, i do this...

**Comment by razarlive** [comment]
it would be better to send one request rather than spend multiple requests for these packs due to the security.

**Comment by DarkVador101** [comment]
I implemented auto-assign all. it took 30 minutes. it would be nice to add it to the toolkit.
