### ISSUE TITLE
Fiddler help please!

### ISSUE THREAD

**Issue by razarlive** [trydis/FIFA-Ultimate-Team-Toolkit#235]
I am trying to use the Fiddler web debugger rather than chrome extension and the tool isn't working for me. it is not capturing any of the app requests. The chrome extension is working capturing the requests fine.   I enabled HTTPs Capture and Decryption. 
What else am I missing?

**Comment by DarkVador101** [comment]
try to use IE instead of chrome.

**Comment by tringler** [comment]
You should work via the local Fiddler proxy

**Comment by tringler** [comment]
Pls close the issue if solved.

**Comment by tringler** [comment]
@trydis Can you pls close it - 18 days without feedback.
