### ISSUE TITLE
Help with GetPriceRangesAsync

### ISSUE THREAD

**Issue by kauefelipe** [trydis/FIFA-Ultimate-Team-Toolkit#237]
Hello,
i´m trying to use "GetPriceRangesAsync" ...

I tried 
`var tradePileResponse = await _client.GetTradePileAsync();`
`var priceRanges = await _client.GetPriceRangesAsync(tradePileResponse.AuctionInfo.Select(ai => ai.CalculateBaseId()));`

or 
`var tradePileResponse = await _client.GetTradePileAsync();`
 `var priceRanges = await _client.GetPriceRangesAsync(tradePileResponse.AuctionInfo.Select(ai => ai.ItemData.Id));            `

...but  not working...

Someone could help me?

**Comment by tringler** [comment]
What is not working? Syntax error? Empty response?

**Comment by kauefelipe** [comment]
Exception in the call...

Message:

> Code: NotFound

Stack

>   at UltimateTeam.Toolkit.Requests.FutRequestBase.MapAndThrowException(Exception exception, FutError futError)
   at UltimateTeam.Toolkit.Requests.FutRequestBase.<Deserialize>d__22`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at UltimateTeam.Toolkit.Requests.PriceRangesRequest.<PerformRequestAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at FutClient2015.Gerenciadores.ManipuladorDaTradePile.<ExibirItens>d__4.MoveNext()

**Comment by tringler** [comment]
Your 2nd code example should work - Can you fiddler it and show me the request you are trying to send?

**Comment by kauefelipe** [comment]
I don´t have fiddler in this machine and can´t install...
The final url request for example is:

> https://utas.s2.fut.ea.com/ut/game/fifa16/marketdata/item/pricelimits?itemIdList=249351565296,250263101928,250220706821,250275582346,248928576073,250242086236,249813174275,244901970785,250294301185,250294789742,250236443555,249186881781,247168135328,249979347406,246055662757,245130100703,249898864779,246775317190,247105922225,246312427434,250286551046,248946132848,248115569759,250280513180,241257277685,249920968828,250300047226,249095343834,242813187848,247166941663

**Comment by tringler** [comment]
Normally this is the behaviour if you didn't call watchlist/tradepile before. This like I do:

```
            PriceRange priceRange = new PriceRange();
            List<long> savedItems = new List<long>();

            try
            {
                await GetTradepile();
                savedItems.Add(itemId);
                var priceRanges = await futClient.GetPriceRangesAsync(savedItems);

                foreach (PriceRange prices in priceRanges)
                {
                    priceRange.MaxPrice = prices.MaxPrice;
                    priceRange.MinPrice = prices.MinPrice;
                }

                return priceRange;
            }
````
This is currently working.

**Comment by kauefelipe** [comment]
Ok, no problem...

**Comment by tringler** [comment]
Can you try again? It's working again at my app.

**Comment by kauefelipe** [comment]
Same error... 404 - NotFound

**Comment by tringler** [comment]
Really weird - It's working in my code - Can proof you are not sending any requests between the tradepile request and the pricerange request?

**Comment by kauefelipe** [comment]
The code is exactly like this:
`var tradePileResponse = await _client.GetTradePileAsync();
var priceRanges = await _client.GetPriceRangesAsync(tradePileResponse.AuctionInfo.Select(ai => ai.CalculateBaseId()));`

**Comment by tringler** [comment]
I'm afraid I cannot help without any Fiddler logs, because you see I'm using exactly the same code and it's working.

**Comment by kauefelipe** [comment]
I will go home on Thursday and I can install on my PC and then show here the log

**Comment by tringler** [comment]
Maybe another user can confirm / not confirm the behaviour?

**Comment by engate** [comment]
It's not working because you don't have that item in the tradepile.

**Comment by tringler** [comment]
Yes, that could be the reason. You need to have the item in your previous response or you get the 404.

**Comment by kauefelipe** [comment]
Great @engate...

I had some items previously listed in TradePile . I removed them in the "select" and then is now working perfectly !

Thank you engate and tringler for the help!

The final code:
`var tradePileResponse = await _client.GetTradePileAsync();`
`var ids = tradePileResponse.AuctionInfo.Where(ai => ai.Expires == -1).Select(ai => ai.ItemData.Id);`
`var priceRanges = await _client.GetPriceRangesAsync(ids);`
