### ISSUE TITLE
Remove all Sold

### ISSUE THREAD

**Issue by mtdx** [trydis/FIFA-Ultimate-Team-Toolkit#239]
Why do we have to remove each sold card with RemoveFromTradePileAsync when there is a nice "Remove All Sold" call? 
http://prntscr.com/aeilho

**Comment by jvianafec** [comment]
checks whether the item already the current bid is greater than 0 and the time is -1

**Comment by mtdx** [comment]
Can't we just make that call? seems such a waste of RPMs

**Comment by jvianafec** [comment]
anyway, u will have to do this query. It is not disperdicio. unless you know exatamenti itemdata.id the item you want to remove.

**Comment by Lululuz** [comment]
For the watchlist you can hand over a list containing the auctioninfos you want to remove. Maybe it works the same way if you ajust the toolkit for the tradepile. If there is a function on the webapp there is also a way of implementing it in the toolkit.

**Comment by tringler** [comment]
I provided a pull request: https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/pull/241
