### ISSUE TITLE
New version - 3.0.0

### ISSUE THREAD

**Issue by trydis** [trydis/FIFA-Ultimate-Team-Toolkit#244]
I've pushed a prerelease version of 3.0.0 to [NuGet](https://www.nuget.org/packages/UltimateTeam.Toolkit/3.0.0-rc3), based on the [vnext branch](https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/tree/vnext).

Includes:
https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/pull/238
https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/pull/240
https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/pull/241
https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/pull/251

I've rewritten some of the stuff, so let me know below if something is broken.

**Comment by Extremeg** [comment]
Do you can add the support to open player packs pls?

**Comment by mtdx** [comment]
What happened with client.RequestFactories.CookieContainer?

**Comment by trydis** [comment]
I see that it was removed here: https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/pull/238/files#diff-12cb7e6a147c95d0cbf87b9bb653e38fL93. 

I guess there are no reason to remove it, so i'll add it again. Thanks for the feedback @mtdx.

**Comment by mtdx** [comment]
@tringler any reason you removed it? Is there another method? https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/pull/238/files#diff-12cb7e6a147c95d0cbf87b9bb653e38fL93.

**Comment by tringler** [comment]
No, obviously my fault

**Comment by mtdx** [comment]
@tringler I get {"error":"invalid_grant","error_description":"code is invalid"} when I try to connect via companion app, but I did checked, the emails codes are good and the web app login works fine with emails codes, any ideas?

**Comment by tringler** [comment]
after which call?

**Comment by mtdx** [comment]
GET /p/mobile/fifa/companion/code?code=QUORADljvCxnYZFJlwfMNOyK.......
then
POST /connect/token HTTP/1.1
{"error":"invalid_grant","error_description":"code is invalid"}

I write to the console the call to the ITwoFactorCodeProvider and I see beeing called and that the returned code is right.

**Comment by tringler** [comment]
You know that these codes have nothing to do with the TwoFactor codes right? Normally LoginMobileRequest.cs should send your code `GET /p/mobile/fifa/companion/code?code=QUORADljvCxnYZFJlwfMNOyK.......` into the GetAuthTokenAsync method.

**Comment by mtdx** [comment]
Looks to me that it gets blocked at the TwoFactor email code, I keep getting EA codes on email, I didn't do nothing custom, is the vnext branch as it is. Where is the issue?

http://prntscr.com/al9z48

**Comment by tringler** [comment]
Can you post your code where you test the vnext branch?

**Comment by mtdx** [comment]
ITwoFactorCodeProvider provider = new ImapTwoFactorCodeProvider(Gmail, Gpassword);
                LoginDetails loginDetails = new LoginDetails(Email, Password, FutSecurityAnswer, Platform.Ps3, AppVersion.CompanionApp);
                LoginResponse loginResponse = await _utClient.LoginAsync(loginDetails, provider);
                CookieContainer cookiecontainer = _utClient.RequestFactories.CookieContainer;
....

I doesn't get past Login, Get this exception 
UltimateTeam.Toolkit.Exceptions.FutException: Unable to login to WebApp ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at UltimateTeam.Toolkit.Requests.FutRequestBase.<DeserializeAsync>d__41`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at UltimateTeam.Toolkit.Requests.LoginRequestMobile.<GetAuthTokenAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at UltimateTeam.Toolkit.Requests.LoginRequestMobile.<PerformRequestAsync>d__15.MoveNext()
   --- End of inner exception stack trace ---
   at UltimateTeam.Toolkit.Requests.LoginRequestMobile.<PerformRequestAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at UltimateTeam.Toolkit.FutClient.<LoginAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ...

**Comment by tringler** [comment]
You should debug it and check which code used here: `var authToken = await GetAuthTokenAsync(**_code**);`

It should be the code you get here: `GET /p/mobile/fifa/companion/code?code=QUORADljvCxnYZFJlwfMNOyK.......`

**Comment by trydis** [comment]
@mtdx: I've pushed a new prerelease to NuGet, which has the CookieContainer getter.

**Comment by mtdx** [comment]
Thanks @trydis , 

@tringler I see in the POST https://accounts.ea.com/connect/token HTTP/1.1 

`grant_type=authorization_code&code=&client_id=FIFA-16-MOBILE-COMPANION....`

Code is empty, but why? do you have any ideas?

**Comment by tringler** [comment]
After the sending your TwoFactorCode you should get code here:

```
        private async Task SetTwoFactorCodeAsync(HttpResponseMessage loginResponse)
        {
            var tfCode = await _twoFactorCodeProvider.GetTwoFactorCodeAsync();

            var responseContent = await loginResponse.Content.ReadAsStringAsync();

            AddReferrerHeader(loginResponse.RequestMessage.RequestUri.ToString());

            var codeResponseMessage = await HttpClient.PostAsync(loginResponse.RequestMessage.RequestUri, new FormUrlEncodedContent(
                        new[]
                            {
                            new KeyValuePair<string, string>(responseContent.Contains("twofactorCode") ? "twofactorCode" : "twoFactorCode", tfCode),
                            new KeyValuePair<string, string>("_eventId", "submit"),
                            new KeyValuePair<string, string>("_trustThisDevice", "on"),
                            new KeyValuePair<string, string>("trustThisDevice", "on")
                            }));

            codeResponseMessage.EnsureSuccessStatusCode();

            var contentData = await codeResponseMessage.Content.ReadAsStringAsync();

            if (contentData.Contains("Incorrect code entered"))
                throw new FutException("Incorrect TwoFactorCode entered.");

            if (contentData.Contains("Tired of waiting for your code?"))
                await SkipAuthenticatorAdvertise(codeResponseMessage);

            //TO DO: How to verify, that content is a companion code
            else if (contentData.Length <= 64)
            {
                _code = contentData;
            }
        }
```

Yoh should check what you get as contentData.

**Comment by mtdx** [comment]
I get the code as content QUORADljCByGxEjIcsydFmp..... but is 40 length, code so because of the contentData.Length <= 64 it doesn't get assigned?

**Comment by tringler** [comment]
for sure it should be assigned, because it's lower than 64 - Pls verify why it doesn't get assigned by debugging

**Comment by mtdx** [comment]
OK, it goes into SkipAuthenticatorAdvertiseAsync which doesn't assigned _code but gets the right content but _code never gets assigned when SkipAuthenticatorAdvertiseAsync returns since is an else if
`
var contentData = await authenticatorResponseMessage.Content.ReadAsStringAsync();` in SkipAuthenticatorAdvertiseAsync remain unused.

**Comment by mtdx** [comment]
Other than the login issue above everything seems to be working but I think we need better exception handling on mobile, which seems to be lacking with just "Response code doesn't indicate success" also getting the gifts list is not implemented.

**Comment by tringler** [comment]
>  also getting the gifts list is not implemented.
Yes, because I don't know if gifts even implemented in the CompanionApp and if yes, I need the requests/responses for it - That's the reason why it's not implemented. It's the same like for captcha handling, but this I will implement as soon as the vnext brach got merged. See https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/issues/246

I know the bug, which you described, but this should be fixed with that commit:
https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/pull/238/commits/7539363ee6565e58edc1512488a962a3bd48dda2?diff=unified

I'm also OK with this fix, but then https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/pull/238/commits/7539363ee6565e58edc1512488a962a3bd48dda2?diff=unified should be reverted, because I'm doing exactly the same here:
```
                 await SetTwoFactorCodeAsync(loginResponseMessage);
 +            
 +            //TO DO: How to verify, that content is a companion code
 +            else if (contentData.Length <= 64)
 +            {
 +                _code = contentData;
 +            }
```

**Comment by mtdx** [comment]
Don't know what to say about how to fix the bug, I just added that "if" in SkipAuthenticatorAdvertise and worked fine after.

**Comment by tringler** [comment]
I assume **you don't apply the commit** https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/pull/238/commits/7539363ee6565e58edc1512488a962a3bd48dda2 - You added this inside the call SkipAuthenticatorAdvertise here: 

```
             else if (contentData.Length <= 64)
              {
                  _code = contentData;
              }
```

and I added it outside the call here:

```
             await SkipAuthenticatorAdvertise(codeResponseMessage);

             //TO DO: How to verify, that content is a companion code
             else
             else if (contentData.Length <= 64)
              {
                  _code = contentData;
              }
```

**Comment by mtdx** [comment]
I have the vnext with all its commits, but here in SetTwoFactorCodeAsync
```
            if (contentData.Contains("Tired of waiting for your code?"))
                await SkipAuthenticatorAdvertise(codeResponseMessage);

            //TO DO: How to verify, that content is a companion code
            else if (contentData.Length <= 64)
            {
                _code = contentData;
            }
```
you can see that it goes into SkipAuthenticatorAdvertise which doesn't do   _code = contentData; and when it returns due to the else it just exits the function. 

The file you mention doesn't have that double else else you're pasting, also a double else else would not work in that context. I think we already confused @trydis, we may need to do a pull request on this.

https://github.com/tringler/FIFA-Ultimate-Team-Toolkit/blob/7539363ee6565e58edc1512488a962a3bd48dda2/UltimateTeam.Toolkit/Requests/LoginMobileRequest.cs

**Comment by tringler** [comment]
I'm also confused, but I think I got it now! :D 

@trydis: Can you apply @mtdx proposal? I just realized I never ran into the SkipAuthenticatorMethod, since I have activated the Google Authenticator.

**Comment by tringler** [comment]
@Extremeg Pls remove this post from this thread.

**Comment by tringler** [comment]
@trydis - I pushed a PR which contains the both bugfixes @mtdx mentioned. Accidently pushed into master branch, but it should not be a problem to apply it to vnext branch as far as I know.

**Comment by trydis** [comment]
Thanks @tringler, I'll take a look tomorrow :+1:

**Comment by trydis** [comment]
I've pushed another prerelease package, which includes #251: https://www.nuget.org/packages/UltimateTeam.Toolkit/3.0.0-rc3

**Comment by mtdx** [comment]
Just tested the new prerelease fixes and are working fine.

**Comment by trydis** [comment]
Thanks for the feedback @mtdx. I'll leave this open a few days just in case something's discovered on certain platforms etc.

**Comment by A-VORONKIN** [comment]
When it will be merged as main branch?

**Comment by tringler** [comment]
As soon as we have we enough positive test feedbacks - Feel free to test it and give feedback ;)

**Comment by trydis** [comment]
Relased
