### ISSUE TITLE
Create Account

### ISSUE THREAD

**Issue by Extremeg** [trydis/FIFA-Ultimate-Team-Toolkit#245]
Hi, its possible to you can add to the library, the possibility to can create playstation accounts, xbox accounts and finaly ea accounts?

**Comment by tringler** [comment]
As this cannot be done via the FUT WebApp / Companion App i don't think this should be implemented in this framework. (Beside of I don't know how to do this without buying a FIFA game for the corresponding platform)

**Comment by Extremeg** [comment]
Hi tringler thanks for you answer, but its necessary if you dont want to create accounts

**Comment by Extremeg** [comment]
Whats with player packs? How i can open player packs or see if a player has a contract?

**Comment by tringler** [comment]
Feel free to open a pull request :) - Open player packs is not implemented to my knowledge - You can check the contracts on itemdata which is attached to auctioninfo object.

**Comment by Extremeg** [comment]
The prob is i dont know how :D

**Comment by tringler** [comment]
Here you go: https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/issues/208#issuecomment-165779443

**Comment by Extremeg** [comment]
No i dont know how, i must do it programatically. To access to the player packs.

**Comment by tringler** [comment]
Sorry, but I don't get you - What do you want to do exactly? What is the issue?

**Comment by Extremeg** [comment]
The issue was at first about the accounts. Then i have asked if its possible to access to player packs

**Comment by tringler** [comment]
Yes and I explained to you how to create pull requests for these implementations,

**Comment by Extremeg** [comment]
the second point

**Comment by tringler** [comment]
Ok - I'm basically open to raise a pull request regarding opening packs for the toolkit, but I don't see the feature to create FUT accounts definitely **not ** in the toolkit as long as the WebApp give us that possibility.

**Comment by A-VORONKIN** [comment]
@tringler do you know how to get consumables from club? for now we can only get players from club.

**Comment by tringler** [comment]
Pls don't open the 3rd topic on this issue thread. Pls open a new one.

**Comment by tringler** [comment]
@ExtremeG: Can you pls open a new issue thread regarding "Open Packs" and close this one regarding "Create Accounts", because it should not part of the toolkit, I will take care of the "Open Packs" issue the next weeks.

**Comment by tringler** [comment]
@trydis : Could you pls close that issue? I assume "Create Origin accounts" should not be a part of the toolkit.
