### ISSUE TITLE
Get Consumables from Club

### ISSUE THREAD

**Issue by A-VORONKIN** [trydis/FIFA-Ultimate-Team-Toolkit#247]
We already have implemented getting players from club but how to get consumables? I tried to implement it by myself. It is not hard to get club items (kits, badges, stadiums) or staff from club. But I don`t understand how to get consumables. There is no id for them like for other type of cards.

**Comment by A-VORONKIN** [comment]
Thanks, I will try to implement it.

**Comment by tringler** [comment]
Pls close if your question is answered.
