### ISSUE TITLE
Open Packs

### ISSUE THREAD

**Issue by Extremeg** [trydis/FIFA-Ultimate-Team-Toolkit#249]
Can someone implement it to the lib that we can access the packs pls?
Another Question is if you can gve me an answer on my question which i have send you per mail.

**Comment by tringler** [comment]
I will take care of as soon as the vnext branch is merged to master.

**Comment by tringler** [comment]
The implementation is basically done, but I need to wait until https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/pull/260 is merged to master, because I'm running into conflicts as long as PinRequests not implemented. OpenPacks are also using PinRequests.

**Comment by tringler** [comment]
Implemented in my fork https://github.com/tringler/FIFA-Ultimate-Team-Toolkit/commit/01ed55d6d3a311a54d993781f32454d0dcf32560 - As soon as PinRequests are applied to the toolkit I will add the missing PinRequests in a seperate commit. Then I can create a PR.

**Comment by tringler** [comment]
@Extremeg Pls close this issue, because it's implemented in my pull request. You can test it and give feedback in the PR thread.
