### ISSUE TITLE
Companion App Exceptions

### ISSUE THREAD

**Issue by mtdx** [trydis/FIFA-Ultimate-Team-Toolkit#252]
Just a reminder, now is missing exceptions like CaptchaTriggeredException, InternalServerException, ExpiredSessionException, etc.

**Comment by tringler** [comment]
Do you know why? My changes should not touch exception handling.

**Comment by mtdx** [comment]
well for now I'm handling it, by seeing which code the exception throws, 461 permission denied, 500 server error, etc. while on the web app I can just catch the specific exception.

I'm not saying your changes should do it, but I think will be good to be implemented at some point, I may even try my first pull request on github.

**Comment by tringler** [comment]
Yes, give it a try :+1: 

I guess what to be fixed is adjust this Model to the Model you get via Companion App:

```
namespace UltimateTeam.Toolkit.Models
{
    public class FutError
    {
        public string Reason { get; set; }

        public FutErrorCode Code { get; set; }

        public string Message { get; set; }

        public string Debug { get; set; }

        public string String { get; set; }
    }
}
```

As I remember correctly the Companion App writes the `FUTErrorCode ` in another structure. You need to define that structure in a new class and then pass the appVersion to the Deserializer. Based on which AppVersion is used you deserialize to `FutErrorWebApp` (renamed) or `FutErrorCompanionApp`

```
        protected static async Task<T> Deserialize<T>(HttpResponseMessage message) where T : class
        {
            message.EnsureSuccessStatusCode();
            var messageContent = await message.Content.ReadAsStringAsync();
            T deserializedObject = null;

            try
            {
                deserializedObject = JsonConvert.DeserializeObject<T>(messageContent, JsonSerializerSettings);
            }
            catch (JsonSerializationException serializationException)
            {
                try
                {
                    var futError = JsonConvert.DeserializeObject<FutError>(messageContent, JsonSerializerSettings);
                    MapAndThrowException(serializationException, futError);
                }
                catch (JsonSerializationException)
                {
                    throw serializationException;
                }
            }

            return deserializedObject;
        }
```

This would be my first approach.

**Comment by tringler** [comment]
I would propose you create a PR for the vnext branch.

a) Fork this repo
b) Make the vnext as default branch in your forked repo (Your repo --> branches)
c) Create a branch called CompanionApp-Exceptionhandling from your master branch (which shoudl vnext)
d) Update your branch from upstream (vnext branch)
e) Insert your changes & Commit
f) Create a PR into vnext branch

**Comment by mtdx** [comment]
Just that it needs to dive a little to deep into the toolkit internals and more advanced C# stuff for my taste. 

I've been testing more, so far looks like the initial web app requests are fine, nothing broken.

**Comment by tringler** [comment]
Feel free to ask if you have additional questions.
