### ISSUE TITLE
Unable to Search Players, Consumables, etc

### ISSUE THREAD

**Issue by maksoy2099** [trydis/FIFA-Ultimate-Team-Toolkit#253]
Hi,

I'm trying to search for players, consumables, etc and it keeps crashing with a http 500 internal server error.

**Comment by tringler** [comment]
Pls send the request which throws the error. We need a detailed error description to help you out.

**Comment by bbday** [comment]
Maybe you didn't unlock the market, cause you use a new account.
Try to do same thing on web app if working.

**Comment by tringler** [comment]
@maksoy2099  Pls close if your question is answered.

**Comment by tringler** [comment]
@trydis Pls close this issue, because no feedback since over 2 weeks.
