### ISSUE TITLE
GetItemAsync not working properly 

### ISSUE THREAD

**Issue by stefanoIT** [trydis/FIFA-Ultimate-Team-Toolkit#254]
Hey guys,
just reporting FutClient.GetItemAsync is not working properly on vnext branch

If you call it by using AuctionInfo parameter it doesn't calculate the baseID properly and app returns 4xx error

If you call it by  long resourceId it works but the parameter name is "confusing" (if you pass me the term) because it's not the resourceID you need to pass but the assetID

I do apologies if I can't push the fix by myself but working out few issues with github client it seems. 

Also, I'm a quite old time contributor (fifa14), I haven't been active at all in the past 1.5 year. Sorry for that and absolutely thanks a bunch to everyone who helped to keep up to date everything. 
I'll try to be a bit more helpful from now on

**Comment by tringler** [comment]
Hello,

you're right! All AssetId, ResourceId and DefinitionId stuff needs to rework. It's really confusing! Pls send me your Request which is causing the error.

**Comment by tringler** [comment]
Implemented a better handling of these Ids in https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/pull/261 - It will automatically convert ResourceId to AssetId and vice versa - Just insert a ResourceId OR AssetId and it will work

**Comment by tringler** [comment]
@stefanoIT Pls close the issue and give me feedback in my PR thread as this issue should solved now.

**Comment by tringler** [comment]
@trydis Can you pls close, because no answer a week and in addition to that it should solved with PR https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/pull/261

**Comment by stefanoIT** [comment]
@tringler apologies for not answering before. thanks for your contribution
