### ISSUE TITLE
Unable to Login

### ISSUE THREAD

**Issue by Extremeg** [trydis/FIFA-Ultimate-Team-Toolkit#255]
Hi guys, i have currently an bug but i dont know why does exactly this error comes.

UltimateTeam.Toolkit.Exceptions.FutException: Unable to login ---> UltimateTeam.Toolkit.Exceptions.InternalServerException: Code: InternalServerError ---> Newtonsoft.Json.JsonSerializationException: Could not find member 'debug' on object of type 'UserAccounts'. Path 'debug', line 1, position 9.

**Comment by mtdx** [comment]
This looks like a EA server error, these happens sometimes, high RPM maybe, busy servers.

**Comment by tringler** [comment]
This is also a known behaviour when the webApp is in maintenance mode. If you would using the webApp you will see "Sorry - Our servers are temp. down"

**Comment by A-VORONKIN** [comment]
It would be greate if toolkit will tell error when Unable to login (like maintenance or logged in consle etc), not just this message)

**Comment by tringler** [comment]
@Extremeg Pls close the issue as it's not a bug and your question seems to be answered.
