### ISSUE TITLE
Login WaitingForActivation

### ISSUE THREAD

**Issue by innerspox** [trydis/FIFA-Ultimate-Team-Toolkit#257]
After successful login I always get the "WaitingForActivation" status code when requesting the tradepile. But the account (ps4) is activated, I can use the transfermarket within the real webapp, also when playing on the ps4 console. This error only occures when using the toolkit. I tested last stable version 2.2.0 and also latest rc3.

**Comment by trydis** [comment]
Related to https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/issues/137#issuecomment-156069382?

**Comment by innerspox** [comment]
No, the account already has access to transfer market (played long enough). I used transfermarket several times within the real webapp.

**Comment by tringler** [comment]
Are you pretty sure you are working with the right persona ID? Maybe you have multiple personas like for PS4 and PC and working accidently with your PC account, which you never activated.

**Comment by innerspox** [comment]
Yes I have only 1 account for testing and this account is for PS4. I can't find the problem. I also created a minimal testprogramm and assigned the current package via nuget (3.0.0). Login is successfull, I get the right account data (name, team, coins and so on). But every following request (e.g. tradepile or card search) result in the "WaitingForActivation" status code. But I can use (and did many times) transfermarket via real EA webup and also with PS4 console. I have no idea what goes wrong, but the logical conclusion is, that there is something wrong with the toolkit software (maybe only in some special cases).

**Comment by mtdx** [comment]
New accounts are locked from the transfer market? can you buy/sell cards via the browser? just post here a screenshot with the fiddler requests.

**Comment by tringler** [comment]
Could you post the "WaitingForActivation" response?

**Comment by tringler** [comment]
@innerspox Please close the issue if its solved or you not interested anymore to solve it. We cannot help you without your requests/responses, because we cannot repoduce it.
