### ISSUE TITLE
How to install (use) FIFA-Ultimate-Team-Toolkit

### ISSUE THREAD

**Issue by samoyan** [trydis/FIFA-Ultimate-Team-Toolkit#258]
I installed Visual Studio in order to import "FIFA-Ultimate-Team-Toolkit" package from Nuget.

Can you tell me please how I can compile it or create an .exe file from it?

**Comment by trydis** [comment]
It's already compiled in the NuGet package. Since it's a (portable) class library it can't be used on its own. You'll have to create an app which contains all the logic, references this library and calls the toolkit methods.

**Comment by samoyan** [comment]
Thank you for your response...
