### ISSUE TITLE
HttpRequestException using CompanionApp

### ISSUE THREAD

**Issue by A-VORONKIN** [trydis/FIFA-Ultimate-Team-Toolkit#267]
I had HttpRequestException (Message: Response status code does not indicate success.) very often when I'm using CompanionApp.
https://gyazo.com/78a528afad81c18418dd58d9bea1f175

After first launch I hade 2-3 exceptions during 20 mins but after 4 hours of work I had it everytime. 
I`m using 6 seconds between requests. Maybe its something like temp ban?

**Comment by tringler** [comment]
I'm pretty sure it's a expired Session. Try to send requests only each 5 seconds.

**Comment by A-VORONKIN** [comment]
I`m sending requests each 6 seconds now.

**Comment by tringler** [comment]
Ok - Can you see how many requests and pin requests you made? I'm also aware of that problem, but it seems to be sometimes there and sometimes not. We need to analyze when it happens. I don't have an idea so far.

**Comment by A-VORONKIN** [comment]
2000+ requests. Sometimes I realy had message: Response status code does not indicate success:401 (Unauthorized). So ExpiredsessionException not working for CompanionApp? But it 90% I had another code and it is not an expired session.

**Comment by tringler** [comment]
The whole exceptionhandling is not working in the companion app I guess, because they have other error codes. We need to collect all companion app error codes and map them.

Yes, but I think you got these codes, because you are unauthorized, because your session is expired. They kick you out from your session for any reasons.

**Comment by A-VORONKIN** [comment]
I think you are right. Maybe when I just start bot I had some exceptions like PermissionDenied and thats why bot was still working for some time. But afte that I get ExpiredSession and then I'm getting so many exceptions.

**Comment by mtdx** [comment]
I can confirm that 401 code is "session expired" but the codes in the screenshot are very strange, try to  login again to see what's happening.

**Comment by A-VORONKIN** [comment]
After relogin everything is working and no exceptions yet.

**Comment by tringler** [comment]
Yes, as I said I think all these errors caused because your session expired and the requests are dropped with your invalid session id.

**Comment by A-VORONKIN** [comment]
So why it didn`t throw ExpiredSessinException if it has same code 401 as WebApp?

**Comment by tringler** [comment]
Ask EA :-P

Just two different implementations of their internal API I assume.

**Comment by A-VORONKIN** [comment]
Its unreal to use companion app now. I have this exceptions with strange codes after 20-30 mins of working.

**Comment by tringler** [comment]
Do you use pin requests?

**Comment by tringler** [comment]
We should analyse the original CompanionApp traffic - Maybe we miss a keep-alive or stuff like that.

**Comment by A-VORONKIN** [comment]
@tringler yes

**Comment by tringler** [comment]
It looks like they do a new authentication after a few minutes - I just opened the app on my Android image and did nothing:

![unbenannt](https://cloud.githubusercontent.com/assets/4985268/14944257/f73df158-0fed-11e6-87e1-34fdb00cb6c8.PNG)

**Comment by tringler** [comment]
@A-VORONKIN Can you verify this only happens while connected to CompanionApp or do you get sometimes also some ExpiredSessions from the WebApp?

**Comment by A-VORONKIN** [comment]
@tringler only when I`m using CompanionApp

**Comment by tringler** [comment]
@A-VORONKIN Give it a try - https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/pull/275

**Comment by A-VORONKIN** [comment]
@tringler do I need manualy call client.GetSettingsAsync()?

**Comment by tringler** [comment]
yes
