### ISSUE TITLE
cannot login to CompanionApp

### ISSUE THREAD

**Issue by a7medit** [trydis/FIFA-Ultimate-Team-Toolkit#268]
can not login to Fut using CompanionApp always get this exception. 
Could not find member 'expiresOn' on object of type 'Auth'. Path 'expiresOn', line 1, position 66.

**Comment by tringler** [comment]
Pls try https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/pull/270/commits/1910db0e6b44529f3c02ada3e1265e24f7c8e5eb
