### ISSUE TITLE
Mobile Client Version

### ISSUE THREAD

**Issue by mtdx** [trydis/FIFA-Ultimate-Team-Toolkit#269]
@tringler Can you please create a pull request to change client version to 20? 

Also what's with the pull requests pilling up? I see 2 failed the checks.

**Comment by tringler** [comment]
Pls explain more detailed - I think you need to ask @trydis about the failed checks.

**Comment by mtdx** [comment]
Well please try to login via companion app, you will see is not working, you need to change ""clientVersion"":18 to ""clientVersion"":20 lines 123 and 164 in LoginMobileRequest.cs

**Comment by trydis** [comment]
@tringler: I started using AppVeyor in this project, so it will build the project + run any tests it detects for every pull request and commits pushed to this repo. If either fails it reports the build as failed.
