### ISSUE TITLE
Invalid Cookies cause strange error

### ISSUE THREAD

**Issue by crephix** [trydis/FIFA-Ultimate-Team-Toolkit#276]
@trydis When the cookie is not valid anymore (e.g. password has changed or cookie is expired) there is just a strange error/exception and no real error message, can you fix that please?

This is what I get: http://img03.imgland.net/EHRfamm.png and that isn't really useful at all.

**Comment by A-VORONKIN** [comment]
Sometimes I can`t login with old cookies but no exceptions just "Unable to login". Then I need to delete cookies and create new and everything works fine.

**Comment by asdfgasdfsafgsdfa** [comment]
same thing here.
can we get a correct exception for that please? :(

**Comment by trydis** [comment]
You're getting a `FutException` and the message even says that it's unable to log in. Catch that exception and do what @A-VORONKIN says.
