### ISSUE TITLE
Search for Player Returns 0

### ISSUE THREAD

**Issue by drawalex** [trydis/FIFA-Ultimate-Team-Toolkit#282]
`var searchParameters = new PlayerSearchParameters
            {
                //ResourceId = 188567
                Page = 1,
                Level = Level.Silver,
                MaxBuy = 10000,
                MinBid = 200
            };

            var searchResponse = await futClient.SearchAsync(searchParameters);
            Console.WriteLine(string.Format("Found {0} auctions", searchResponse.AuctionInfo.Count));`

When i search by the ResourceId it returns results but when i search by using the Parameters. Am i using the correct search Parameters?

**Comment by edmolko** [comment]
I'm having the same issue as well, I'm not getting any results even with no filters applied...
