### ISSUE TITLE
Internal server error strategy 

### ISSUE THREAD

**Issue by ulrickpsp** [trydis/FIFA-Ultimate-Team-Toolkit#286]
Hi mates. I came across Internal server error after 4 days of botting. I'm wondering which strategy do you follow when you suffer from this error. Mobile app seems to work fine. Would it be enough to switch to mobile login and then run the bot again?

**Comment by mfsdcool** [comment]
I can't login mobile app using toolkit since 16. So I cannot switch.

It happens to me when bid too much in short period of time. And I will wait for few hours or somewhat I play the games on PS4 it will resumed normal.

**Comment by ulrickpsp** [comment]
Ok, thanks. I will try to adapt mobile login for FUT17. Any chance for using fiddler with Android?

**Comment by mfsdcool** [comment]
![android app1](https://cloud.githubusercontent.com/assets/19850239/19020207/a11041b8-88d4-11e6-918b-1ad519054e5f.png)

Yes I tried it just now. Upper part is Android (success login) and lower part is Toolkit which is failed

I checked and the following are difference which I am not sure which one cause the login failure:
- Machine Key ID
- Cookies using
- Android will issue a GET request (line 37) /p/web2/login?execution=xxxx**&eventId=end**

while Toolkit will ask for  **/connect/token**  (Line 119) and it will return failure.

My package downloaded around June 2016. I don't know if any stuff I missed as I didn't patch or debug it as I only use WebApp since FIFA16.

Thanks in advance

**Comment by ulrickpsp** [comment]
Thanks. I'll check it later.

**Comment by artielange** [comment]
Which requests return internal server error? All?

I remember this happening in the past actually

**Comment by ulrickpsp** [comment]
Only the ones related with transfer market.

**Comment by mfsdcool** [comment]
For me it will have internal error when place bid after I have bid war with others

**Comment by ulrickpsp** [comment]
Im now working on it. I'm stuck trying to get fid. Any idea about getting this in C#? 

Response does not show that header (or I can't find it)

![captura](https://cloud.githubusercontent.com/assets/8997800/19032751/e6bd37fc-895b-11e6-881f-1e0990aebf83.PNG)

**Comment by ulrickpsp** [comment]
Original cookies look like this

![image](https://cloud.githubusercontent.com/assets/8997800/19040635/37cc8c14-8985-11e6-95f2-389aafdb98d9.png)
![image](https://cloud.githubusercontent.com/assets/8997800/19040649/487b32cc-8985-11e6-9fc8-87cd509f79bd.png)



And mine look like this:

![image](https://cloud.githubusercontent.com/assets/8997800/19040604/157f5e5c-8985-11e6-8553-53566950cb9f.png)
![image](https://cloud.githubusercontent.com/assets/8997800/19040622/2c18948a-8985-11e6-8500-3efb14c241d8.png)


Any idea?

**Comment by mfsdcool** [comment]
I have the same cookies pattern with u for mobile app and toolkit
And same results with u too (toolkit failed)

**Comment by ulrickpsp** [comment]
I've been able to reach the two factor code screen. I receive the code in my email but i'm having trouble posting it to EA. 

![image](https://cloud.githubusercontent.com/assets/8997800/19070633/879acbb4-8a2c-11e6-8eb4-a9da98a64f0e.png)

**Comment by mfsdcool** [comment]
Anyone success connect using toolkit connect MobileApp can share your successful story?

Thanks

**Comment by ulrickpsp** [comment]
Same state than the other day..no success.

**Comment by artielange** [comment]
May i ask why mobile login is important? In previous years is was important because trading had been turned off on webapp...

**Comment by ulrickpsp** [comment]
It's important when you get internal server error and can't use AB for some hours..

**Comment by proeben** [comment]
It's important due to some other reason but the competitive ppl won't tell u

Von meinem iPhone gesendet

**Comment by artielange** [comment]
Makes sense lol

**Comment by ulrickpsp** [comment]
Would be nice to know that mysterious reason :)

**Comment by artielange** [comment]
Proeben is competitive lol

**Comment by RicoBoone** [comment]
I think it was to do with the max requests per day. I tested this today, my account couldn't bid anymore because it reached the max requests mark but I still was able to bid on items using my mobile app manually . Haven't got the mobile login working myself too that's why I kinda want to figure it out.

**Comment by ulrickpsp** [comment]
Same here..

**Comment by artielange** [comment]
It could have only been that really.. But honestly.. It will only be a matter of time before ea pick up on that and limit the mobile app as well. 

Ea have stepped up their game, they came a long way since 2014 lol

**Comment by ulrickpsp** [comment]
No  new progress from my side. Any help? Still getting 200 instead of 302

**Comment by artielange** [comment]
I haven't got the error yet on my end... I've had sessions that lasted 12-24 hours with about 4000 requests

**Comment by ulrickpsp** [comment]
Of course..the idea is to be able to make more than those 4000 requests.

2016-10-17 17:27 GMT+02:00 artielange <notifications@github.com>:

**Comment by artielange** [comment]
Sure, and then EA cracks down like they did two years ago and then the fun stops for everyone. I'm not willing to contribute to that sorry.

**Comment by ulrickpsp** [comment]
OK, it's up to you. But be sure that was not the cause for which EA cracked
down. Market went uncontrollable, which cannot happen anymore with price
ranges.

**Comment by Ricbun16** [comment]
Is the companion app working with the new changes? Can't test it myself right now but I'm curious

**Comment by A-VORONKIN** [comment]
@Ricbun16 Companion app is not working. You need to change CleintVersion to 21, but it still not working.

**Comment by ulrickpsp** [comment]
Not for me

**Comment by Bltfast** [comment]
Hi, I have the same problem here but a little more strange. I have two accounts, ps4 and xboxone. With the same application I did the former does the login with no problems, the latter receives the 500 internal server error. By the way, the xboxone account has worked for some days before getting the error! Is there something that I can try to figure out the issue?
