### ISSUE TITLE
How to support Proxy

### ISSUE THREAD

**Issue by Extremeg** [trydis/FIFA-Ultimate-Team-Toolkit#288]
Hi guys, 
I have a question how can i add successfully a proxy server to the lib? It would be great if someone can help me with that.
Good Regards, 
Extremeg

**Comment by trydis** [comment]
https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/issues/150#issuecomment-145885173

**Comment by Extremeg** [comment]
Thanks at first for the answer, but this solution i know already. Im looking for where i can change/add in the toolkit something in the class in which the request are handled.

**Comment by trydis** [comment]
https://msdn.microsoft.com/en-us/library/system.net.http.httpclienthandler.proxy(v=vs.118).aspx

**Comment by A-VORONKIN** [comment]
You need to change httpClient in FutRequestFactories or HttpClientWrapper. But I tried it but login to web app is not working with proxy. I don't know why. Other request like getting ip from http://bot.whatismyipaddress.com/ is working fine with proxy.
