### ISSUE TITLE
Proxy capable

### ISSUE THREAD

**Issue by A-VORONKIN** [trydis/FIFA-Ultimate-Team-Toolkit#301]
How to make it proxy capable? I tried to changing HttpClientHandler and adding proxy to app.config (https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/issues/288) but in both cases Toolkit is not working with proxy. Other request like getting IP from other site (client.DownloadString("http://bot.whatismyipaddress.com/") is working fine with proxy (after changing app.config because it will automaticly use proxy for all application). So proxy is working but Toolkit don't want to work with it (even can't login).

**Comment by tringler** [comment]
This is all you need to do: https://msdn.microsoft.com/en-us/library/kd3cf2ex(v=vs.110).aspx

**Comment by A-VORONKIN** [comment]
@tringler, I tried it buy still not working.

```
<system.net>
    <defaultProxy useDefaultCredentials="true" enabled="true">
      <proxy
        usesystemdefault="True"
        proxyaddress="http://[proxy ip]:[proxy port]"
        bypassonlocal="True"
    />
    </defaultProxy>
  </system.net>
```

Just can't login after that.

**Comment by tringler** [comment]
Just use:
```
<system.net>
    <defaultProxy useDefaultCredentials="true" enabled="true">
      <proxy
        usesystemdefault="True"
    />
    </defaultProxy>
  </system.net>
```

Then it will use the systemproxy you setup via i.e. Internet Explorer as system-wide proxy.

**Comment by A-VORONKIN** [comment]
I want to add different proxies when you initialize new FutClient (like Cookie Container). I tried to add this code to HttpClientWrapper.cs or FutRequestFactories.cs but it not works. Just can't log in with it.

```
public HttpClientWrapper()
        {
            Proxy webProxy_Interface = new Proxy(new Uri("[https//proxy ip]:[proxy port"]));
            webProxy_Interface.Credentials = CredentialCache.DefaultNetworkCredentials;

            MessageHandler = new HttpClientHandler { AutomaticDecompression = DecompressionMethods.GZip, Proxy = webProxy_Interface, UseProxy = true };
            _httpClient = new HttpClient(MessageHandler);
            SetExpectContinueHeaderToFalse();
        }
```

**Comment by Extremeg** [comment]
It would be nice if someone can say how that can be fixed.

**Comment by A-VORONKIN** [comment]
I had System.Net.Http.HttpRequestException (An error occurred while sending the request.) when I'm trying to login with proxy.

**Comment by tringler** [comment]
No action on this issue, so I will close that issue now.
