### ISSUE TITLE
Login Companion App Fifa 17 not working?

### ISSUE THREAD

**Issue by JoaoFelipePego** [trydis/FIFA-Ultimate-Team-Toolkit#303]
I'm trying to login the Companion App version of fifa 17 ut and not working. When I try to login the WebApp version of FIFA ut 17 works normally! 
Does anyone know any way to login via companion app work?

**Comment by thijsvanbloemendaal** [comment]
I guess you'll need to use the loginmobilerequest in this case?

**Comment by Majed93** [comment]
Are you getting any errors?

**Comment by JoaoFelipePego** [comment]
@Majed93 

I'm using version 3.0.0, login the web app is running fine.

When I try to log the Companion App is the following error:

**"Response status code does not Indicate success: 400 (Bad Request)."**


Debugging realized the error occurs in the Post method "_GetAuthTokenAsync_" within the **_LoginMobileRequest.cs_**  class

I believe that the login form used in **_LoginMobileRequest.cs_** is outdated.

**Comment by JoaoFelipePego** [comment]
@trydis 

Any idea of ​​the problem?

**Comment by trydis** [comment]
Nope, never tried it. Just compare the requests using Fiddler and see where they differ.
