### ISSUE TITLE
Login Unknown Error 465 [PS4]

### ISSUE THREAD

**Issue by Romboide82** [trydis/FIFA-Ultimate-Team-Toolkit#304]
Hi, i get this error when try to login with the last nuget version (4.0.0). 

Any idea?

**Comment by JoaoFelipePego** [comment]
@Romboide82  
You have the error more detailed?
What message stacktrace?

**Comment by Romboide82** [comment]
I think it's related to Newtonsoft.Json.

Message = "Could not find member 'debug' on object of type 'UserAccounts'. Path 'debug', line 1, position 9."

StackTrace = " at UltimateTeam.Toolkit.Requests.LoginRequest.<PerformRequestAsync>d__9.MoveNext()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at UltimateTeam.Toolkit.FutClient.<LoginAsync>d__5.MoveNext()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n ......

And

"   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)\r\n   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)\r\n   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)\r\n   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)\r\n   at UltimateTeam.Toolkit.Requests.FutRequestBase.<DeserializeAsync>d__42`1.MoveNext()"

**Comment by JoaoFelipePego** [comment]
@Romboide82 @trydis 

Update the **UserAccounts.cs** class to:

namespace UltimateTeam.Toolkit.Models 
{
    public class UserAccounts
    {
        public UserAccountInfo UserAccountInfo { get; set; }
        _**public string debug { get; set; }
        public string @string { get; set; }
        public string code { get; set; }
        public string reason { get; set; }**_
    }
}

**Comment by trydis** [comment]
Those properties will only be in the response when there's an error. https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/blob/master/UltimateTeam.Toolkit/Models/FutError.cs already contains those, so a better option would be to figure out what code 465 is and throw a FutException with a proper description to the library user.

**Comment by trydis** [comment]
Looks like it might be related to authenticator apps?

https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/pull/251/commits/83c345c9e2bf46f88c95cd9e7488c7ff7b1e4ffe

**Comment by Romboide82** [comment]
Mmmh i don't know, i'm not trying to login on the companion. Any idea?

**Comment by Romboide82** [comment]
@JoaoFelipePego tried your changes but got a "reference to not instantiated object" error.

**Comment by trydis** [comment]
Like i mentioned above, EA returns an error. Adding those properties won't make the underlying problem go away.

You have successfully logged in, using the same account, on a console and created a team, i assume?

**Comment by Romboide82** [comment]
Yes, web app works fine too.

**Comment by Romboide82** [comment]
Another detail i forgot to mention: the error appears after i send back the verification code.

**Comment by Romboide82** [comment]
SOLVED

Found the problem -.-

I saved PS4 as platform. But the account was on XboxOne. 

Sorry for the waste of time :l and thanks a lot for help!
