### ISSUE TITLE
PlayerSearch not working

### ISSUE THREAD

**Issue by losersFocus** [trydis/FIFA-Ultimate-Team-Toolkit#307]
This issue still exists:
https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/issues/226

I will do a pull request soon. 
Help is appreciated.
Can someone else confirm that this issue still exists?

**Comment by trydis** [comment]
I guess you're not searching for a specific player? If so, it's related to this: https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/commit/0a334235ba6d1bf0a0f4f55353d7f000dd9e6633. The definitionId/maskedDefId shouldn't always be added to the URL.

**Comment by trydis** [comment]
https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/pull/309 should fix this once it's merged.
