### ISSUE TITLE
Error code 500 when login to Xbox account.

### ISSUE THREAD

**Issue by A-VORONKIN** [trydis/FIFA-Ultimate-Team-Toolkit#308]
I had error code 500 when trying to login to any Xbox account. Login to PS4 accounts is working fine.

VisualStudio shows problem with 
`var userAccounts = await GetUserAccountsAsync(_loginDetails.Platform);`
in LoginRequest.cs

Any ideas how to fix it?

**Comment by CoverJ** [comment]
Looking into fixing but no luck yet, can at least confirm that it isn't only on your end!

**Comment by CoverJ** [comment]
I think more specifically there is a problem with
`var accountInfoResponseMessage = await HttpClient.GetAsync(string.Format(Resources.AccountInfo, DateTime.Now.ToUnixTime()));`

**Comment by Taggardos** [comment]
Can confirm the Problem, but unfortunately too stupid to fix it :-D

[http://imgur.com/a/KpLIt](url) 

I tried to sniff the Login with Fiddler, but the only difference I am seeing is at this Log entry:
`200	HTTPS	www.easports.com	/iframe/fut17/p/ut/game/fifa17/user/accountinfo?filterConsoleLogin=true&sku=FUT17WEB&returningUserGameYear=2016&_=1481882419387	49	max-age=0, no-cache, no-store; Expires: Fri, 16 Dec 2016 10:00:20 GMT	application/json	iexplore:19240	[#169]`

added to the Baseurl the "filterConsoleLogin" and the "returningUserGameYear", but that didn't fixed it...

**Comment by CoverJ** [comment]
also tried that @Taggardos with the same result!

**Comment by Majed93** [comment]
I'm getting this error too!

**Comment by CoverJ** [comment]
If anyone has any ideas I'm willing to do the leg work!

**Comment by Majed93** [comment]
the x-ut-route url has changed by the looks of it

**Comment by CesarAdmin** [comment]
You need to change the resources file and from s3 to external.s3
Resources.cs 
`  public const string FutHomeXbox = "https://utas.external.s3.fut.ea.com/ut/game/fifa17/";;`
LoginRequest.cs 

`  HttpClient.RemoveRequestHeader(NonStandardHttpHeaders.Route);
            var route = $"https://utas.{(platform == Platform.Xbox360 || platform == Platform.XboxOne ? "external.s3" : "s2")}.fut.ea.com:443";`

**Comment by A-VORONKIN** [comment]
Thanks! It works!

**Comment by trydis** [comment]
A pull request would be appreciated :)
