### ISSUE TITLE
How to use GetConsumablesAsync?

### ISSUE THREAD

**Issue by A-VORONKIN** [trydis/FIFA-Ultimate-Team-Toolkit#312]
I want to move some consumables from my club to transfer list. GetConsumablesAsync returns something strange, I fail to get an ItemData from it. How to use it?

**Comment by ZardoZ70** [comment]
I wrote a method `GetConsumableDetails` with which you can access details for consumables in your club, including their resource ids. See 76bf2ef3fc8579221d061f53e7d1a2fdcdbcf481. It's available in the [vnext](https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/tree/vnext) branch.
Hope that helps.

**Comment by trydis** [comment]
Also on NuGet: https://www.nuget.org/packages/UltimateTeam.Toolkit/5.0.0-rc0002

**Comment by A-VORONKIN** [comment]
@ZardoZ70 how to move consumables for club to tradepile? you need itemdata to do it.
