### ISSUE TITLE
EA Banishing accounts that log on by this Toolkit!

### ISSUE THREAD

**Issue by JoaoFelipePego** [trydis/FIFA-Ultimate-Team-Toolkit#314]
A month ago I had 4 accounts banned for no reason, after that I created a new account and played a few games until WebApp was unlocked!

After that I performed exactly 4 logons using this Toolkit and my account was subsequently banned. I believe that the login method that the toolkit is doing is obsolete and EA is banning everyone who is using this method!

**Comment by trydis** [comment]
Closing this since a similar issue already exists.
