### ISSUE TITLE
Http Error 500 (internal server error) on Login

### ISSUE THREAD

**Issue by A-VORONKIN** [trydis/FIFA-Ultimate-Team-Toolkit#315]
Can't login today. Had this error on any platform.

**Comment by lkuklis** [comment]
Have these same issue. It is 500 when getting shards, any clue if something changed ?

**Comment by brkoz** [comment]
I have the same problem. Did you solve it? I am able to login via other toolkits.

**Comment by csimoes1** [comment]
It seems another URL has changed.  If you go into LoginRequest.cs and change the following line:
HttpClient.AddRequestHeader(NonStandardHttpHeaders.Route, "https://utas.fut.ea.com");
to
HttpClient.AddRequestHeader(NonStandardHttpHeaders.Route, "https://utas.external.fut.ea.com");

This should resolve your issue.  Then to pay this forward please submit a pull request to the owner @trydis of this project with patched file.

**Comment by lkuklis** [comment]
No, but as I made quick look into code and Fiddler I assume that there are changes in request headers.

**Comment by lkuklis** [comment]
Unfortunately changing only url does not help.
