### ISSUE TITLE
Unable to login using the toolkit

### ISSUE THREAD

**Issue by aftershock9** [trydis/FIFA-Ultimate-Team-Toolkit#316]
Since the past few days, I haven't been able to login with the toolkit with my bot. I keep on receiving the status code of 500. 

1. Has something change with the fifa webapp? 
2. Is anyone else experiencing the same issue?

**Comment by lkuklis** [comment]
Yeah, they've made some changes to WebApp. You can look at [this](https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/issues/315) but no one managed to fix this yet.

**Comment by lkuklis** [comment]
It is strange... Request for shards looks ok. It is deserialized and return status is 200.But exception is thrown on  message.EnsureSuccessStatusCode() execution.
`at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at UltimateTeam.Toolkit.Requests.FutRequestBase.<DeserializeAsync>d__42`1.MoveNext() `

**Comment by lkuklis** [comment]
Finally managed to fix that.
To make toolkit work two lines need change
`165:  var route = $"https://utas.external.{(platform == Platform.Xbox360 || platform == Platform.XboxOne ? "s3" : "s2")}.fut.ea.com:443";`

and 
`176: HttpClient.AddRequestHeader(NonStandardHttpHeaders.Route, "https://utas.external.fut.ea.com");
            `

**Comment by artielange** [comment]
FutHome changed too for PS, host is https://utas.external.s2.fut.ea.com/ut/game/fifa17/

Seems ok for now, Can't confirm for xbox

**Comment by lkuklis** [comment]
@artielange are you able to make other requests or you also get an error ?

**Comment by artielange** [comment]
Working fine here

**Comment by ZardoZ70** [comment]
Working fine here, too. Tested for PS4 and WebApp login.

**Comment by JoaoFelipePego** [comment]
Some of you had your account banned after consecutive logins through the Toolkit?

**Comment by aftershock9** [comment]
Will someone be able to pay it forward with a pull request?

Thank you kindly

**Comment by trydis** [comment]
@artielange submitted https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/pull/317.

**Comment by trydis** [comment]
Merged the PR and pushed a new NuGet package.

**Comment by aftershock9** [comment]
Thanks, this issue can now be closed.
