### ISSUE TITLE
Login failure

### ISSUE THREAD

**Issue by aftershock9** [trydis/FIFA-Ultimate-Team-Toolkit#318]
As of today, I am receiving issues with the toolkit to login. I am receiving an error:

"Login Failed: Could not find member on object of type 'Persona'"

Is anyone else experiencing the same issue?

**Comment by Majed93** [comment]
Same here, think they've changed the login again.

**Comment by Majed93** [comment]
I've added the field 'trialFree' in Persona and seems to work.

**Comment by aftershock9** [comment]
@Majed93 Would you please able to pay it forward with a PR? Thanks :)

**Comment by mh1980** [comment]
Do you mean a property of which type in Persona? Can you provide an example plz.

**Comment by Majed93** [comment]
Sorry yes property.

` public string trialFree`

Not done much testing, it would be nice if someone else can also confirm this works please.

@aftershock9 Not sure i can do a PR unfortunately.

**Comment by mh1980** [comment]
thnx, was just starting debugging. Will test it and confirm.

**Comment by mh1980** [comment]
Seems to work! Thnx :)

**Comment by trydis** [comment]
Included in: https://www.nuget.org/packages/UltimateTeam.Toolkit/5.0.0-rc0001
