### ISSUE TITLE
Could not find member 'resourceGameYear' 

### ISSUE THREAD

**Issue by Bltfast** [trydis/FIFA-Ultimate-Team-Toolkit#321]
I receive this new error during deserializing of a consumable. This should be put within the ItemData class such this:

public int resourceGameYear {get; set;}

**Comment by Lululuz** [comment]
FYI, they also changed the way the resource id's are handled. You no longer need to add 1879048192 and can instead use the raw number.

**Comment by aftershock9** [comment]
I have just seen this issue. Has anyone managed to resolve it?

**Comment by Bltfast** [comment]
Just write the code line in the first message into the ItemData.cs class.

**Comment by aftershock9** [comment]
@Bltfast I inserted that code line but unfortunately I am unable to purchase any players.

What others changes do I need to make?
