### ISSUE TITLE
Get list Portuguese players

### ISSUE THREAD

**Issue by SeTi2k** [trydis/FIFA-Ultimate-Team-Toolkit#323]
Hi all,

This is more of a question then an issue, but I can't seem to figure out how it works.
If I search a player by ResourceId that works, but how on earth can I for example get a list of all Portuguese players , or all Spain players, etc. that are currently listed on the market ?

Thank you so much in advance!
Best regards,
Sam

**Comment by trydis** [comment]
There's a bug at the moment, that uses the ResourceId no matter what. 

This PR will fix it, once it's merged: https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/pull/309. Quite busy at the moment, but i'll see what i can do. I you're in a hurry, you can grab this piece of code: https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/pull/309/commits/d96d7412f7136643531dcc9229f6ee29f98c17a3

**Comment by SeTi2k** [comment]
Hi Trydis,

Thank you for the quick reply.
I already tried that piece of code but I thought it was from an older version, since it gives me the following errors when compiling:

Error	CS0534	'PlayerSearchParameters' does not implement inherited abstract member 'SearchParameters.BuildUriString(ref string)'
Error	CS0115	'PlayerSearchParameters.BuildUriString(ref string)': no suitable method found to override

Thank you already.
Best regards,
Sam

**Comment by trydis** [comment]
```
if (ResourceId != 0)
{
    if (ResourceId <= 16777216)
        uriString += "&maskedDefId=" + ResourceId.CalculateBaseId();
    else
        uriString += "&definitionId=" + ResourceId;
}
```

**Comment by trydis** [comment]
Nuget prerelease package, which includes the fix: https://www.nuget.org/packages/UltimateTeam.Toolkit/5.0.0-rc0001
