### ISSUE TITLE
Unable to login to WebApp - Could not find member 'trialFree' on object of type 'Persona'.

### ISSUE THREAD

**Issue by swingo256** [trydis/FIFA-Ultimate-Team-Toolkit#327]
Was able to login fine yesterday, but today I get the below error message. Anyone know the fix? Thanks!

Could not find member 'trialFree' on object of type 'Persona'. Path 'userAccountInfo.personas[0].trialFree', line 1, position 1056.

**Comment by trydis** [comment]
It has been added in the latest prerelease package: https://www.nuget.org/packages/UltimateTeam.Toolkit/5.0.0-rc0001

**Comment by tringler** [comment]
Issue will be closed, because it's fixed in https://www.nuget.org/packages/UltimateTeam.Toolkit/5.0.0-rc0001
