### ISSUE TITLE
Using Toolkit to get TOTW Players

### ISSUE THREAD

**Issue by danieljbingham** [trydis/FIFA-Ultimate-Team-Toolkit#328]
Hi,

I was hoping to use the toolkit to find out the totw players in advance. This guy has got the totw players very early [shown here.](https://twitter.com/fifarenderz/status/831780749112123392) I think he may be using something on here to do it. I thought it was on the api, but I couldn't find anything.

Hopefully someone can help, sorry if I've posted this in the wrong place.

**Comment by CoverJ** [comment]
I am unsure how he is doing it but I thought I would let you know (and maybe @trydis can back me up) that I don't think this toolkit is aimed at that type of function. This is only meant to be a representation of the web app/phone app so that you can automate their functions, not "hack" fifa.

**Comment by trydis** [comment]
> This is only meant to be an API to mimic the web app/phone app so that you can automate their functions, not "hack" fifa.

Spot on @CoverJ 😄

**Comment by tringler** [comment]
@danieljbingham - Take a look at https://github.com/trydis/FIFA-Ultimate-Team-Toolkit#get-definitions - With right `definitionId `you can search the TOTW player by:

```
  var searchParameters = new PlayerSearchParameters
        {
            ResourceId = _definitionId_
        };
        var searchResponse = await futClient.SearchAsync(searchParameters);
````

**Comment by tringler** [comment]
No action on this issue since months, so I will close that issue now.
