### ISSUE TITLE
Login issue with ver 5.0 rc2

### ISSUE THREAD

**Issue by Bltfast** [trydis/FIFA-Ultimate-Team-Toolkit#331]
Hi, I have a new account and and old one. The latter logins using toolkit rc2 without problems, the former receives this error:

Could not find member 'debug' on object of type 'UserAccounts'. Path 'debug', line 1, position 9.

Changing the login to the companion app I receive this other error:

Could not find member 'access_token' on object of type 'MobileToken'. Path 'access_token', line 2, position 18.

What I have done wrong? Why the older account has no problem to login? :O

Thanks

**Comment by trydis** [comment]
I assume you're able to log in using the new account in the FUT web app? https://www.easports.com/fifa/ultimate-team/web-app

**Comment by Bltfast** [comment]
Sure... I have unlock transfer market on that account and I can login with the web app.

**Comment by Bltfast** [comment]
This is the code I use:

```
            var loginDetails = new LoginDetails(user, password, sAnswer, platform, UltimateTeam.Toolkit.Constants.AppVersion.WebApp);

            ITwoFactorCodeProvider provider = new ImapTwoFactorCodeProvider();
            try
            {                
                await _client.LoginAsync(loginDetails, provider); // Here the exception!!!
                var cookiecontainer = _client.RequestFactories.CookieContainer;
```

No code into the ImapTwoFactorCodeProvider constructor... I'm wondering why the other account works well :(

**Comment by marlonespindola** [comment]
I am having the same error here when trying to conect at the webapp

Could not find member 'debug' on object of type 'UserAccounts'. Path 'debug', line 1, position 9.

And yes... I can login at the webapp. I have access.

Dont know whats happening...
Can anyone help me?

**Comment by marlonespindola** [comment]
its returning me StatusCode: 200
butt for what a read here, it always return this when something is wrong

**Comment by marlonespindola** [comment]
Could this have anything to do with anti virus?

**Comment by pashaparenyuk** [comment]
Login Failed: Could not find member 'access_token' on object of type 'MobileToken'. Path 'access_token', line 2, position 18.


when try login with companion app
