### ISSUE TITLE
How can I see the requests and responses of Companion App?

### ISSUE THREAD

**Issue by israeliMaster** [trydis/FIFA-Ultimate-Team-Toolkit#332]
I can see the request and the response of the nomal webapp very  easly  using fiddler and able the HTTPS.

But how can I see the request and response of Companion App ?
do you have any idea how can I do it?

**Comment by trydis** [comment]
I haven't tried it, but my guess is you need to configure your phone to use Fiddler as a proxy.

Android: http://docs.telerik.com/fiddler/Configure-Fiddler/Tasks/ConfigureForAndroid
iOS: http://docs.telerik.com/fiddler/Configure-Fiddler/Tasks/ConfigureForiOS

**Comment by by1338** [comment]
You can easily use an android emulator on your PC like Nox and use fiddler
