### ISSUE TITLE
LoginMobileRequest missing implementation?

### ISSUE THREAD

**Issue by Bltfast** [trydis/FIFA-Ultimate-Team-Toolkit#334]
@tringler @trydis 
After the mobile login is accomplished correctly, my app writes the cookie container to a file in order to avoid the full login process the next time. This works perfectly for the LoginRequest, not for the mobile version. So, I started using Fiddler to inspect what it doing wrong and I saw that when the companion app uses a cached account, it appends two new params to the Home URL:

redirect_uri=nucleus:rest&prompt=none

The next call is directly to retrieve the nucleusId, no get token or other get/post request. What I see from the header is the Authentication Bearer code but I don't have understand how it has been generated! There is no GET between the two requests as I said. Maybe the app uses the "strange" JSON that contains a code in the first call to generate it?

By the way, is this part missing from the LoginMobileRequest or I am doing something wrong?

Thanks guys

**Comment by tringler** [comment]
@Bltfast I stopped to worked on that repo completely due to EA banned my account.

**Comment by Bltfast** [comment]
@tringler that's sad to read :( My accounts had been banned too but I don't give up :)

**Comment by trydis** [comment]
i haven't played fifa or fut in ages...

**Comment by Bltfast** [comment]
so no clue about how solving this?

**Comment by trydis** [comment]
No, not without inspecting the traffic. Not something i want to spend time on tbh.

**Comment by tringler** [comment]
I will close that issue, because it's a duplicate of https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/issues/343
