### ISSUE TITLE
problems using tool

### ISSUE THREAD

**Issue by marlonespindola** [trydis/FIFA-Ultimate-Team-Toolkit#336]
hello guys forgive me my poor english
i am a noob to c#, and i'm trying to use this tool on android, using xamarim

i was using this code provided by @tringler in #272 .

but on ReadCookie it gives me "Could not find file \"/FUT.cookie.WebApp\"
how do i proceed ?

here is the code:

`using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Runtime.Serialization.Formatters.Binary;
using System.Text;
using System.Threading.Tasks;
using UltimateTeam.Toolkit;
using UltimateTeam.Toolkit.Constants;
using UltimateTeam.Toolkit.Exceptions;
using UltimateTeam.Toolkit.Models;
using UltimateTeam.Toolkit.Parameters;
using UltimateTeam.Toolkit.Services;

namespace TestFrontEnd
{
    class Program
    {
        static void Main(string[] args)
        {
            ServicePointManager.ServerCertificateValidationCallback = delegate { return true; };

            DoWebLogin().Wait();
            Console.WriteLine("Press any key to proceed to App Login");
            Console.ReadLine();
            DoAppLogin().Wait();
            Console.WriteLine("Press any key to proceed to Exit FUT Toolkit Tester");
            Console.ReadLine();
        }

        static async Task DoWebLogin()
        {
            var cookieJar = new CookieContainer();
            cookieJar = ReadCookie(@"FUT.cookie." + AppVersion.WebApp);
            FutClient futClient = new FutClient(cookieJar);
            var loginDetails = new LoginDetails("xxx@xxx.xy", "xyz", "abcd", Platform.Pc, AppVersion.WebApp);
            Auth AuthHelper = new Auth();
            var loginResponse = await futClient.LoginAsync(loginDetails, AuthHelper);

            await DoTests(futClient);
        }

        static async Task DoAppLogin()
        {
            var cookieJar = new CookieContainer();
            cookieJar = ReadCookie(@"FUT.cookie." + AppVersion.CompanionApp);
            FutClient futClient = new FutClient(cookieJar);
            var loginDetails = new LoginDetails("xxx@xxx.xy", "xyz", "abcd", Platform.Pc, AppVersion.CompanionApp);
            Auth AuthHelper = new Auth();
            var loginResponse = await futClient.LoginAsync(loginDetails, AuthHelper);

            await DoTests(futClient);
        }

        private static async Task DoTests(FutClient futClient)
        {
            var creditsResponse = await futClient.GetCreditsAsync();
            Console.WriteLine(string.Format("Credits: {0}", creditsResponse.Credits));

            var pileSizeResponse = await futClient.GetPileSizeAsync();
            Console.WriteLine(string.Format("Tradepile size: {0}, Watchlist size: {1}", pileSizeResponse.Entries[0].Value, pileSizeResponse.Entries[2].Value));

            var tradePileResponse = await futClient.GetTradePileAsync();
            Console.WriteLine(string.Format("Found {0} tradepile items", tradePileResponse.AuctionInfo.Count));

            var squadListResponse = await futClient.GetSquadListAsync();
            Console.WriteLine(string.Format("Found {0} squads", squadListResponse.Squad.Count));

            var squadDetailsResponse = await futClient.GetSquadDetailsAsync(squadListResponse.ActiveSquadId);
            Console.WriteLine(string.Format("Active squad: {0}", squadDetailsResponse.SquadName));

            var clubItems = await futClient.GetClubItemsAsync();
            Console.WriteLine(string.Format("Found {0} players in club", clubItems.ItemData.Count));

            var searchParameters = new PlayerSearchParameters
            {
                ResourceId = 188567
            };
            var searchResponse = await futClient.SearchAsync(searchParameters);
            Console.WriteLine(string.Format("Found {0} auctions", searchResponse.AuctionInfo.Count));

            var giftsListResponse = await futClient.GetGiftsListAsync();
            foreach (var activeMessages in giftsListResponse.ActiveMessage)
            {
                //HandleMessage
            }

            //await futClient.SendPinRequestAsync(PinEventId.CompanionApp_AppOpened);

            //Get available Packs
            /*
            var storeResponse = await futClient.GetPackDetailsAsync();

            uint packId = 0;

            foreach (Pack packDetail in storeResponse.Purchase)
            {
                if (packDetail.Coins == 7500)
                {
                    packId = packDetail.Id;
                }
            }

            //Buy Pack
            var buyPackResponse = await futClient.BuyPackAsync(new PackDetails(packId));

            */

            /*
            //BID
            var auctionResponse = await futClient.PlaceBidAsync(searchResponse.AuctionInfo[0]);
            Console.WriteLine(string.Format("Bid 150 coins on trade id {0}", auctionResponse.AuctionInfo[0].TradeIdStr));

            //await futClient.RemoveFromWatchlistAsync(auctionResponse.AuctionInfo[0]);
            //Console.WriteLine(string.Format("Remove trade id {0} from watchlist", auctionResponse.AuctionInfo[0].TradeIdStr));

            //BIN
            var binAuctionResponse = await futClient.PlaceBidAsync(searchResponse.AuctionInfo[0], searchResponse.AuctionInfo[0].BuyNowPrice);
            Console.WriteLine(string.Format("BIN {0} coins on trade id {1}", searchResponse.AuctionInfo[0].BuyNowPrice, binAuctionResponse.AuctionInfo[0].TradeIdStr));

            var purchasedItemsResponse = await futClient.GetPurchasedItemsAsync();
            var sendToTradePileResponse = await futClient.SendItemToTradePileAsync(purchasedItemsResponse.ItemData[0]);
            Console.WriteLine(string.Format("Send trade id {0} to tradepile", binAuctionResponse.AuctionInfo[0].TradeIdStr));

            List<long> itemId = new List<long>();
            itemId.Add(sendToTradePileResponse.ItemData[0].Id);
            var priceRangeTradepileResponse = await futClient.GetTradePileAsync();
            var priceRanges = await futClient.GetPriceRangesAsync(itemId);
            //Console.WriteLine(string.Format("Pricerange for trade id {0} MIN: {1} coins MAX: {2} coins", binAuctionResponse.AuctionInfo[0].TradeIdStr.ToString()), priceRanges[0].MinPrice, priceRanges[0].MaxPrice);

            var quickSellResponse = await futClient.QuickSellItemAsync(sendToTradePileResponse.ItemData[0].Id);
            */

            var searchDevParameters = new DevelopmentSearchParameters
            {
                Page = 1,
                Level = Level.Gold,
                DevelopmentType = DevelopmentType.Healing,
            };

            var searchDevResponse = await futClient.SearchAsync(searchDevParameters);
            Console.WriteLine(string.Format("Found {0} development auctions", searchDevResponse.AuctionInfo.Count));

            var searchTrainingParameters = new TrainingSearchParameters
            {
                Page = 1,
                Level = Level.Gold,
                TrainingType = TrainingType.ChemistryStyles,
            };

            var searchTrainingResponse = await futClient.SearchAsync(searchTrainingParameters);
            Console.WriteLine(string.Format("Found {0} training auctions", searchTrainingResponse.AuctionInfo.Count));

            var item = await futClient.GetItemAsync(searchResponse.AuctionInfo[0].ItemData.AssetId);
            var playerImageBytes = await futClient.GetPlayerImageAsync(searchResponse.AuctionInfo[0]);
            Console.WriteLine(string.Format("Player Image Size: {0} ", playerImageBytes.Length));

            var ClubImageBytes = await futClient.GetClubImageAsync(searchResponse.AuctionInfo[0]);
            Console.WriteLine(string.Format("Club Image Size: {0} ", ClubImageBytes.Length));

            var NationImageBytes = await futClient.GetNationImageAsync(item);
            Console.WriteLine(string.Format("Nation Image Size: {0} ", ClubImageBytes.Length));

            await futClient.ReListAsync();
            Console.WriteLine("Relist all auctions in tradepile");

            await futClient.RemoveSoldItemsFromTradePileAsync();
            Console.WriteLine("Removed sold auctions in tradepile");

            await futClient.RemoveFromTradePileAsync(tradePileResponse.AuctionInfo[0]);
            Console.WriteLine(string.Format("Removed sold auction with Trade Id {0} in tradepile", tradePileResponse.AuctionInfo[0].TradeId));
        }
        private static CookieContainer ReadCookie(string file)
        {
            using (Stream stream = File.Open(file, FileMode.Open))
            {
                BinaryFormatter formatter = new BinaryFormatter();
                return (CookieContainer)formatter.Deserialize(stream);
            }
        }

    }

    public partial class Auth : ITwoFactorCodeProvider
    {
        private TaskCompletionSource<string> taskResult = new TaskCompletionSource<string>();
        public Task<string> GetTwoFactorCodeAsync()
        {
            Console.WriteLine("Enter OTP:");
            taskResult.SetResult(Console.ReadLine());
            return taskResult.Task;
        }
    }
}`

**Comment by Taggardos** [comment]
If you don't have an Cookiefile, just comment the Readcookie call out and create the Futclient Instance without it. 

`#cookieJar = ReadCookie(@"FUT.cookie." + AppVersion.WebApp);`
`FutClient futClient = new FutClient();`

**Comment by marlonespindola** [comment]
now the program is hanging on 
var loginDetails = new LoginDetails("xxx@xxx.xy", "xyz", "abcd", Platform.Pc, AppVersion.CompanionApp);
it dont give me any error, just hangs... 

heres the code that im using:

`
using Android.App;
using Android.Widget;
using Android.OS;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Runtime.Serialization.Formatters.Binary;
using System.Text;
using System.Threading.Tasks;
using UltimateTeam.Toolkit;
using UltimateTeam.Toolkit.Constants;
using UltimateTeam.Toolkit.Exceptions;
using UltimateTeam.Toolkit.Models;
using UltimateTeam.Toolkit.Parameters;
using UltimateTeam.Toolkit.Services;

namespace App5
{
    [Activity(Label = "App5", MainLauncher = true, Icon = "@drawable/icon")]
    public class MainActivity : Activity
    {
        protected override void OnCreate(Bundle bundle)
        {
            base.OnCreate(bundle);

            ServicePointManager.ServerCertificateValidationCallback = delegate { return true; };

//            DoWebLogin().Wait();
//            Console.WriteLine("Press any key to proceed to App Login");
//            Console.ReadLine();
            DoAppLogin().Wait();
            Console.WriteLine("Press any key to proceed to Exit FUT Toolkit Tester");
            Console.ReadLine();

        }

        static async Task DoWebLogin()
        {
//            var cookieJar = new CookieContainer();
//            cookieJar = ReadCookie(@"FUT.cookie." + AppVersion.WebApp);
//            FutClient futClient = new FutClient(cookieJar);
            FutClient futClient = new FutClient();
            var loginDetails = new LoginDetails("xxx@xxx.xy", "xyz", "abcd", Platform.Pc, AppVersion.WebApp);
            Auth AuthHelper = new Auth();
            var loginResponse = await futClient.LoginAsync(loginDetails, AuthHelper);

            await DoTests(futClient);
        }

        static async Task DoAppLogin()
        {
//            var cookieJar = new CookieContainer();
//            cookieJar = ReadCookie(@"FUT.cookie." + AppVersion.CompanionApp);
//            FutClient futClient = new FutClient(cookieJar);
            FutClient futClient = new FutClient();
            var loginDetails = new LoginDetails("xxx@xxx.xy", "xyz", "abcd", Platform.Pc, AppVersion.CompanionApp);
            Auth AuthHelper = new Auth();
            var loginResponse = await futClient.LoginAsync(loginDetails, AuthHelper);

            await DoTests(futClient);
        }

        private static async Task DoTests(FutClient futClient)
        {
            var creditsResponse = await futClient.GetCreditsAsync();
            Console.WriteLine(string.Format("Credits: {0}", creditsResponse.Credits));

            var pileSizeResponse = await futClient.GetPileSizeAsync();
            Console.WriteLine(string.Format("Tradepile size: {0}, Watchlist size: {1}", pileSizeResponse.Entries[0].Value, pileSizeResponse.Entries[2].Value));

            var tradePileResponse = await futClient.GetTradePileAsync();
            Console.WriteLine(string.Format("Found {0} tradepile items", tradePileResponse.AuctionInfo.Count));

            var squadListResponse = await futClient.GetSquadListAsync();
            Console.WriteLine(string.Format("Found {0} squads", squadListResponse.Squad.Count));

            var squadDetailsResponse = await futClient.GetSquadDetailsAsync(squadListResponse.ActiveSquadId);
            Console.WriteLine(string.Format("Active squad: {0}", squadDetailsResponse.SquadName));

            var clubItems = await futClient.GetClubItemsAsync();
            Console.WriteLine(string.Format("Found {0} players in club", clubItems.ItemData.Count));

            var searchParameters = new PlayerSearchParameters
            {
                ResourceId = 188567
            };
            var searchResponse = await futClient.SearchAsync(searchParameters);
            Console.WriteLine(string.Format("Found {0} auctions", searchResponse.AuctionInfo.Count));

            var giftsListResponse = await futClient.GetGiftsListAsync();
            foreach (var activeMessages in giftsListResponse.ActiveMessage)
            {
                //HandleMessage
            }

            var searchDevParameters = new DevelopmentSearchParameters
            {
                Page = 1,
                Level = Level.Gold,
                DevelopmentType = DevelopmentType.Healing,
            };

            var searchDevResponse = await futClient.SearchAsync(searchDevParameters);
            Console.WriteLine(string.Format("Found {0} development auctions", searchDevResponse.AuctionInfo.Count));

            var searchTrainingParameters = new TrainingSearchParameters
            {
                Page = 1,
                Level = Level.Gold,
                TrainingType = TrainingType.ChemistryStyles,
            };

            var searchTrainingResponse = await futClient.SearchAsync(searchTrainingParameters);
            Console.WriteLine(string.Format("Found {0} training auctions", searchTrainingResponse.AuctionInfo.Count));

            var item = await futClient.GetItemAsync(searchResponse.AuctionInfo[0].ItemData.AssetId);
            var playerImageBytes = await futClient.GetPlayerImageAsync(searchResponse.AuctionInfo[0]);
            Console.WriteLine(string.Format("Player Image Size: {0} ", playerImageBytes.Length));

            var ClubImageBytes = await futClient.GetClubImageAsync(searchResponse.AuctionInfo[0]);
            Console.WriteLine(string.Format("Club Image Size: {0} ", ClubImageBytes.Length));

            var NationImageBytes = await futClient.GetNationImageAsync(item);
            Console.WriteLine(string.Format("Nation Image Size: {0} ", ClubImageBytes.Length));

            await futClient.ReListAsync();
            Console.WriteLine("Relist all auctions in tradepile");

            await futClient.RemoveSoldItemsFromTradePileAsync();
            Console.WriteLine("Removed sold auctions in tradepile");

            await futClient.RemoveFromTradePileAsync(tradePileResponse.AuctionInfo[0]);
            Console.WriteLine(string.Format("Removed sold auction with Trade Id {0} in tradepile", tradePileResponse.AuctionInfo[0].TradeId));
        }

        private static CookieContainer ReadCookie(string file)
        {
            using (Stream stream = File.Open(file, FileMode.Open))
            {
                BinaryFormatter formatter = new BinaryFormatter();
                return (CookieContainer)formatter.Deserialize(stream);
            }
        }

    }

    public partial class Auth : ITwoFactorCodeProvider
    {
        private TaskCompletionSource<string> taskResult = new TaskCompletionSource<string>();
        public Task<string> GetTwoFactorCodeAsync()
        {
            Console.WriteLine("Enter OTP:");
            taskResult.SetResult(Console.ReadLine());
            return taskResult.Task;
        }
    }

}


`

**Comment by tringler** [comment]
It is maybe the same behaviour I experienced as I wanted to use Mono - https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/issues/169

**Comment by marlonespindola** [comment]
@tringler this code that you provided  on #272 works in what language?

**Comment by tringler** [comment]
It works in C# native, but not in C# Mono.

**Comment by trydis** [comment]
@marlonespindola your latest example looks like a Xamarin.Android app. Your `GetTwoFactorCodeAsync` method gets the result from `Console.ReadLine`, how does that work in a Xamarin.Android app? On what line does it hang?

**Comment by marlonespindola** [comment]
Yes @trydis it is a xamarin.android app tha I am trying to do.
The console.readline is there because Im using a code provided by @tringler .
But putting a break on the GetTwoFactorCodeAsync, it never stops there. My gess is that the program never gets there. It hangs before that.

Keeps hanging in this line inside DoAppLogin
On this line:
var loginDetails = new LoginDetails("xxx@xxx.xy", "xyz", "abcd", Platform.Pc, AppVersion.CompanionApp);

appreciate the help guys...

**Comment by marlonespindola** [comment]
actually it is hanging on this line...

var loginResponse = await futClient.LoginAsync(loginDetails, AuthHelper);

not the line that i said previously.

**Comment by Taggardos** [comment]
So it seems, that the Application hangs, while it waits for the Code.
I never worked with Xamarin, but I don't think that you can use `Console.Readline` within an Android App.

I think it would be the Best for you, if you let go of the Test-Script and write your own Code-Snippet. (Receive the Code with a simple Text Field, where you can enter the Code)

**Comment by trydis** [comment]
Ok, but his example was a console application, so `GetTwoFactorCodeAsync` expects input from the user in a command prompt.

**Comment by marlonespindola** [comment]
so, i've done what you said.
I removed de readLine and I'm passing a code directly, but stills hanging.
the code looks like this:

`    public partial class Auth : ITwoFactorCodeProvider
    {
        private TaskCompletionSource<string> taskResult = new TaskCompletionSource<string>();
        public Task<string> GetTwoFactorCodeAsync()
        {
            taskResult.SetResult("******");
            return taskResult.Task;
        }
    }
`

**Comment by marlonespindola** [comment]
so, i've done what you said.
I removed de readLine and I'm passing a code directly, but stills hanging.
the code looks like this:


    public partial class Auth : ITwoFactorCodeProvider
    {
        private TaskCompletionSource<string> taskResult = new TaskCompletionSource<string>();
        public Task<string> GetTwoFactorCodeAsync()
        {
            taskResult.SetResult("357843");
            return taskResult.Task;
        }
    }

**Comment by marlonespindola** [comment]
Funny thing is, i've created a new C# project, using this tool, and it doesnt hang. It passes the point.
Its given me error still, but I'm working on it.

**Comment by tringler** [comment]
No action on this issue since months, so I will close that issue now.
