### ISSUE TITLE
How do I save the login cookie into in a file?

### ISSUE THREAD

**Issue by shady2k12** [trydis/FIFA-Ultimate-Team-Toolkit#340]
Just out of interest I would like to know how the cookie file works.
I know you can login without using the cookie but I would just like to understand how you use it.
So can someone please give me some hints on how to implement this?

`var cookieJar = new CookieContainer();
string fileName = username + @"FUT.cookie." + AppVersion.CompanionApp;
FutClient futClient = new FutClient(cookieJar);`

**Comment by Bltfast** [comment]
after the successfully login, your futClient object will contain the cookie container with all the necessary to perform a next login without requesting two factor code again. All you have to do is store the cookie container in a file after the login and read it from the file before the login.

The code I use is:

        public static void WriteCookiesToDisk(string file, CookieContainer c)
        {
            using (Stream stream = File.Create(file))
            {
                try
                {
                    WriteLog.DoWrite("Writing cookies to disk... ");
                    BinaryFormatter formatter = new BinaryFormatter();
                    formatter.Serialize(stream, c);
                    WriteLog.DoWrite("Done.");
                }
                catch (Exception e)
                {
                    WriteLog.DoWrite("Problem writing cookies to disk: " + e.GetType());
                }
            }
        }

        public static CookieContainer ReadCookiesFromDisk(string file)
        {

            try
            {
                using (Stream stream = File.Open(file, FileMode.Open))
                {
                    BinaryFormatter formatter = new BinaryFormatter();
                    return (CookieContainer) formatter.Deserialize(stream);
                }
            }
            catch (Exception e)
            {
                WriteLog.DoWrite("Problem reading cookies from disk: " + e.GetType());
                return new CookieContainer();
            }

        }

**Comment by shady2k12** [comment]
I see, many thanks @Bltfast. I  will try this out.
