### ISSUE TITLE
errorCode":473

### ISSUE THREAD

**Issue by pashaparenyuk** [trydis/FIFA-Ultimate-Team-Toolkit#341]
{"itemData":[{"id":274721998472,"reason":"Destination Full","pile":"trade","success":false,"errorCode":473}]}
response from server;

catch this error when try make a bid /fifa17/trade/191959237803/bid

whats i make wrong?

**Comment by bijandaei** [comment]
The problem is that you're trade pile is full. You need to sell some of you're items before you can buy new ones.

**Comment by pashaparenyuk** [comment]
Thanks
