### ISSUE TITLE
Can't get access web app market + buying accounts if you have 

### ISSUE THREAD

**Issue by israeliMaster** [trydis/FIFA-Ultimate-Team-Toolkit#342]
how can I get access to the web app market
before one month I opened 3 accounts played 7 games and after 3 days they had access to the web app

last week I opened other 3 account played even more than 7 games and I didn't get the web access , it's still saying " playing more...".
Is it because the main account that bought the game on xbox got a ban?
is  it because the changed the numbers of game you need?

**and if someone sell accounts with web app access I will buy it from you (skype: danielll007)** 

.thanks

**Comment by Majed93** [comment]
It's because you need to play more games.

**Comment by israeliMaster** [comment]
the question is how many
before one month i have been played 7 games and wating 3-4 days
today it is not work for me any more

**Comment by Majed93** [comment]
From my experience there is no definitive number, some take longer than others, you'll just have to keep playing until they're unlocked.

**Comment by kauefelipe** [comment]
From experience, I also say that it does not have a certain number. I already had accounts that I needed less than 10, and anothers more than 20 and more than a week ...

I have an account with 800k and the market is released. If you have interest you can send me an email that we can negotiate. Kaueffreitascampeonatofifa@gmail.com

**Comment by tringler** [comment]
No action on this issue since months, so I will close that issue now.
