### ISSUE TITLE
Login Failed: Companion

### ISSUE THREAD

**Issue by pashaparenyuk** [trydis/FIFA-Ultimate-Team-Toolkit#343]
Login Failed: Could not find member 'access_token' on object of type 'MobileToken'. Path 'access_token', line 2, position 18.

when try login with companion app

Please help if its possible.

I wanna try to use companion auth and client to make some requests, when i was WebApp auth i catch temporary ban for search requests.

I think companion auth solve this problem,but i cant auth for reason in header

**Comment by tringler** [comment]
Issue will be closed, because of inactivity and FIFA release change.
