### ISSUE TITLE
FUT18 adaptation

### ISSUE THREAD

**Issue by ulrickpsp** [trydis/FIFA-Ultimate-Team-Toolkit#347]
Hi all!

Just starting this thread to check whether there are people interested in toolkit this year :D

**Comment by Ricbun16** [comment]
Very! Hows the ban thing going right now tho?

**Comment by ulrickpsp** [comment]
I'll let you know as soon as I get login working

**Comment by tringler** [comment]
If anyone can provide me a fut account I'm pretty sure I can fix the login. I only have my personal one I don't want to get banned again.

**Comment by kauefelipe** [comment]
@tringler i sent u an email...

**Comment by parenyukp** [comment]
Same here. im trying fix login,
So i can get twofactorcode an email and next i cant get shards and nucleusid

so, when u turn 2factor u need to put on html form button subit.

making a post request in ur twofactor
_eventId=submit
and then making another one with code and some atrbs:
oneTimeCode=341876&_trustThisDevice=on&trustThisDevice=on&_eventId=submit

there is my twofactor method in loginrequest.cs:


` private async Task<HttpResponseMessage> SetTwoFactorCodeAsync(HttpResponseMessage loginResponse)
        {
            //check if twofactorcode is required
            var contentData = await loginResponse.Content.ReadAsStringAsync();

            if (!(contentData.Contains("We sent a security code to your") ||contentData.Contains("In order to verify your identity")||
                  contentData.Contains("Your security code was sent to") ||
                  contentData.Contains("Enter the 6-digit verification code generated by your App Authenticator")))
            {
                return loginResponse;
            }

          //  var tfCode = await _twoFactorCodeProvider.GetTwoFactorCodeAsync();

            var responseContent = await loginResponse.Content.ReadAsStringAsync();

            AddReferrerHeader(loginResponse.RequestMessage.RequestUri.ToString());

            var codeResponseMessage = await HttpClient.PostAsync(loginResponse.RequestMessage.RequestUri,
                new FormUrlEncodedContent(
                    new[]
                    {
                     new KeyValuePair<string, string>("codeType", "EMAIL"),
                        new KeyValuePair<string, string>("_eventId", "submit")
                    }));

            codeResponseMessage.EnsureSuccessStatusCode();
            var responseContent2 = await codeResponseMessage.Content.ReadAsStringAsync();
            var tfCode = await _twoFactorCodeProvider.GetTwoFactorCodeAsync();
     
            var codeResponseMessage2 = await HttpClient.PostAsync(loginResponse.RequestMessage.RequestUri,
             new FormUrlEncodedContent(
                 new[]
                 {
                        new KeyValuePair<string, string>(responseContent2.Contains("oneTimeCode") ? "oneTimeCode" : "oneTimeCode", tfCode),
                        new KeyValuePair<string, string>("_trustThisDevice", "on"),
                        new KeyValuePair<string, string>("trustThisDevice", "on"),
                    
                          new KeyValuePair<string, string>("placeholder", tfCode),
                              new KeyValuePair<string, string>("_eventId", "submit"),


                 }));


      

            var tfcResponseContent = await codeResponseMessage2.Content.ReadAsStringAsync();

      //      if (tfcResponseContent.Contains("Incorrect code entered"))
          //      throw new FutException("Incorrect TwoFactorCode entered.");

            return codeResponseMessage;
        }`


some bugs or my fail: page return always incorrect code, but its worked for me.


some links in resources cs(web app):

  switch (appVersion)
            {
                case AppVersion.WebApp:

                    Validate = "https://www.easports.com/iframe/fut18/p/ut/game/fifa18/phishing/validate"; //not worker

                    Auth = "https://www.easports.com/uk/fifa/ultimate-team/web-app/auth.htm";
// not worked for me

                    Home = "https://signin.ea.com/p/web2/login?execution=e1009644976s1&initref=https%3A%2F%2Faccounts.ea.com%3A443%2Fconnect%2Fauth%3Fprompt%3Dlogin%26accessToken%3Dnull%26client_id%3DFIFA-18-WEBCLIENT%26response_type%3Dtoken%26display%3Dweb2%252Flogin%26locale%3Den_US%26redirect_uri%3Dhttps%253A%252F%252Fwww.easports.com%252Fuk%252Ffifa%252Fultimate-team%252Fweb-app%252Fauth.html%26scope%3Dbasic.identity%2Boffline%2Bsignin";
// worked

                    NucleusId = "https://gateway.ea.com/proxy/identity/pids/me";// not worked

                    Shards = "https://utas.mob.v4.fut.ea.com/ut/shards/v2?_=1506362099243";// must worked but i cant get nucleusid

                    AccountInfo = "https://www.easports.com/iframe/fut18/p/ut/game/fifa18/user/accountinfo?sku=FUT18WEB&_={0}";
//idk

                    Item = "https://fifa18.content.easports.com/fifa/fltOnlineAssets/CC8267B6-0817-4842-BB6A-A20F88B05418/2017/fut/items/web/{0}.json";
//idk
                    PlayerImage = "http://fifa18.content.easports.com/fifa/fltOnlineAssets/CC8267B6-0817-4842-BB6A-A20F88B05418/2017/fut/items/images/players/web/{0}.png";
//idk
                    FlagsImage = "http://fifa18.content.easports.com/fifa/fltOnlineAssets/CC8267B6-0817-4842-BB6A-A20F88B05418/2017/fut/items/images/cardflagssmall/web/{0}.png";
//idk
                    ClubImage = "http://fifa18.content.easports.com/fifa/fltOnlineAssets/CC8267B6-0817-4842-BB6A-A20F88B05418/2017/fut/items/images/clubbadges/web/dark/s{0}.png";
//idk
                    break;

**Comment by tringler** [comment]
For me it looks like they dropped the crappy flash webapp and using now the CompanionApp code for webapp and companionapp with different SKUs.

**Comment by tringler** [comment]
@parenyukp 
You get the NucleusId by:

```GET https://gateway.ea.com/proxy/identity/pids/me HTTP/1.1
Host: gateway.ea.com
Connection: keep-alive
Accept: application/json; charset=utf-8; */*; q=0.01
Origin: https://www.easports.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36
Authorization: Bearer AUTHID
Content-Type: application/json
Referer: https://www.easports.com/de/fifa/ultimate-team/web-app/
Accept-Encoding: gzip, deflate, br
Accept-Language: de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4```

I'm pretty sure, that I have a working code now - Just waiting for @kauefelipe 's account.

**Comment by parenyukp** [comment]
@tringler  yeah this worked well, but how can i get authorization header value? "Bearer AUTHID"?

**Comment by ulrickpsp** [comment]
Hi mates! I'm struggling at the the first screen. I make a post request with the following headers:

```
POST https://signin.ea.com/p/web2/login?execution=e1797819821s1&initref=https%3A%2F%2Faccounts.ea.com%3A443%2Fconnect%2Fauth%3Fprompt%3Dlogin%26accessToken%3Dnull%26client_id%3DFIFA-18-WEBCLIENT%26response_type%3Dtoken%26display%3Dweb2%252Flogin%26locale%3Des_ES%26redirect_uri%3Dhttps%253A%252F%252Fwww.easports.com%252Fes%252Ffifa%252Fultimate-team%252Fweb-app%252Fauth.html%26scope%3Dbasic.identity%2Boffline%2Bsignin HTTP/1.1
Connection: keep-alive
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36
Accept-Encoding: gzip, deflate, br
Referer: https://signin.ea.com/p/web2/login?execution=e1797819821s1&initref=https:%2F%2Faccounts.ea.com:443%2Fconnect%2Fauth%3Fprompt%3Dlogin%26accessToken%3Dnull%26client_id%3DFIFA-18-WEBCLIENT%26response_type%3Dtoken%26display%3Dweb2%252Flogin%26locale%3Des_ES%26redirect_uri%3Dhttps%253A%252F%252Fwww.easports.com%252Fes%252Ffifa%252Fultimate-team%252Fweb-app%252Fauth.html%26scope%3Dbasic.identity%2Boffline%2Bsignin
Origin: https://signin.ea.com/
Upgrade-Insecure-Requests: 1
Accept: text/html, application/xhtml+xml, application/xml; q=0.9, image/webp, image/apng, */*; q=0.8
Cache-Control: max-age=0
Content-Type: application/x-www-form-urlencoded
Host: signin.ea.com
Cookie: JSESSIONID=D75BD004E55D2183AE94419EFCA4C69E.prdaccountc-45
Content-Length: 127

email=xxxxxxxxxx&password=xxxxxxxxx&_eventId=submit&gCaptchaResponse=&isPhoneNumberLogin=false&isIncompletePhone=

```

**Comment by CoverJ** [comment]
If I have a second account made on the same xbox as my main account, and my second acc gets banned is my main account banned? it would probably at least be put under more scrutiny?

**Comment by KristianSv** [comment]
I'm working on the python library, but to get the authorization id you need to make a call to:
`https://accounts.ea.com/connect/auth?prompt=login&accessToken=null&client_id=FIFA-18-WEBCLIENT&response_type=token&display=web2%2Flogin&locale=en_US&redirect_uri=https%3A%2F%2Fwww.easports.com%2Ffifa%2Fultimate-team%2Fweb-app%2Fauth.html&scope=basic.identity+offline+signin&fid=` **fid id goes here**

**Get the fid id** by scraping the html you get from the GET call to:
`https://signin.ea.com/p/web2/login?execution=e1217867131s6&initref=https%3A%2F%2Faccounts.ea.com%3A443%2Fconnect%2Fauth%3Fprompt%3Dlogin%26accessToken%3Dnull%26client_id%3DFIFA-18-WEBCLIENT%26response_type%3Dtoken%26display%3Dweb2%252Flogin%26locale%3Den_US%26redirect_uri%3Dhttps%253A%252F%252Fwww.easports.com%252Ffifa%252Fultimate-team%252Fweb-app%252Fauth.html%26scope%3Dbasic.identity%2Boffline%2Bsignin`

It's in the html tag with class=registration-link and looks so:
`<a href="./create?fid=RlMxOjEuMDoyLjA6NVVJV0JCQTJHRzd2V3J3THF3YmR1UFd2Om51NWtu" class="registration-link" isRegisterPopup="no">`

I think that's how to do it. Will test it myself later.
Hope I could be of any help.

**Comment by parenyukp** [comment]
@KristianSv  thx dude. Think this help me.

**Comment by tringler** [comment]
It's the same procedure like CompanionApp last season. I think I can fix the repo by this evening.

**Comment by parenyukp** [comment]
@tringler i will wait ur fixes.)

**Comment by parenyukp** [comment]
@KristianSv  another question. Im trying parse fid. This value realy in html code in href. Then i try get authid
and put my fid into get request on ur url. server returned to me:
{"error":"invalid_request","error_description":"fid is invalid"}

maybe this request need more headers? at now this is my headers:

User-Agent: Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/29.0.1547.62 Safari/537.36
Accept-Encoding: gzip, deflate
Referer: https://signin.ea.com/p/web2/login?execution=e2129460649s3&initref=https:%2F%2Faccounts.ea.com:443%2Fconnect%2Fauth%3Fprompt%3Dlogin%26accessToken%3Dnull%26client_id%3DFIFA-18-WEBCLIENT%26response_type%3Dtoken%26display%3Dweb2%252Flogin%26locale%3Den_US%26redirect_uri%3Dhttps%253A%252F%252Fwww.easports.com%252Fuk%252Ffifa%252Fultimate-team%252Fweb-app%252Fauth.html%26scope%3Dbasic.identity%2Boffline%2Bsignin
Host: accounts.ea.com
Content-Length: 0

**Comment by ulrickpsp** [comment]
Could anybody please post the changes needed in order to pass the first screen? It's driving me nuts...I mean the changes necessary to reach this point:

![image](https://user-images.githubusercontent.com/8997800/30858351-9d264920-a2bf-11e7-90a5-3e4e948da004.png)

**Comment by parenyukp** [comment]
@ulrickpsp yeah i solve this. u need to send request to put button send on this form.

for me its seems like:

var codeResponseMessage = await HttpClient.PostAsync(loginResponse.RequestMessage.RequestUri,
            new FormUrlEncodedContent(
                new[]
                {
                 new KeyValuePair<string, string>("codeType", "EMAIL"),
                    new KeyValuePair<string, string>("_eventId", "submit")
                }));

post request with body codetype:EMAIL and _eventID:submit

**Comment by tringler** [comment]
Just wait for my PR - It should be something like this I think:
```
        protected async Task<HttpResponseMessage> LoginForwarder(HttpResponseMessage responseMessage)
        {
            HttpResponseMessage forwardResponseMessage = new HttpResponseMessage();
            var contentData = await responseMessage.Content.ReadAsStringAsync();
            if (contentData.Contains("https://signin.ea.com:443/p/web2/login?execution="))
            {
                Match executionIdMatch = Regex.Match(contentData, @"https:\/\/signin\.ea\.com:443\/p\/web2\/login\?execution=([A-Za-z0-9\-]+)");

                string executionId = executionIdMatch.Groups[1].Value;
                forwardResponseMessage = await HttpClient.GetAsync("https://signin.ea.com:443/p/web2/login?execution=" + executionId + "&_eventId=end");

                return forwardResponseMessage;
            }
            return responseMessage;
        }
```

**Comment by ulrickpsp** [comment]
I appreciate your reply @parenyukp . Unfortunately I'm stuck at the previous screen so I cannot reach this one. Maybe I didn't explain properly.

**Comment by KristianSv** [comment]
@parenyukp try this instead:
`'upgrade-insecure-requests': "1",
 'user-agent': "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) 
  Chrome/60.0.3112.113 Safari/537.36",
    'accept': "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
    'referer': "https://signin.ea.com/p/web2/login?execution=e1217867131s7&initref=https%3A%2F%2Faccounts.ea.com%3A443%2Fconnect%2Fauth%3Fprompt%3Dlogin%26accessToken%3Dnull%26client_id%3DFIFA-18-WEBCLIENT%26response_type%3Dtoken%26display%3Dweb2%252Flogin%26locale%3Den_US%26redirect_uri%3Dhttps%253A%252F%252Fwww.easports.com%252Ffifa%252Fultimate-team%252Fweb-app%252Fauth.html%26scope%3Dbasic.identity%2Boffline%2Bsignin",
 'accept-encoding': "gzip, deflate, br",
 'accept-language': "da-DK,da;q=0.8,en-US;q=0.6,en;q=0.4,de;q=0.2",
 'cache-control': "no-cache"`

In postman there's also a cookie in the header, but that shouldn't be necessary here.
Make sure you are using the same uger-agent throughout the code

**Comment by KristianSv** [comment]
I haven't tested it yet, but it SHOULD work :-)

**Comment by KristianSv** [comment]
@parenyukp have you tested it?

**Comment by parenyukp** [comment]
@KristianSv  yeah. Not working for me. Maybe i am doing wrong. but thanks for reply)

**Comment by KristianSv** [comment]
Np. I will let you guys know when/if I get it to work.

**Comment by ulrickpsp** [comment]
Anything special in the first post request with credentials? Cannot get through that state.

**Comment by parenyukp** [comment]
@ulrickpsp  i use this body:

     new KeyValuePair<string, string>("email", loginDetails.Username),
                        new KeyValuePair<string, string>("password", loginDetails.Password),
                        new KeyValuePair<string, string>("_rememberMe", "on"),
                        new KeyValuePair<string, string>("rememberMe", "on"),
                        new KeyValuePair<string, string>("_eventId", "submit"),
                        new KeyValuePair<string, string>("facebookAuth", ""),
                         new KeyValuePair<string, string>("PhoneNumberLogin", "false"),
                                 new KeyValuePair<string, string>("isIncompletePhone", "false")

**Comment by ulrickpsp** [comment]
And which Home URL?

**Comment by parenyukp** [comment]
@ulrickpsp 

https://signin.ea.com/p/web2/login?execution=e1009644976s1&initref=https%3A%2F%2Faccounts.ea.com%3A443%2Fconnect%2Fauth%3Fprompt%3Dlogin%26accessToken%3Dnull%26client_id%3DFIFA-18-WEBCLIENT%26response_type%3Dtoken%26display%3Dweb2%252Flogin%26locale%3Den_US%26redirect_uri%3Dhttps%253A%252F%252Fwww.easports.com%252Fuk%252Ffifa%252Fultimate-team%252Fweb-app%252Fauth.html%26scope%3Dbasic.identity%2Boffline%2Bsignin

**Comment by ulrickpsp** [comment]
So strange..I'm doing the same. Do you have any special header in that requesT?

**Comment by parenyukp** [comment]
@ulrickpsp i dont think so, nothing specials, just standarts toolkit headers

**Comment by KristianSv** [comment]
If it's for getting the html which has the FID, try with these:

```
'origin': "https://signin.ea.com",
'upgrade-insecure-requests': "1",
'user-agent': (your own user-agent),
'content-type': "application/x-www-form-urlencoded",
'accept': "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
'referer': "https://signin.ea.com/p/web2/login?execution=e1217867131s4&initref=https%3A%2F%2Faccounts.ea.com%3A443%2Fconnect%2Fauth%3Fprompt%3Dlogin%26accessToken%3Dnull%26client_id%3DFIFA-18-WEBCLIENT%26response_type%3Dtoken%26display%3Dweb2%252Flogin%26locale%3Den_US%26redirect_uri%3Dhttps%253A%252F%252Fwww.easports.com%252Ffifa%252Fultimate-team%252Fweb-app%252Fauth.html%26scope%3Dbasic.identity%2Boffline%2Bsignin",
'accept-encoding': "gzip, deflate, br",
'accept-language': "en-US;q=0.6,en;q=0.4",
'cache-control': "no-cache"
```

**Comment by ulrickpsp** [comment]
Are you using the last version of toolkit? I just downloaded the project, change HOME url and post data but cannot get it to work. So weird.

**Comment by KristianSv** [comment]
Oh sorry, not what you asked :-/

**Comment by ulrickpsp** [comment]
@KristianSv It will be useful, for sure.

**Comment by parenyukp** [comment]
there is my custom loginrequest.cs
[LoginRequest.txt](https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/files/1333113/LoginRequest.txt)

**Comment by ulrickpsp** [comment]
@parenyukp really helpful. I was missing LoginRedirect().

**Comment by parenyukp** [comment]
@KristianSv  yeah. i can get fid now. i think i cant get authId because im send request with my fid so late, after twofactorcode, or too fast, or another one. And in response from ea(when i login into web app from my browser) i see that request with fid do not returned me authID. I think we need another way to get auth id.

Why we need authID?
cuz we need nuclearID.
in request to get nuclearID we must put AccessToken.
So i need to get AccessToken ;D to get nuclearID.
its look like Bearer AUTHID..

**Comment by KristianSv** [comment]
I think we get the access token from this:
`https://accounts.ea.com/connect/auth?prompt=login&accessToken=null&client_id=FIFA-18-WEBCLIENT&response_type=token&display=web2%2Flogin&locale=en_US&redirect_uri=https%3A%2F%2Fwww.easports.com%2Ffifa%2Fultimate-team%2Fweb-app%2Fauth.html&scope=basic.identity+offline+signin&fid=` **fid id goes here**

**Comment by tringler** [comment]
Within the whole WebApp all is handled now like in the CompanionApp in previous versions. That means I need to rewrite all transactions/delete the WebApp part.

**Comment by KristianSv** [comment]
@tringler Hi. If you think you can get it to work, there's no need for me to spend time on it I guess? :-)

**Comment by parenyukp** [comment]
@tringler  and so this is possible?its will be cool if u get this, just like a semi-working way to auth.

or can you get resources and mobileLogin.cs worked now?

**Comment by tringler** [comment]
Let me rework the whole repo this evening - This is much easier as some hackish code which needs to be reworked again to have a good code in the repo ;) - I'm pretty sure they kicked the whole webApp part and just redesigned the CompanionApp to a browser view. Just look like at the design of the WebApp - It's the same like on mobile phone.

**Comment by KristianSv** [comment]
Allright, I trust you on that one. If you get any trouble underway, contact me :-)

**Comment by tringler** [comment]
What would help if someone can provide a full fiddler trace of companionApp.

**Comment by parenyukp** [comment]
@tringler good luck)

**Comment by tringler** [comment]
Looks like I need another day, but the good news are I'm at the point we need to input the one time password. It looks like if you asking too often for an OTP you will not get it instantly. That's because my work is stuck at the moment.

From the Fiddler traces I see, when I get finished the OTP part it should be almost done. Here you are my latest state:

https://www.file-upload.net/download-12731048/FIFA-Ultimate-Team-Toolkit.7z.html

A lot of rework in loginbase.cs and loginrequest.cs is needed, but it's a first approach.

**Comment by parenyukp** [comment]
@tringler good job.Nice! Thanks for your work. Hope today toolkit maybe get worked!)

**Comment by parenyukp** [comment]
So i can get persona now. And next i will request for Auth. 

Auth = "https://utas.external.s2.fut.ea.com/ut/auth?timestamp=" + "{0}";

there is problem now code 500)

**Comment by ulrickpsp** [comment]
I'm ready to start coding right now. In order to get the most updated code and not waste time redoing things already done, where I should start from?

**Comment by KristianSv** [comment]
Same question here :-D

**Comment by CoverJ** [comment]
@ulrickpsp see @tringler post above he has a file-upload.net link

**Comment by KristianSv** [comment]
https://join.slack.com/t/netfutapi/shared_invite/enQtMjQ3NDYxNzM2Nzg3LTRkMGQxNDc0ZjA4ZjExOWUzNzY4ODJlNjRlNTgwOGM5NGY2MjA2MzE4MjcwYzgwNjkzY2FkMWZhN2FlNjE2ZjY

join my Slack. Then we don't fill up this thread

**Comment by tringler** [comment]
Right - I stopped working on it at the point you need to enter your one time password. It could be that the repo is working out of the box.

Things to do:
* Review the headers
* Get a companionapp trace to get ClientVersion and Client-Name and try companionapp login
* CleanUp LoginRequest.cs

**Comment by parenyukp** [comment]
Almost done. I need to send request for validate secret and its all)

**Comment by KristianSv** [comment]
Allright sounds nice, good job. How did you get the bearer authentication id?

**Comment by KristianSv** [comment]
@parenyukp you're of course also welcome in the slack I linked above ;-)

**Comment by parenyukp** [comment]
@KristianSv Bearer authID contains in response when you sucsessfully send twofactorcode and parse response from.

**Comment by KristianSv** [comment]
Oh yeah, I see. Got it.
But when I then do:
`var codeResponseMessageContent = await codeResponseMessage.Content.ReadAsStringAsync();`
It does not contain "code=" anywhere. Most of the content is javascript.
Did you get past this check:
`if (codeResponseMessage.RequestMessage.RequestUri.AbsoluteUri.Contains("code="))
 {
       LoginResponse.AuthCode.Code = 
          codeResponseMessage.RequestMessage.RequestUri.AbsoluteUri.Replace($"
                                                                                                          {Resources.CompanionAuthCode}", "");
}`
?

**Comment by parenyukp** [comment]
@KristianSv yeah, now thats not a string.contains("Code")

this way:

  if (codeResponseMessage.RequestMessage.RequestUri.AbsoluteUri.Contains("access_token="))
            {
                LoginResponse.AuthCode.Code = codeResponseMessage.RequestMessage.RequestUri.AbsoluteUri.Substring(codeResponseMessage.RequestMessage.RequestUri.AbsoluteUri.IndexOf("=")+1);
                LoginResponse.AuthCode.Code = LoginResponse.AuthCode.Code.Substring(0, LoginResponse.AuthCode.Code.IndexOf('&'));
             
            }

sorry idk regex, im parse this by substrings and indexofs

**Comment by parenyukp** [comment]
So. I can authorize. I can get a tradepile. Tomorrow i will upload my loginrequests and resources if this wil be actual.

**Comment by KristianSv** [comment]
Allright.

**Comment by ulrickpsp** [comment]
Got sutck after getting shards. Error 500.

**Comment by tringler** [comment]
Great Work! Share your code with me then that I can integrate it to my PR

**Comment by KristianSv** [comment]
@parenyukp can you post a snippet of your GetAuthTokenAsync() from LoginRequest?
Mine is throwing System.AggregateException, therefore I can't get the Nucleus id.

**Comment by parenyukp** [comment]
And now.

There is my toolkit. My codes need to be refactored if u guys wanna add it to repo,

My changes after @tringler latest state:

TwoFactorCode - now its sended at email. And now its correctly
GetAuthCode  - now authcode getting from response from twofactor request.
Validate request - now worked.
Cookies - now auth works with cookies same great for me.
GetItemAsync - reworked url - but its worked as 2017 assets.
Added some fields at persona, itemdata and item. just for correctly json deserialized.

So. Im tested this features with PS4 Accounts with opened trade.
[UltimateTeam.Toolkit_.zip](https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/files/1339689/UltimateTeam.Toolkit_.zip)


Thanks for @tringler - Great work with Forwarder and ect.

**Comment by ulrickpsp** [comment]
Great work @parenyukp and @tringler. Login seems to work fine now. Will check all requests to check if they are still valid

**Comment by ulrickpsp** [comment]
Seems that ListAuction has changed as well.

**Comment by parenyukp** [comment]
@ulrickpsp  nope. this works fine. im right now tested listauction, tradepiles, placebid, search - works well)
some fields just added from json response of getitemasync method and thats all..

**Comment by KristianSv** [comment]
@parenyukp I'm having trouble with the FutClient.SearchAsync(PlayerSearchParameters), even though I'm using the version you were so kind to upload this morning. When calling it, it returns only empty results :-/

**Comment by parenyukp** [comment]
@KristianSv 
try this way

  var searchParameters = new PlayerSearchParameters
                    {
                        Page = 1,
                        MaxBuy = price,
                        //  Level = setrarity(rows),
                        ResourceId = resId,
                        PageSize = 49
                    };
                    searchResponse = await _client.SearchAsync(searchParameters);

works fine for me.

**Comment by jagarake** [comment]
Just a quick (noob) question... How would i initialize this and start the login process? In the FutClient.cs file? Create a new file? Or create a new project and refer to the api project?

**Comment by parenyukp** [comment]
@jagarake  refer toolkit.dll and add using and next read main page repo.

**Comment by KristianSv** [comment]
@parenyukp so it is only possible to search for one specific player as of now, using Resource ID?

**Comment by artielange** [comment]
Hey all, are you guys still using email to get the 2 factor code? How come? EA let's you use authenticator apps now

**Comment by tringler** [comment]
I tried to refactor and summarize your contributions here - Thanks a lot! https://github.com/tringler/FIFA-Ultimate-Team-Toolkit/tree/FUT18

**Comment by parenyukp** [comment]
@KristianSv  possible, but without toolkit

  json_data = w.DownloadString("http://www.easports.com/uk/fifa/ultimate-team/api/fut/item?jsonParamObject=%7B%22name%22:%22" + name + "%22%7D");
 SearchResultJson deserializedProduct = JsonConvert.DeserializeObject<SearchResultJson>(json_data);

this way returned players with specific name

**Comment by tringler** [comment]
I created a Discord server for more chit-chat interaction: https://discordapp.com/channels/363450836183023616

**Comment by CoverJ** [comment]
@tringler the link doesnt work for me? got an invite link like discord.gg/blahblah

**Comment by tringler** [comment]
@CoverJ Maybe that one: https://discord.gg/uy6n8h

**Comment by tringler** [comment]
I didn't get it managed to get a Fiddler trace of CompanionApp - Anyone with more success? As soon as I activate Fiddler the connection to EA on the phobe is broken. Other connections are traced without any problems. Due to this fact I cannot fix the companionApp part :(

**Comment by tringler** [comment]
I assume they blocked any proxy and vpn connections for their app, which is the technique for https proxies I know. Any ideas?

**Comment by InkedCurtis** [comment]
@tringler if for a second you think you need to "bypass" the cert pinning, you're on the wrong path.

**Comment by lGuzl** [comment]
Hi guys,

I have all working with the last code, but i have an error in the RemoveSoldItemsFromTradePileAsync, "410: Gone"

Has anyone had this problem?


![sold error](https://user-images.githubusercontent.com/30179987/31341574-4e54c742-ace0-11e7-977b-ac6e760d913f.png)

**Comment by DjTrilogic** [comment]
So, we can’t use proxies for now ? 
--
Abdessamad Benslimane 
abdessamad.benslimane@usercube.com
+33 6 05 56 47 27 

De : lGuzl
Envoyé le :lundi 9 octobre 2017 15:55
À : trydis/FIFA-Ultimate-Team-Toolkit
Cc : Subscribed
Objet :Re: [trydis/FIFA-Ultimate-Team-Toolkit] FUT18 adaptation (#347)

Hi guys,
I have all working with the last code, but i have an error in the RemoveSoldItemsFromTradePileAsync, "410: Gone"
Has anyone had this problem?

**Comment by jagarake** [comment]
Are there anyone here who bought the game for Xbox One who could help me reactivate my account, since i didnt buy the game yet?

**Comment by KristianSv** [comment]
@jagarake I think you have to log in to the account in FUT18 on a Xbox for it to be reactivated (given it is because the early access is over, which is your problem)

**Comment by jagarake** [comment]
@KristianSv I know. But I didnt buy the game yet, so I wondered if anyone could log in to FUT for me to get my account activated.

**Comment by Ricbun16** [comment]
@jagarake You need to do way more then just logging in on a console. My farm account has almost 20 games played and is still locked from the transfermarket “to play more games on console”.

**Comment by KristianSv** [comment]
@Ricbun16 That's not what he's talking about. There's difference in not being able to trade once logged in, and being locked out because Early Access is over. If he logs into a console, he'll be able to play again. As far as I know this account HAD access to trade on the web app, when early access was ongoing, right @jagarake ?

**Comment by jagarake** [comment]
@KristianSv @Ricbun16 Yes i had early access and was able to trade on the webapp up untill today.

**Comment by tringler** [comment]
Closing this discussion, because we will push the FUT18 branch to vnext/master in the next days.

**Comment by jalley3** [comment]
is the discord still active? the link is dead
