### ISSUE TITLE
Login failed: Method Not Allowed

### ISSUE THREAD

**Issue by omgwtfholyshit** [trydis/FIFA-Ultimate-Team-Toolkit#348]
I'm having an error message saying status code 405: method not allowed at LoginRequest.LoginAsync(_loginDetails,mainPageResponseMessage)
It uses post method to send the data but the response message shows that the server only accepts HEAD/DELETE/PUT/GET methods.
I've been trying to use PUT method however it didn't work.
Any suggestions please?

**Comment by tringler** [comment]
Please test that branch: https://github.com/tringler/FIFA-Ultimate-Team-Toolkit/tree/FUT18

**Comment by tringler** [comment]
No answer since 7 days. I will close the issue.
