### ISSUE TITLE
FIFA 18 Players with end point 'fifa/ultimate-team/api/fut/item' 

### ISSUE THREAD

**Issue by cethak89** [trydis/FIFA-Ultimate-Team-Toolkit#349]
Hello,

When can we access to FIFA 18 players data with this end point [https://www.easports.com/fifa/ultimate-team/api/fut/item](url) or how can we access FIFA 18 players data?

Thanks

**Comment by tringler** [comment]
I think they dropped that kind of json db - You need to use know kind of that requests:
`https://www.easports.com/de/fifa/ultimate-team/api/fut/item?jsonParamObject=%7B%22baseid%22:%2220801%22,%22link%22:1%7D `
or
`https://www.easports.com/de/fifa/ultimate-team/api/fut/price-band/20801`
or
`https://www.easports.com/de/fifa/ultimate-team/api/fut/item?jsonParamObject=%7B%22ovr%22:%2274:99%22,%22pageSize%22:40,%22position%22:%22LW%22%7D`

Just use [Fiddler](http%3A%2F%2Fwww.telerik.com%2Ffiddler) and open [FUT DB](https://www.easports.com/de/fifa/ultimate-team/fut/database) - Then you can inspect all the requests you need for your project.

It's not part of the toolkit so far. Feel free to contribute a PR :)

**Comment by cethak89** [comment]
@tringler thanks for reply. I write some codes already for this endpoint " https://www.easports.com/fifa/ultimate-team/api/fut/item". So you are saying that there is no way to take FIFA 18 data from this endpoint?

Thanks alot

**Comment by cethak89** [comment]
Also Fiddler seems too expensive?

**Comment by trydis** [comment]
[Fiddler](http://www.telerik.com/fiddler) is free

**Comment by tringler** [comment]
No answer since about 1 month. Issue will be closed.

**Comment by wesleyamaro** [comment]
Hey @tringler 

Do you know how I can do to access real time prices from PS4??

For instance, Pogba is being sold for 480k right now, 5 minutes ago it was 479k. Do you know how i can check it?

**Comment by Javier-AN** [comment]
I made this script in python3. It takes all the json files from [this link](https://www.easports.com/fifa/ultimate-team/api/fut/item?page=1) (and the other 879 pages), discards the metadata so you just keep the player data and dumps that 87MB json array to a local file.
You can even modify it to just keep the link to the small images, or even download them to a folder, etc.

It also prints the download %.

```python
import urllib.request
import json

total = 880
items = []
for i in range(1, total + 1):
    with urllib.request.urlopen("https://www.easports.com/fifa/ultimate-team/api/fut/item?page=" + str(i)) as url:
        data = json.loads(url.read().decode())
        items += data['items']
        downloaded = int(i / total * 100)
        print("Downloaded: " + str(downloaded) + "%")

with open("download.json", "w") as f:
    print("Writing")
    json.dump(items, f)

```
