### ISSUE TITLE
.NET Core 2 Toolkit

### ISSUE THREAD

**Issue by DjTrilogic** [trydis/FIFA-Ultimate-Team-Toolkit#350]
Hello Guys,

Could you please take .NET core 2 into account when releasing the API.

Thank's!

**Comment by tringler** [comment]
I put that on the roadmap for this upcoming PR https://github.com/tringler/FIFA-Ultimate-Team-Toolkit/tree/FUT18

**Comment by tringler** [comment]
Hello @DjTrilogic - I think we need to wait some more time, because the most NuGet packages are not compatible to .Net Standard 2.0, yet. In example:
https://www.nuget.org/packages/Newtonsoft.Json/

As far as I understood you need to be compatible to .NET Standard 2.0 to target .NET Core and .NET Framework at the same time: https://blogs.msdn.microsoft.com/dotnet/2016/09/26/introducing-net-standard/

Any other ideas?

**Comment by trydis** [comment]
[Developing Libraries with Cross Platform Tools](https://docs.microsoft.com/en-us/dotnet/core/tutorials/libraries)

**Comment by tringler** [comment]
@trydis - I'm a bit unsure about that link - Do you think there is an option to get the needed nuGet packages with .NET Standard 2.0?

In my opinion it would be good idea to change to .NET Standard 1.0 to support all platforms.

**Comment by trydis** [comment]
Yes, i think so. I've made a few .NET Core apps and 2.0 makes a lot more API´s available, but the toolkit doesn't really need that much.

The templates that ship with VS default to 1.4:
> ...which gives you access to most APIs on .NET Standard while still being compatible with UWP,  > .NET Framework 4.6.1, and the forthcoming .NET Standard 2.0.

I don't mind 1.0, if possible, although MS support has ended for .NET Framework <= 4.5.1. Windows Phone Silverlight and Windows 8.x apps (Metro?) are dead as well.

I guess it's easier to check what could be the lowest target when the fifa 18 related stuff has been merged.

**Comment by tringler** [comment]
Yes, Ok. - Then let's wait for some testing feedback from the FUT18 branch and after it applied, we can see which option we can choose.

**Comment by DjTrilogic** [comment]
Alright, Fair enough !
Thank's mates

**Comment by DjTrilogic** [comment]
#360

**Comment by DjTrilogic** [comment]
Please guys, can we review this issue again, I'm facing a problem with the used version of .net standard.

Do you think that an update of .net core version would resolve it ? (i put the link of the issue i'm facing in the comment above)
