### ISSUE TITLE
Login verification improvement from EA (captcha)

### ISSUE THREAD

**Issue by KristianSv** [trydis/FIFA-Ultimate-Team-Toolkit#352]
![image](https://user-images.githubusercontent.com/25365788/31054070-f2b315c8-a6aa-11e7-9093-d88a401b80fa.png)

Have any of you tried this yet?

**Comment by tringler** [comment]
This must be a new feature. Can you please trace it via Fiddler? I'm not able to reproduce it.

**Comment by KristianSv** [comment]
[captchaTrace.zip](https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/files/1348352/captchaTrace.zip)
This has the .saz for Fiddler desktop. There might be two or three unnecessary calls in there, but I wasn't sure if they were needed.

**Comment by tringler** [comment]
Hello,

unfortunately the trace doesn't help, because he is not decrypted locally by Fiddler.

![image](https://user-images.githubusercontent.com/4985268/31070817-0d10338a-a762-11e7-9541-1bd4c2947dbb.png)

**Comment by KristianSv** [comment]
I will be a while before it will ask for captcha again. Can someone else post a trace?

**Comment by tringler** [comment]
Just FYI - This is how Fiddler needs to be configured to collect useful traces - http://docs.telerik.com/fiddler/Configure-Fiddler/Tasks/DecryptHTTPS

**Comment by Fullbreak** [comment]
I have some Fiddler Logs of Funcaptcha and already do somthing to find a way to send it to 2captcha.
I need someone who is good in JavaScript and can help me to unobfuscated some stuff of the FunCaptcha JS to do the right request.

The most problem is to calculate the var guess for the Funcaptcha POST request to solve them.

Maybe here some good Dev who like to share results in skype please contact me. Skype: fullbreak@protonmail.com

PS: When you Bot don't solve the captcha in some min you will get banned after 24-48h.

@tringler hope for your message in skype.

**Comment by tringler** [comment]
Hello,

I don't use Skype. You can provide the trace i.e. via Discord and I will have a look at it how to implement into the toolkit. Otherwise erase your personal data and upload it here.

**Comment by Fullbreak** [comment]
hi @tringler ,

i also have Discord please contact me there my email address there is fullbreak@protonmail.com

**Comment by tringler** [comment]
You can join our FUT Toolkit Discord channel: https://discord.gg/5h37bh

**Comment by DjTrilogic** [comment]
Expired invitation link…. Can you please provide another one ?

Provenance : Courrier pour Windows 10

De : tringler
Envoyé le :02 October 2017 17:30
À : trydis/FIFA-Ultimate-Team-Toolkit
Cc : Subscribed
Objet :Re: [trydis/FIFA-Ultimate-Team-Toolkit] Login verificationimprovement from EA (captcha) (#352)

You can join our FUT Toolkit Discord channel: https://discord.gg/5h37bh

**Comment by tringler** [comment]
https://discord.gg/rCwXds

**Comment by Ricbun16** [comment]
Expired, can you send a new one pleases? @tringler

**Comment by lGuzl** [comment]
@tringler , can u send a new discord invite?

**Comment by A-VORONKIN** [comment]
@tringler any news with funcaptcha? do you know how to calculate the var guess for the Funcaptcha POST?

**Comment by KmanProdz** [comment]
Any got a fiddler trace that is decrypted? and @Fullbreak accept my skype request.

**Comment by ulrickpsp** [comment]
Got banned yesterday from TM in webapp and companion. I think that the captcha was triggered but I didnt notice. How do you detect it?

**Comment by KmanProdz** [comment]
error code on request and message is like fun captcha triggered I think

**Comment by ulrickpsp** [comment]
Which is the error code?

**Comment by ulrickpsp** [comment]
458

**Comment by pradella** [comment]
Following this thread. @tringler can u send a new discord invite?

**Comment by CoverJ** [comment]
its dead man, I wouldn't bother.

**Comment by tringler** [comment]
Issue will be closed, because of inactivity and FIFA release change.
