### ISSUE TITLE
Use backup codes as 2-factor login method

### ISSUE THREAD

**Issue by Kristoffer88** [trydis/FIFA-Ultimate-Team-Toolkit#353]
Hello.

I want to know if anyone has managed to use backup-codes as 2-factor method?

it throws an exception that says it got to be a 6 digit number, but the backup code are 8 digits.

**Comment by tringler** [comment]
Hello,

backup codes are not an authentication method given by EA. These are just the backup codes to remove your chosen 2-factor authentication method (e-mail, authenticator app, etc.) and go back to username/password. Therefore it cannot be supported.

**Comment by KristianSv** [comment]
@tringler you CAN log into Ultimate Team using backup codes as two/factor authentication, through your browser. Did it MANY times. Go try it yourself.

**Comment by tringler** [comment]
Maybe we are talking about different topics. Can you describe me in detail how you login via backup codes step by step?

**Comment by KristianSv** [comment]
When asked for the email security code, just type in one of your backup codes.

**Comment by tringler** [comment]
Indeed! I will put that on the roadmap.
