### ISSUE TITLE
chooses wrong authtype

### ISSUE THREAD

**Issue by Kooszi** [trydis/FIFA-Ultimate-Team-Toolkit#354]
it chooses always authtype = APP if you've setup both

**Comment by tringler** [comment]
Can you please share the code how you setup both auth types?

**Comment by Kooszi** [comment]
`      protected async Task<HttpResponseMessage> SetTwoFactorTypeAsync(HttpResponseMessage mainPageResponseMessage)
        {
            var loginResponseMessage = new HttpResponseMessage();
            var contentData = string.Empty;

            if (_authType == AuthenticationType.Email)
            {
                loginResponseMessage = await HttpClient.PostAsync(mainPageResponseMessage.RequestMessage.RequestUri, new FormUrlEncodedContent(
                                                                                                                            new[]
                                                                                                                            {
                                                                                                                            new KeyValuePair<string, string>("_eventId", "submit"),
                                                                                                                            }));
            }
            else
            {
                loginResponseMessage = await HttpClient.PostAsync(mainPageResponseMessage.RequestMessage.RequestUri, new FormUrlEncodedContent(
                                                                                                                            new[]
                                                                                                                            {
                                                                                                                            new KeyValuePair<string, string>("_eventId", "submit"),
                                                                                                                            new KeyValuePair<string, string>("codeType", "APP"),
                                                                                                                            }));
            }

            return loginResponseMessage;
        }`
it'd need an addition of "codeType=EMAIL&_eventId=submit"
