### ISSUE TITLE
FUT18: Search not possible

### ISSUE THREAD

**Issue by niklasfc** [trydis/FIFA-Ultimate-Team-Toolkit#355]
```
            var creditsResponse = await _client.GetCreditsAsync();
            var searchParams = new PlayerSearchParameters();
            var searchResponse = await _client.SearchAsync(searchParams);
```
I can login and getting credit response is also possible, but I cannot do a search request (Properties in response object are null).

**Comment by jagarake** [comment]
I get the same issue. Although I get a valid response when entering a resourceID. Training- and Developmentsearch works fine for me too.

**Comment by jfoe98** [comment]
I think I have found the problem. If you compare the request with the request of the WebApp, you can see that the "maskedDefId" hasn't to be set. This is also the reason why searching by resourceID was successfull at you @jagarake.

**Comment by jalley3** [comment]
what is the maskeddefid?

**Comment by goodspeed1392** [comment]
@jfoe98 Hey man, thanks, I commented this block in the player search parameters
`//            if (ResourceId <= 16777216)`
`//                uriString += "&maskedDefId=" + ResourceId.CalculateBaseId();`
`//            else`
`//                uriString += "&definitionId=" + ResourceId;`
And player search started working

**Comment by tringler** [comment]
Issue will be closed, because of inactivity and FIFA release change.
