### ISSUE TITLE
Login XboxOne fails (response code 401 unauthorized)

### ISSUE THREAD

**Issue by KristianSv** [trydis/FIFA-Ultimate-Team-Toolkit#356]
This occurs after typing in the mail confirmation code.
Thoughts?

**Comment by Majed93** [comment]
400 is Bad request,  you're most likely sending a bad request

**Comment by KristianSv** [comment]
@Majed93 I'm perfectly aware of that.....
The toolkit web requests to the xbox servers needs to be updated I guess.
I'll try to figure it out

**Comment by KristianSv** [comment]
Just tried again and now it says unauthorized. Can't seem to find an issue in the code..

**Comment by KristianSv** [comment]
Fixed it. Added this in LoginBase.cs
`if (loginDetails.Platform == Platform.Ps4)
{
    validateResponseMessage = await HttpClient.PostAsync("https://utas.external.s2.fut.ea.com/ut/game/fifa18/phishing/validate?answer=" + Hasher.Hash(loginDetails.SecretAnswer), new FormUrlEncodedContent(
                    new[]
                    {
                        new KeyValuePair<string, string>("answer", Hasher.Hash(loginDetails.SecretAnswer))
                    }));
}
else
{
    validateResponseMessage = await HttpClient.PostAsync("https://utas.external.s3.fut.ea.com/ut/game/fifa18/phishing/validate?answer=" + Hasher.Hash(loginDetails.SecretAnswer), new FormUrlEncodedContent(
                    new[]
                    {
                        new KeyValuePair<string, string>("answer", Hasher.Hash(loginDetails.SecretAnswer))
                    }));
            }`

**Comment by jagarake** [comment]
I get this response after 1 minute of running the program.. do i have to manually authorize after a while?
