### ISSUE TITLE
How to proceed after sending 2factor code

### ISSUE THREAD

**Issue by omgitsme87** [trydis/FIFA-Ultimate-Team-Toolkit#357]

**Comment by omgitsme87** [comment]
I have been trying to figure out to login for days, but after I send 2 factor code I get met with

`

<script type="text/javascript">  	function getUriRoot(href) { 		return href.substring(0, href.lastIndexOf("/")) + "/"; 	}; 	function getParameterByName(name, url) { 		if (!url) { 			url = window.location.href; 		} 		name = name.replace(/[\[\]]/g, "\\$&"); 		var regex = new RegExp("[?&#]" + name + "(=([^&#]*)\|&\|#\|$)"),  			results = regex.exec(url); 		if (!results) 			return null; 		if (!results[2]) 			return ''; 		return decodeURIComponent(results[2].replace(/\+/g, " ")); 	}  	if (getParameterByName("code")) { 		code = getParameterByName("code"); 		if (parent && parent.eadpAuthSuccess) { 			parent.eadpAuthSuccess(code); 		} 	} else if (getParameterByName("access_token")) { 		token = getParameterByName("access_token"); 		var tokenParam = ""; 		 		try { 			localStorage.setItem("_eadp.identity.access_token", token); 		} 		catch (e) { 			tokenParam = "token=" + token; 		} 		 		if (getParameterByName("expires_in")) { 			expires_in = getParameterByName("expires_in"); 			var expireParam = ""; 			 			try { 				localStorage.setItem("_eadp.identity.expire", expires_in); 			} 			catch (e) { 				expireParam = "expire=" + expires_in; 			} 		} 		 		var uri = getUriRoot(window.location.href); 		if (tokenParam !== "") 		{ 			uri += "?" + tokenParam; 			 			if (expireParam !== "") 			{ 				uri += "&" + expireParam; 			} 		} 		 		window.top.location = uri; 	} 	 	else if ("" === window.location.search && "" === window.location.hash) { 		window.top.location = getUriRoot(window.location.href); 	} </script>
--

in the response, and I cant figure out how to generate the redirect url from that
`

**Comment by jalley3** [comment]
Without reading that text wall, I will ask, are you saving the cookies? What exactly is your issue?

**Comment by omgitsme87** [comment]
yes i am saving cookies, my issue is, there seems to be a redirect url generated by the javascript in the response i get after sending the 2 factor code.  obviously a httpwebrequest will not execute the javascript and generate the url.   i have followed fiddler traces and the browsers get the same javascript response ,

**Comment by Majed93** [comment]
What's your question here? How to redirect to the page to enter the code?

**Comment by tringler** [comment]
Do you use the FUT18 branch? https://github.com/tringler/FIFA-Ultimate-Team-Toolkit/tree/FUT18

**Comment by omgitsme87** [comment]
![untitled](https://user-images.githubusercontent.com/32684342/32000662-55f076b6-b98f-11e7-936c-bd435e4e61d4.png)

after i send the 2factor code ,i was expecting to recieve the "Bearer + authcode" in the response so i could move onto getting the nucleusid, the image shows fiddler trace when logging in with chrome

**Comment by jalley3** [comment]
can you post your code? also maybe post the response (from above) in a pastebin link or something with some formatting ....

**Comment by omgitsme87** [comment]
im guessing by all your responses that you guy do not get this response after sending 2factor code??.  the response is a valid one as i see it happen in chrome, firefox and my app,i dont code in C# so have difficulty following the toolkit  but i would be very interested if anyone could throw together a little  test app i could download purley  to show how the toolkit logs in to web app   so i could follow the fiddler trace of that app?
