### ISSUE TITLE
Is there anyone that has made a working program?

### ISSUE THREAD

**Issue by andrewrov** [trydis/FIFA-Ultimate-Team-Toolkit#359]
Is there anyone that has made a working program? I've tried but I'm stuck at the login...
I'm also afraid of possible ban, does they know that's someone is using a bot from how the user "moves" in the market or there's something like a flag that distinguishes from webapp and bots??

**Comment by jalley3** [comment]
I am able to log in, and save the cookie, etc. What difficulty are you having?

**Comment by jasknky** [comment]
Hi !
Me too I' can't login.
I'm using  [https://github.com/tringler/FIFA-Ultimate-Team-Toolkit/tree/FUT18](url)
here the login :  
`var loginDetails = new LoginDetails(credentias.Email, credentias.Password, credentias.Answer, Platform.Ps4, AppVersion.WebApp);
            ITwoFactorCodeProvider provider = new FutAuth();
            var loginResponse = await client.LoginAsync(loginDetails, provider);`

with : 
`public class FutAuth : ITwoFactorCodeProvider
    {
        
        public TaskCompletionSource<string> taskResult = new TaskCompletionSource<string>();
        public Task<string> GetTwoFactorCodeAsync(AuthenticationType authType)
        {
            Console.WriteLine($"{ DateTime.Now } Enter OTP ({ authType }):");
            taskResult.SetResult(Console.ReadLine());
            return taskResult.Task;
        }
    }`
If someone have a suggestion for resolve my probleme, thank you by advance !!


PS : my mail : jasknky@gmail.com!!

**Comment by stojkovic76** [comment]
I had some problems with login, because I always found incomplete examples...then I was able to complete that part...for the moment I'm not going ahead because I want to use an account different from my main but at the moment don't have yet the access to the market.

Ho works saving the cookies? Is used to avoid to re-insert each time the two factor code?

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Text;
using System.Threading.Tasks;
using UltimateTeam;
using UltimateTeam.Toolkit;
using UltimateTeam.Toolkit.Constants;
using UltimateTeam.Toolkit.Exceptions;
using UltimateTeam.Toolkit.Factories;
using UltimateTeam.Toolkit.Models;
using UltimateTeam.Toolkit.Parameters;
using UltimateTeam.Toolkit.Requests;
using UltimateTeam.Toolkit.Services;

using System.Security.Principal;

namespace Test18
{
    class Program
    {
        static void Main(string[] args)
        {
            FUT futClient = new FUT();
            futClient.Start().Wait();
            Console.ReadLine();
        }
    }

    public class FUT
    {
        public async Task Start()
        {
            await futClient();
        }
        private async Task futClient()
        {
            var client = new FutClient();
            var loginDetails = new LoginDetails("email@youremail.com", "password", "secret", Platform.Ps4 /* or any of the other platforms */, AppVersion.WebApp /* or AppVersion.CompanionApp */);
            ITwoFactorCodeProvider provider = new Auth();
            var loginResponse = await client.LoginAsync(loginDetails, provider);

        }
    }

    public class Auth : ITwoFactorCodeProvider
    {
        public TaskCompletionSource<string> taskResult = new TaskCompletionSource<string>();

        public Task<string> GetTwoFactorCodeAsync(UltimateTeam.Toolkit.Constants.AuthenticationType authType)
        {
            Console.WriteLine($"{ DateTime.Now } Enter OTP ({ authType }):");
            taskResult.SetResult(Console.ReadLine());
            return taskResult.Task;
        }
    }
}

```

**Comment by jalley3** [comment]
I can post my code when I get home, but mine is pretty similar to yours stojkovic, only I handle saving the cookie

**Comment by stojkovic76** [comment]
Don't worry I discovered how to manage cookies..

**Comment by jasknky** [comment]
Thanks for the help.
@jalley3  and @stojkovic76  ; May you help me with the cookies , please?

**Comment by stojkovic76** [comment]
Yes I can help, but for now I can post just some part of codes because I tried yesterday, works but I need to re-arrange my code.

Basically after a successfull login you have the CookieContainer here:
client.RequestFactories.CookieContainer

you can save it with a function like this one.

```
        public static void WriteCookiesToDisk(string file, CookieContainer cookieJar)
        {
            using (Stream stream = File.Create(file))
            {
                try
                {
                    Console.Out.Write("Writing cookies to disk... ");
                    BinaryFormatter formatter = new BinaryFormatter();
                    formatter.Serialize(stream, cookieJar);
                    Console.Out.WriteLine("Done.");
                }
                catch (Exception e)
                {
                    Console.Out.WriteLine("Problem writing cookies to disk: " + e.GetType());
                }
            }
        }

```

Next time that your app will restart you can read the cookies from disk

```
        public static CookieContainer ReadCookiesFromDisk(string file)
        {

            try
            {
                using (Stream stream = File.Open(file, FileMode.Open))
                {
                    Console.Out.Write("Reading cookies from disk... ");
                    BinaryFormatter formatter = new BinaryFormatter();
                    Console.Out.WriteLine("Done.");
                    return (CookieContainer)formatter.Deserialize(stream);
                }
            }
            catch (Exception e)
            {
                Console.Out.WriteLine("Problem reading cookies from disk: " + e.GetType());
                return new CookieContainer();
            }
        }
    }

```
An pass the loaded cookie container to the FutClient:
var client = new FutClient(cookie);

The login will not request the TwoFactorCode.

I hope it help!

P.S. This is my usings to be sure to find all functions:

```
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Threading.Tasks;
using UltimateTeam;
using UltimateTeam.Toolkit;
using UltimateTeam.Toolkit.Constants;
using UltimateTeam.Toolkit.Exceptions;
using UltimateTeam.Toolkit.Factories;
using UltimateTeam.Toolkit.Models;
using UltimateTeam.Toolkit.Parameters;
using UltimateTeam.Toolkit.Requests;
using UltimateTeam.Toolkit.Services;

using System.Security.Principal;
using System.Runtime.Serialization.Formatters.Binary;
```

**Comment by bootyliciouxx** [comment]
Hi ! 
I can't login.
i'm using : [https://github.com/tringler/FIFA-Ultimate-Team-Toolkit/tree/FUT18](url)
with (like @stojkovic76  )   : 
`public class Auth : ITwoFactorCodeProvider
    {
        public TaskCompletionSource<string> taskResult = new TaskCompletionSource<string>();

        public Task<string> GetTwoFactorCodeAsync(UltimateTeam.Toolkit.Constants.AuthenticationType authType)
        {
            Console.WriteLine($"{ DateTime.Now } Enter OTP ({ authType }):");
            taskResult.SetResult(Console.ReadLine());
            return taskResult.Task;
        }
    }`

but  i have an error because GetTwoFactorCodeAsync return a null value.

Someone  have an idea ?

**Comment by Raknar** [comment]
I also stuck on GetTwoFactorCodeAsync. I don't get an access code on my email.

**Comment by bootyliciouxx** [comment]
Hi !!
I still can't login!

nobody to help me ?

My mail: bootyliciouxx@gmail.com

**Comment by stojkovic76** [comment]
This is the best I can do.

Here you can download a working source code with the library that I'm currently using:
https://ufile.io/7mway

This example try to read a cookie from the disk, make login, save the cookie a show the current credits.

If don't work I believe that there is a problem on your account.
