### ISSUE TITLE
HttpClient adds spaces to headers

### ISSUE THREAD

**Issue by CoverJ** [trydis/FIFA-Ultimate-Team-Toolkit#360]
Hi guys,

Might be paranoid but I thought I'd share. The HttpClient used to make requests adds spaces to headers that don't appear in the web app (or at least not that I have seen through fiddler and chrome).

e.g
This if the Accept header from a request performed by the Toolkit
"Accept: text/html, application/xhtml+xml, application/xml; q=0.9, image/webp, image/apng, */*; q=0.8"
note the spaces after the ',' and ';'

This is the Accept header captured from fiddler by the web app
"Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8"

Like I said this may just be paranoid, my research says that both are acceptable by the standard but this could be an easy signature for a bot. Also found that this is an open issue to be resolved in dot net core.

Interested in others thoughts.

**Comment by DjTrilogic** [comment]
Hello, Is there a workaround for this please? i'm facing the exact same issue in my application deployed in Azure.

It looks like the dot net core version used there doesn't allow empty spaces. Resulting in the failure of all the ea api calls :/ 

Please help

**Comment by tringler** [comment]
Issue will be closed, because of inactivity and FIFA release change.
