### ISSUE TITLE
Did yesterday's (25/10/2017) update affect our API ?

### ISSUE THREAD

**Issue by DjTrilogic** [trydis/FIFA-Ultimate-Team-Toolkit#363]
Hello guys, 

I heard that EA made an update on the web app yesterday.

Does anyone knows the impact of this on the current version of the toolkit ?

Thank's for your answers in advance! 

Cheers

**Comment by jalley3** [comment]
I havent experimented, but most of the changes seemed like front end behavior judging by the release notes
