### ISSUE TITLE
Pack request

### ISSUE THREAD

**Issue by jasontaffy** [trydis/FIFA-Ultimate-Team-Toolkit#366]
Anyone had issues with the get available packs request, doesnt seem to b working for me

**Comment by weedali** [comment]
Same here.
I'd like to buy a pack. Is there anywhere a list of packids?

**Comment by weedali** [comment]
@jasontaffy if you still have the problem go to PerformRequestAsync() of the StoreRequest -> the request should be GET and not POST.
Change:
var storeResponseMessage = await HttpClient
    .PostAsync(uriString, new StringContent(" "))
    .ConfigureAwait(false);
to:
var storeResponseMessage = await HttpClient
                .GetAsync(uriString)
                .ConfigureAwait(false);
and you're good to go.
