### ISSUE TITLE
problem searching players

### ISSUE THREAD

**Issue by marlonespindola** [trydis/FIFA-Ultimate-Team-Toolkit#368]
searchResponse.AuctionInfo is returning NULL when I do this code:
            var searchParameters = new PlayerSearchParameters
            {
                MaxBid = 1000,
            };
            var searchResponse = await ``futClient.SearchAsync(searchParameters);

but it works when I do this code : 
            var searchParameters = new PlayerSearchParameters
            {
                ResourceId = 188567,
            };
            var searchResponse = await futClient.SearchAsync(searchParameters);

what am I doing wrong on the first code?

**Comment by parenyukp** [comment]
@marlonespindola  by using toolkit you can get players only by resourceID, idk why.
For seaching players you can use this:
"http://www.easports.com/uk/fifa/ultimate-team/api/fut/item?jsonParamObject=%7B%22name%22:%22" + name + "%22%7D"

response from server contains items by mask.

**Comment by marlonespindola** [comment]
so I cant use like this too??
var searchParameters = new PlayerSearchParameters
{
                Level = Level.Gold
};
var searchResponse = await futClient.SearchAsync(searchParameters);

is this a problem from this toolkit?

**Comment by marlonespindola** [comment]
@trydis i ve managed to do it another way. You can close this issue.

**Comment by Timo1603** [comment]
Can you give me an example of how you solved the problem? @marlonespindola

**Comment by trydis** [comment]
Check https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/issues/305#issuecomment-259815615 and https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/issues/305#issuecomment-259940095
