### ISSUE TITLE
ERROR 461 when bying

### ISSUE THREAD

**Issue by marlonespindola** [trydis/FIFA-Ultimate-Team-Toolkit#369]
In my code, I found 50 players to buy.
But I am getting to many error 461 when placing the BID. From this 50 player, only around 15 are successfull.
I am doing a random and a Sleep to take some time between the bids.
Here is the code i am using to buy them one after another:

                int count = 0;
                foreach (var eee in searchResponse.AuctionInfo)
                {
                    try
                    {
                        count += 1;
                        rndTime = rnd.Next(2000, 5000);
                        System.Threading.Thread.Sleep(rndTime);

                        var au = await futClient.PlaceBidAsync(eee, bidPrice);
                        Console.WriteLine(string.Format("{0} - SUCCESS {1}. Time = {2}", count, au.AuctionInfo[0].TradeIdStr, eee.Expires / 60));
                    }
                    catch (Exception e)
                    {
                        Console.WriteLine(string.Format("{0} - ERROR! Time = {1}", count, eee.Expires / 60));
                    }
                }

**Comment by trydis** [comment]
It's most likely that someone else has placed a bid, making your bid amount invalid.

**Comment by surfen** [comment]
I had the same issue and in my case it was indeed other people placing the bids. 
I solved it by retrying and updating the auction status:

        private static async Task<uint> PlaceBid(AuctionInfo auctionInfo, BiddingInfo card, uint bid, uint credits, int retries = 3)
        {
            var auction = auctionInfo;

            for (int i = 0; i < retries; i++)

                try
                {
                    bid = Math.Max(bid, auction.CalculateBid());

                    if(auction.Expires<0)
                    {
                        Console.WriteLine(string.Format("{0} PlaceBid: {1} auction expired ({2}), Cancelling....", DateTime.Now, card.Name, auction.TradeId));
                        return credits;
                    }
                    else if (bid > credits)
                    {
                        Console.WriteLine(string.Format("{0} PlaceBid: {1} bid({2})>credits({3}), Cancelling....", DateTime.Now, card.Name, bid, credits));
                        return credits;
                    }
                    else if (bid > card.MaxBid)
                    {
                        Console.WriteLine(string.Format("{0} PlaceBid: {1} bid({2})>maxBID({3}), Cancelling....", DateTime.Now, card.Name, bid, card.MaxBid, auction.BuyNowPrice, credits));
                        return credits;
                    }

                    Console.WriteLine(string.Format("{0} PlaceBid: {1} {2}<={3}, BuyNow={4}", DateTime.Now, card.Name, bid, card.MaxBid, auction.BuyNowPrice));
                    var response = await Client.PlaceBidAsync(auction);
                    SleepRandom();
                    credits = response.Credits;
                    Console.WriteLine(string.Format("{0} PlaceBid: Success", DateTime.Now));

                    return credits;
                }
                catch (Exception ex)
                {
                    Console.WriteLine(string.Format("{0}: ERROR! Message = {1}, GetTradeStatus", DateTime.Now, ex.Message));
                    SleepRandom();
                    var tradeStatus = await Client.GetTradeStatusAsync(new[] { auction.TradeId });
                    Console.WriteLine(string.Format("{0} Try: {1}", DateTime.Now, i + 1));
                    Console.WriteLine(string.Format("{0} Before: {1}", DateTime.Now, auction.PropertyList()));
                    auction = tradeStatus.AuctionInfo.FirstOrDefault();
                    credits = tradeStatus.Credits;
                    if (auction == null)
                        break;
                    Console.WriteLine(string.Format("{0} After: {1}", DateTime.Now, auction.PropertyList()));
                    SleepRandom();
                }

            return credits;
        }
