### ISSUE TITLE
New address to Item into Resources.cs

### ISSUE THREAD

**Issue by DoctorDMC** [trydis/FIFA-Ultimate-Team-Toolkit#370]
Hello, thx for u guys for make this toolkit.
Can someone help me find new address for Item into GetItemAsync() method.
Old address "http://fifa.content.easports.com/fifa/fltOnlineAssets/CC8267B6-0817-4842-BB6A-A20F88B05418/2017/fut/items/web/{0}.json" doen't work for new players in FIFA 18. Example "http://fifa.content.easports.com/fifa/fltOnlineAssets/CC8267B6-0817-4842-BB6A-A20F88B05418/2017/fut/items/web/234785.json" - 234785 is ID for Stephane Omeonga. But i can't get some response. It return "404 Not Found". What am i doing wrong?

**Comment by tringler** [comment]
Issue will be closed, because of inactivity and FIFA release change.
