### ISSUE TITLE
FunCaptcha

### ISSUE THREAD

**Issue by jasontaffy** [trydis/FIFA-Ultimate-Team-Toolkit#375]
Can some please help me with catching the funcaptcha response so i can link it to 2captcha or anticaptcha?

**Comment by Taggardos** [comment]
Hi,

I think you have to send a json with the Funcaptcha Token that you receive from anticaptcha (or any other Captcha Solving Service) to fut.home + "/ut/game/fifa18/captcha/fun/validate" 

Simple Example:

```
URL = https://utas.external.s3.fut.ea.com/ut/game/fifa18/captcha/fun/validate

Content =
{"funCaptchaToken":"11959eb182ed3b979.31771186|r=us-east-1|metabgclr=transparent|guitextcolor=%23606060|metaiconclr=%23606060|meta=6|lang=de|pk=A4EECF77-AC87-8C8D-5754-BF882F72063B|pl=2|injs=https://cdn.funcaptcha.com/fc/assets/graphics/ea/script/privacy_policy_fifa_2.js|at=40|ht=1|cdn_url=https://cdn.funcaptcha.com/fc|surl=https://funcaptcha.com"}
```

**Comment by tringler** [comment]
Issue will be closed, because of inactivity and FIFA release change.
