### ISSUE TITLE
Companion app login

### ISSUE THREAD

**Issue by ulrickpsp** [trydis/FIFA-Ultimate-Team-Toolkit#376]
Hi mates!

With the last available code I haven't been able to login in companion App. Now I've some time to continue with the development.

Could anybody provide me a fiddler trace? 

Thanks a lot.

**Comment by ulrickpsp** [comment]
Did myself

**Comment by bootyliciouxx** [comment]
Hi @ulrickpsp  !
Could you Help me please!!

like I said in issues #359  
i'm using : [https://github.com/tringler/FIFA-Ultimate-Team-Toolkit/tree/FUT18]

I have an error because GetTwoFactorCodeAsync return a null value.

Help please :D 

Thanks by advance!!
