### ISSUE TITLE
Soft ban for too many requestes

### ISSUE THREAD

**Issue by stojkovic76** [trydis/FIFA-Ultimate-Team-Toolkit#377]
Someone have an idea of how EA soft ban for too many requestes works?

I can receive this ban also using the APP without external software, I don't know if there is a maximum number of requestes per minute or hour that can be considered safe.

I have this problem if I want to relist expired items one by one (because I want to lower the buy now), also if I wait 5 seconds for each request...generally works but after one or two hours I take the soft ban.

**Comment by weedali** [comment]
Same here.

**Comment by marlonespindola** [comment]
You guys know what's the status code returns when you get a soft ban?

**Comment by weedali** [comment]
Either of those
        Unknown_HTTP_512 = 512,
        Unknown_HTTP_521 = 521,

**Comment by pradella** [comment]
Did you guys find out how to avoid this soft ban?
Here the status code returns 426 or 521.

**Comment by marlonespindola** [comment]
426 is the need of that verification... If I'm not mistaken

**Comment by pradella** [comment]
Now its returning 429 (too many requests)... 
Have you experienced it before @marlonespindola? 
How long be able to perform searches again?

**Comment by weedali** [comment]
@marlonespindola not 426 but 458.

**Comment by jaakob** [comment]
Guys, did you decide this question? How to avoid this soft ban?

**Comment by tringler** [comment]
Issue will be closed, because of inactivity and FIFA release change.
