### ISSUE TITLE
Staying alive = keep session

### ISSUE THREAD

**Issue by weedali** [trydis/FIFA-Ultimate-Team-Toolkit#379]
After some short time (~2-7 minutes) my session expires.
How do I keep the session from expiring? Or how do I automatically relogin?
I use 2 factor verification. Is there a way not to use this stupid ea sec key?

**Comment by stojkovic76** [comment]
My session didn't expire so fast...I don't believe that your session is expired, maybe you did just too much request and for this reason you need to login and fill the captcha....if I don't make a lot of request my session go ahead for a couple of hours....but is very easy to reach the limit because this can happen also using the web app as human. The 2 factor verification isn't a problem, if you save the cookie after the first login, if you reload it you don't need to re-insert it...the problem remain the captcha...

**Comment by weedali** [comment]
Thank you for your response.
The thing is that I do a lot of requests. However fortunately, the session doesn't expire unexpectedly, just when everything is done.
Could you please provide the code how to reload the cookie?

**Comment by stojkovic76** [comment]
To Load and Save you need these two methods.

```
        public static void WriteCookiesToDisk(string file, CookieContainer cookieJar)
        {
            using (Stream stream = File.Create(file))
            {
                try
                {
                    BinaryFormatter formatter = new BinaryFormatter();
                    formatter.Serialize(stream, cookieJar);
                    Console.Out.WriteLine("Scrittura cookie completata!");
                }
                catch (Exception e)
                {
                    Console.Out.WriteLine("Errore scrittura cookie: " + e.GetType());
                }
            }
        }

        public static CookieContainer ReadCookiesFromDisk(string file)
        {

            try
            {
                using (Stream stream = File.Open(file, FileMode.Open))
                {
                    BinaryFormatter formatter = new BinaryFormatter();
                    Console.Out.WriteLine("Lettura cookie completata!.");
                    return (CookieContainer)formatter.Deserialize(stream);
                }
            }
            catch (Exception e)
            {
                Console.Out.WriteLine("Errore leggendo il cookie dal disco: " + e.GetType());
                return null;
            }
        }
```
At the beginning you need to check if there is a cookie already saved and use it.

```
            FutClient client = new FutClient();
            CookieContainer cookie = Tools.ReadCookiesFromDisk(Config.WorkingPath + Config.Email + Config.CookieExt);

            if (cookie != null)
            {
                client = new FutClient(cookie);
            }
            else
            {
                client = new FutClient();
            }

```

After a successful login you can save the cookie for the next time.

```
            var loginResponse = await client.LoginAsync(loginDetails, provider);
            if (loginResponse.PhishingToken.String == "OK")
            {
                Console.WriteLine("LOGIN OK!");
                login = true;
                if (cookie == null)
                {
                    cookie = client.RequestFactories.CookieContainer;
                    Tools.WriteCookiesToDisk(Config.WorkingPath + Config.Email + Config.CookieExt, cookie);
                }
            }

```

I hope can help!

**Comment by weedali** [comment]
Damn. It just doesn't work. When I reload the cookie I get "value cannot be null" exception on any client.request.
like:

            if (File.Exists(fileName))
            {
                cookieJar = ReadCookie(fileName);

                if (cookieJar != null)
                {
                    client = new FutClient(cookieJar);
                }
            }

            purchasedItemsResponse = await client.GetPurchasedItemsAsync();
            -> Exception: value cannot be null

For a test I do it right after successful login.

What am I doing wrong?

**Comment by stojkovic76** [comment]
Try to understand where could be the problem check using debug if the cookie is not null before save it (should be), verify, that the file is written correctly, after check that the loading was fine and you have a not null cookie before pass it to the fut client...

**Comment by weedali** [comment]
Somehow the appversion and logindetails are null/throw exception after I've loaded the cookie.
You know why?
![untitled](https://user-images.githubusercontent.com/34369874/33942746-2fb83304-e017-11e7-8eb7-ca334bc9f81d.png)

**Comment by stojkovic76** [comment]
To be honest I don't have any idea...I'm using Visual Studio 2015 with Framework .NET 4.5.2 I don't know if a different version can give a different result...

**Comment by weedali** [comment]
No, the version does not matter.
Please, help me. It's annoying to re-login manually every time I get an "unauthorized" exception.

**Comment by weedali** [comment]
I got it.
Solution: I thought that I don't have to login (await login) after successful load of the cookie but I have to. Now, it works.
