### ISSUE TITLE
Tradepile with Icons

### ISSUE THREAD

**Issue by fernandofelixf** [trydis/FIFA-Ultimate-Team-Toolkit#383]
If you want to retrieve the TradePile and it has an icon inside, it crashes. Its because the Discard Value member in the struct is Int16, and the actual discard value exceeds its limits. How can I fix it?

Also, it crashes with a couple random players, guess they are not in the database,

**Comment by fernandofelixf** [comment]
Finally found where to change the ushort to uint... it doesn't crash in the getTradePile method anymore, but it crashes when I try to create the ItemData from the getTradePileResponse. Any idea how I can update the players database? (seems to happen with some other players that were not present in older FUTs)

**Comment by pradella** [comment]
Did the same, change ushort to uint the property related to price range.
About the ItemData, as I never sent icons to tradepile (only watch list), probably should be any property not defined in the class ItemData.

**Comment by pradella** [comment]
Sure, @trydis , just need to find out how, last time I did I make some mistakes. Not used to send pull requests... Will be a pleasure share the improvements.
