### ISSUE TITLE
Coins transfer

### ISSUE THREAD

**Issue by Timo1603** [trydis/FIFA-Ultimate-Team-Toolkit#384]
Hi,
Does anyone know of a safe way to transfer the coins from A to B?
I have 500k on my second account and I don't want to be blocked by ea
Thanks :)

**Comment by lkuklis** [comment]
As longs as I know there is no safe method to transfer coins. 
When you do it in small amounts (real price for a card) for a long period of time you have a chance not to be catch by EA but from my expirience  they will catch you anyway.

**Comment by DjTrilogic** [comment]
The best way is to have the 500k splitted among many accounts, and make them all handle a single "transaction" (many accounts transfer 500k to a single one).
