### ISSUE TITLE
squad fitness cards

### ISSUE THREAD

**Issue by NR1910** [trydis/FIFA-Ultimate-Team-Toolkit#388]
hey guys, 
does anyone know how it is possible to search for squad fitness cards now? beacause ea separated fitness and squad fitness in different categories so when i search for DevelopmentType.Fitness i only get normal fitness cards.

**Comment by Timo1603** [comment]
Hi random guy,
you can't search for only squad fitness cards in the current version.
you have to modify the urlparameters from the development search in the fut toolkit local
