### ISSUE TITLE
Can't connect anymore?

### ISSUE THREAD

**Issue by fernandofelixf** [trydis/FIFA-Ultimate-Team-Toolkit#390]
I can't connect anymore... it gets an "Unable to login to WebApp" error, anyone with the same problem or a solution?

**Comment by fernandofelixf** [comment]
Still same error here... my app had been working fine until today

**Comment by weedali** [comment]
Same here. I guess EA has made some changes.
Maybe the request must be patched.

**Comment by weedali** [comment]
I figured out that it must be something with the certificates. They must be added to the https request.
Unfortunately, I'm not that good with the https/certificates/request/response and don't know how to do it.
If somebody could help us that would be awesome.

**Comment by pradella** [comment]
Me neither, will do my best tonight trying to figure out.

**Comment by Majed93** [comment]
I can login fine? Do you know which part you're login is failing?

**Comment by weedali** [comment]
internal class LoginRequest : FutRequestBase, IFutRequest<LoginResponse>

        protected async Task<HttpResponseMessage> LoginForwarder(HttpResponseMessage responseMessage)
        {
            HttpResponseMessage forwardResponseMessage = new HttpResponseMessage();
            var contentData = await responseMessage.Content.ReadAsStringAsync();
            if (contentData.Contains("https://signin.ea.com:443/p/web2/login?execution="))
            {
                Match executionIdMatch = Regex.Match(contentData, @"https:\/\/signin\.ea\.com:443\/p\/web2\/login\?execution=([A-Za-z0-9\-]+)");

                string executionId = executionIdMatch.Groups[1].Value;
                forwardResponseMessage = await HttpClient.GetAsync("https://signin.ea.com:443/p/web2/login?execution=" + executionId + "&_eventId=end"); <- here

                return forwardResponseMessage;
            }
            return responseMessage;
        }

**Comment by Majed93** [comment]
what error does it throw?

**Comment by fernandofelixf** [comment]
For me, it crashes in this line:

`                forwardResponseMessage = await HttpClient.GetAsync("https://signin.ea.com:443/p/web2/login?execution=" + executionId + "&_eventId=end");`

(LoginRequest.cs, Line 194)


And the error is:

https://imgur.com/6yTJ0iH

**Comment by fernandofelixf** [comment]
BTW, executionId seems to be valid... and it also crashes when I change to CompanionApp login, instead of WebApp

**Comment by Majed93** [comment]
Have you checked fiddler to see any differences?

**Comment by fernandofelixf** [comment]
As someone else said here, I have no experience with HTTP/Request/Certificate things... I have no idea about how to use Fiddler (actually had to google it to know what it is)

**Comment by weedali** [comment]
@Majed93 Did you change anything in the code? I can't imagine that you login correctly if you have the same code.

**Comment by Majed93** [comment]
Unfortunately i have very different code this year but the concept is the same. Without a stacktrace i can't help. You should really use fiddler to inspect the requests otherwise it'll be tough to diagnose.

**Comment by weedali** [comment]
If I remove "&_eventId=end" I get passed through with status 200 OK but after that I don't seem to get the access_token.

**Comment by pradella** [comment]
Im also very bad at Fiddler, but I give a try. 

Noticed that when I try to sign in using toolkit, it send requests to the domains accounts.ea.com and signin.ea.com

When using WebApp, does not seems to send any request to signin.ea.com

**Comment by weedali** [comment]
I just sent an email to trydis and hope that he can help us.

**Comment by trydis** [comment]
I haven't looked at this in ages, but looking at the error it looks like they changed their certificate.

Can you try this line of code *before* calling any of the toolkit code?

`ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;`

**Comment by weedali** [comment]
Worked, halleluya.

**Comment by pradella** [comment]
Wow, thank you @trydis for the help.

@weedali did you use this code before connect, or you have to use everytime you call an async method of the client? Will try tonight.

**Comment by weedali** [comment]
I have a form with all the controls and I set the SecurityProtocol the first and only time my form is being initialized, which happens before logging in.
So technically you should set the SecurityProtocol only one time before logging in.

**Comment by fernandofelixf** [comment]
thanks trydis! it works again :) you are the best!

**Comment by syedbilal228** [comment]
@weedali I am using winform which consumes the toolkit as a DLL, In the winform project I set this protocol ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
befor calling  var loginResponse = await FutClient.LoginAsync(loginDetails, provider);
I get a 503 exception saying Serivice is unavailable
Do I need to set this in toolkit project and where?

**Comment by weedali** [comment]
Forget it. The login doesn't work at the moment (for FIFA 19). EA has a new way to login, new auth. So sit back and wait 'till a way is found to log in

**Comment by syedbilal228** [comment]
Thanks @weedali , Please update if you do any changes to get it working...

**Comment by tringler** [comment]
Issue will be closed, because of inactivity and FIFA release change.
