### ISSUE TITLE
WinForm

### ISSUE THREAD

**Issue by danijel88** [trydis/FIFA-Ultimate-Team-Toolkit#391]
Is there any real example how to use in WinForms ?
For me part of ITwoFactorCodeProvider is totaly confused, how should be generated to be used ?

Kind Regards

**Comment by weedali** [comment]
Hi
Look at how i'm doing it. It's a very ugly solution but it works and the code is run only once, at the login, after that you store the cookies and are good to go.


            if (!String.IsNullOrEmpty(/*your loginname*/)
                && !String.IsNullOrEmpty(/*your loginpassword*/)
                && !String.IsNullOrEmpty(/*your loginanswer*/))
            {
                if (client == null)
                    client = new FutClient();

                if (provider == null)
                    provider = new FutAuth(/*the sec key you get in your email*/); // I use here a text field which I fill with the sec code I get from EA. The first login attempt the text field is empty as I don't have the sec code

                loginDetails = new LoginDetails(/*loginname*/, /*loginpassword*/, loginData.secAnswer, Platform.Ps4, /*appVersion*/);

                // at the first login attempt there will be an exception saying that the format of the security code is incorrect (because our sec code is missing)
                // at the second login attempt (now that EA sent me the sec code via email) there won't be any exception if the account is valid
                try
                {
                    await client.LoginAsync(loginDetails, provider); // here you'll get the exception

                    cookieJar = client.RequestFactories.CookieContainer;
                    SaveCookie(fileName, cookieJar);

                    shouldContinue = true;
                }
                catch (Exception)
                {
                    shouldContinue = false;
                }
            }

shouldContinue is a bool to go on. If shouldContinue is true the program opens new form.
The rest of the code is your code.
Hope it helps.
