### ISSUE TITLE
Login doesn't work anymore.

### ISSUE THREAD

**Issue by NR1910** [trydis/FIFA-Ultimate-Team-Toolkit#394]
Hey developers!
I'm trying to start my application which I wrote several months ago but the login doesn't work anymore.
Does someone know what changed?

Here's my exception: 
InnerException = {"Could not find member 'onlineAccess' on object of type 'Persona'. Path 'userAccountInfo.personas[0].onlineAccess', line 1, position 113."}

Thanks!

**Comment by Kristoffer88** [comment]
You need to add the following properties to \Models\Persona.cs
public string onlineAccess { get; set; }
public string returningUserTier { get; set; }

**Comment by NR1910** [comment]
That worked thank you! I also had to add in the \Models\Auth.cs
public string phishingToken {get; set;}
