### ISSUE TITLE
 client.SearchAsync returns empty object

### ISSUE THREAD

**Issue by syedbilal228** [trydis/FIFA-Ultimate-Team-Toolkit#395]
I want to place a bid but, after successful login, I am using the same client instance to Search players

 var searchParameters = new PlayerSearchParameters
            {
                Page = 1,
                Level = Level.All,
                ChemistryStyle = ChemistryStyle.All,
                League = League.Any,
                Nation = Nation.Norway,
                Position = Position.Striker,
                Team = Team.ManchesterUnited
            };
            var searchResponse = await client.SearchAsync(searchParameters);

but the object returned by has all objects with default values and nothing else

Please help on this

**Comment by trydis** [comment]
No Norwegian strikers playing for Man U anymore 😄 Try not setting the nation parameter, or set it to something else.

**Comment by syedbilal228** [comment]
Thank you Trydis 👍
