### ISSUE TITLE
Trouble searching a player

### ISSUE THREAD

**Issue by pubsrc** [trydis/FIFA-Ultimate-Team-Toolkit#396]
Hi 
I saved all players to my local db, that I got from this json
https://fifa18.content.easports.com/fifa/fltOnlineAssets/CC8267B6-0817-4842-BB6A-A20F88B05418/2017/fut/items/web/players.json

assuming id of player object in this json is resource/asset id that can be used to find a single player
Then I call SearchAsync like this
var searchParameters = new PlayerSearchParameters
            {
              ResourceId=id //id propery of above json object
            };
            var response = await FutClient.SearchAsync(searchParameters);

the response returns multiple objects in AuctionInfo, each object with different buynow price

are these auctions of same player, if not, how can I find a single Player?

**Comment by tringler** [comment]
It should present just auctions of that specific player.
