### ISSUE TITLE
Login stopped working throwing  400 (Bad Request) exception

### ISSUE THREAD

**Issue by syedbilal228** [trydis/FIFA-Ultimate-Team-Toolkit#397]
Hi
My app was working fine but it suddenly started throwing below exceptions
Response status code does not indicate success: 400 (Bad Request).

I tried to trace and found 
In LoginRequest.cs 
at this line 
if (loginResponseMessage.RequestMessage.RequestUri.AbsoluteUri.Contains("access_token="))
this property loginResponseMessage.RequestMessage.RequestUri.AbsoluteUri cotains below value
https://www.easports.com/de/fifa/ultimate-team/coming-soon

because of which LoginResponse.AuthCode.Code contains null
 var accessToken = LoginResponse.AuthCode.Code;
var pidData = await GetPidDataAsync(accessToken);

and this method await GetPidDataAsync(accessToken); throws the exception
Response status code does not indicate success: 400 (Bad Request).

**Comment by syedbilal228** [comment]
Can someone help on this? Is anyone else facing the same issue?

**Comment by Taggardos** [comment]
The Fifa 18 Webapp is shut down. Fifa 19 Web app should be released tommorow
