### ISSUE TITLE
Development for FUT 19

### ISSUE THREAD

**Issue by KristianSv** [trydis/FIFA-Ultimate-Team-Toolkit#398]
Join my discord so we can help each other with the new web app:
https://discord.gg/f7ytm8

**Comment by tringler** [comment]
Hello @KristianSv - The invite is expired. I'm not really working on that project anymore, but I want to keep it up-to-date - Do you have anything for a PR?

**Comment by KristianSv** [comment]
https://discord.gg/fEKaq8a sorry - this link should not expire. Thanks for the notice

**Comment by Nicorad** [comment]
Hello,
Is anybody succeed in logging to the app?
I still get the 503 error...
