### ISSUE TITLE
StatusCode: 403 on login

### ISSUE THREAD

**Issue by marlonespindola** [trydis/FIFA-Ultimate-Team-Toolkit#404]
this routine 
LoginResponse.AuthData = await AuthAsync();

is returning statusCode 403 (Forbidden) for me

right here is where it returns 403
![fut_error](https://user-images.githubusercontent.com/16193729/47610640-d31d5380-da30-11e8-9151-b469d789f784.jpg)

@syedbilal228

**Comment by syedbilal228** [comment]
Put a breakpoint here and check if any field/parameter is empty
also post the innerexception when it breaks

**Comment by marlonespindola** [comment]
@syedbilal228 
this is how its been called

httpContent = "{\"isReadOnly\":false,\"sku\":\"FUT18WEB\",\"clientVersion\":1,\"locale\":\"en-US\",\"method\":\"authcode\",\"priorityLevel\":4,\"identification\":{\"authCode\":\"QUOQAAv-Cjpb5Xf1k8_sB-nIhSDuhY_kr6kg4bvr\",\"redirectUrl\":\"nucleus:rest\"},\"nucleusPersonaId\":\"1003504765040\",\"gameSku\":\"FFA18PCC\"}"

authResponseMessage = await HttpClient.PostAsync(string.Format(String.Format(Resources.Auth, DateTime.Now.ToUnixTime()), DateTime.Now.ToUnixTime()), new StringContent(httpContent));

Resources.Auth = "https://utas.external.s2.fut.ea.com/ut/auth?{0}"

**Comment by marlonespindola** [comment]
@syedbilal228 
now that I am looking...
"sku":"FUT18WEB" ???
"gameSku":"FFA18PCC" ???

any thoughts?

**Comment by marlonespindola** [comment]
yep... that was my mistake....
