### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by caiorodrig0** [trydis/FIFA-Ultimate-Team-Toolkit#405]
I am having problems with login.

 Everytime i try, i get this exception: "Two Factor Code MUST be 6 digits long WebApp."

Can someone help?

**Comment by marlonespindola** [comment]
Did you received the EA code and typed in?

**Comment by caiorodrig0** [comment]
No, can you help me?

**Comment by marlonespindola** [comment]
did you try the solution from #401 
for me it worked.

**Comment by caiorodrig0** [comment]
Yeah, my method is like this:

protected async Task<HttpResponseMessage> SetTwoFactorTypeAsync(HttpResponseMessage mainPageResponseMessage)
        {
            var loginResponseMessage = new HttpResponseMessage();
            var contentData = string.Empty;

            if (_authType == AuthenticationType.Email)
            {
                loginResponseMessage = await HttpClient.PostAsync(mainPageResponseMessage.RequestMessage.RequestUri, new FormUrlEncodedContent(
                                                                                                                            new[]
                                                                                                                            {
                                                                                                                            new KeyValuePair<string, string>("codeType", "EMAIL"),
                                                                                                                            new KeyValuePair<string, string>("_eventId", "submit"),
                                                                                                                            }));
            }
            else
            {
                loginResponseMessage = await HttpClient.PostAsync(mainPageResponseMessage.RequestMessage.RequestUri, new FormUrlEncodedContent(
                                                                                                                            new[]
                                                                                                                            {
                                                                                                                            new KeyValuePair<string, string>("_eventId", "submit"),
                                                                                                                            new KeyValuePair<string, string>("codeType", "EMAIL"),
                                                                                                                           // new KeyValuePair<string, string>("codeType", "APP"),
                                                                                                                            }));
            }

            return loginResponseMessage;
        }

but still didnt work properly =/

**Comment by caiorodrig0** [comment]
Ok, its working now.. but i get this error atm

Could not find member 'onlineAccess' on object of type 'Persona'. Path 'userAccountInfo.personas[0].onlineAccess', line 1, position 115

do you know how to fix it?

**Comment by trydis** [comment]
See https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/issues/394#issuecomment-415378139
