### ISSUE TITLE
Login problems

### ISSUE THREAD

**Issue by stojkovic76** [trydis/FIFA-Ultimate-Team-Toolkit#409]
Hello,
I changed my code as explained in another issue because I was not receiving the code but I'm not still able to login.

I debugged the DLL and  I saw that the code was accepted but there is an error in "PerformRequestAsynch()"

"Could not find member 'onlineAccess' on object of type 'Persona'. Path 'userAccountInfo.personas[0].onlineAccess', line 1, position 119."

Someone knows what could be the problem?

Thanks.

**Comment by syedbilal228** [comment]
Add below properties to Persona class (namespace UltimateTeam.Toolkit.Models)

public string OnlineAccess { get; set; } 
public string ReturningUserTier { get; set; }

**Comment by stojkovic76** [comment]
Thank you for the reply... I made the change that you suggest me and now the error is changed.
 503 (Service Unavailable) on the same method (PerformRequestAsynch()) that is caused calling LoginResponse.AuthData = await AuthAsync();

There are other changes to do?

**Comment by stojkovic76** [comment]
Seems the same problem described on #399 but there I didn't find any solution.

**Comment by stojkovic76** [comment]
I didn't yet understood if someone was able to use this API with Fifa 19 or not...

**Comment by nhcoohrh** [comment]
a small fix to the solution:

Instead of:
public string OnlineAccess { get; set; }

we should use:
public string onlineAccess { get; set; }

**Comment by stojkovic76** [comment]
> a small fix to the solution:
> 
> Instead of:
> public string OnlineAccess { get; set; }
> 
> we should use:
> public string onlineAccess { get; set; }

Always the same result...you are able to login? if yes can you post all the dll source code?

**Comment by stojkovic76** [comment]
I have found some constant that was remained to 2018...changed and now I have a new error... {"Unable to get Phishing Token WebApp."}

**Comment by nhcoohrh** [comment]
Sometimes I'm able to login, other times I got the error, it was on the Resources.cs that you found the 2018 url?

**Comment by alperselvi** [comment]
> I have found some constant that was remained to 2018...changed and now I have a new error... {"Unable to get Phishing Token WebApp."}
> 
> EDIT: ok maybe I have understood also this, some part of code need to be comment

have you found a solution for this?

**Comment by stojkovic76** [comment]
Just add a comment on 
// LoginResponse.PhishingToken = await ValidateAsync(LoginDetails);
on
PerformRequestAsync

**Comment by alperselvi** [comment]
i did that then it gave "Got no Nucleus Data and Auth Data during the Loginprocess" error, i then changed it to

LoginResponse.PhishingToken = new PhishingToken();
LoginResponse.PhishingToken.Token = LoginResponse.AuthData.phishingToken;

but data is very bad and i am spending countless hours trying to get the api working, it is a struggle :)

**Comment by stojkovic76** [comment]
I made several changes...now I can't remember all...if can help this is the modified library that I'm using at the moment:
https://ufile.io/qract

**Comment by ijr84** [comment]
Please, could you put a link to the version that worked with FUT19 to use as a start for FUT20? Thank you.
