### ISSUE TITLE
GetUserAccountsAsync gets 460

### ISSUE THREAD

**Issue by felipedrumond** [trydis/FIFA-Ultimate-Team-Toolkit#417]
```
LoginRequest.GetUserAccountsAsync -> 
{
...
var accountInfoResponseMessage = await HttpClient.GetAsync(string.Format(Resources.AccountInfo, DateTime.Now.ToUnixTime()));
// where Resources.AccountInfo is https://utas.external.s3.fut.ea.com/ut/game/fifa20/user/accountinfo?filterConsoleLogin=true&sku=&returningUserGameYear=2019&_={0}
}
```

returns http 460 and

`var accountInfoResponseMessageContent = await accountInfoResponseMessage.Content.ReadAsStringAsync(); 
`
// returns an empty string

Any ideas? I'm using WebApp as WebCompanion does not get that far.

**Comment by DjTrilogic** [comment]
I'm getting the same issue @felipedrumond. Have you found a workaround ?

**Comment by felipedrumond** [comment]
Hi @DjTrilogic I haven't solved this issue yet. I'm actually copying the X-UT-SID header from https://www.easports.com/fifa/ultimate-team/web-app/ requests and using it on my ow requests, bypassing the auth issue. I found out that all headers used in the FutClient are useless but X-UT-SID. So if you set this header in your FutClient instance, you will be able to request anything.

That's my implementation:

```
public void SetToken(string token)
        {
            RequestFactories.HttpClient.AddRequestHeader(NonStandardHttpHeaders.SessionId, token);
        }
```
       

I also changed the FutRequestBase:

```
 protected void AddCommonHeaders()
        {
            HttpClient.ClearRequestHeaders();
            HttpClient.AddConnectionKeepAliveHeader();
}
```

HttpClientWrapper:

public void ClearRequestHeaders()
        {
            // saves token
            var headers = _httpClient.DefaultRequestHeaders.AsEnumerable().ToList();
            var token = headers.Where(a => a.Key == NonStandardHttpHeaders.SessionId).FirstOrDefault();
            
            // remove headers
            _httpClient.DefaultRequestHeaders.Clear();

            // re-add token
            if (token.Key != null)
                _httpClient.DefaultRequestHeaders.Add(NonStandardHttpHeaders.SessionId, token.Value.First());
        }

Just be advised that:
- do not leave the browser open, otherwise due to lack of activity it may reload the page then your X-UT-SID will change
- limit the number of requests, specially on /auctionhouse otherwise I may get ban of few hours. Bans seems to be per route, so you'll be able to call relist all for instance even though banned from /auctionhouse
- you need to change the request base urls to https://utas.external.s3.fut.ea.com - **s2** is deprecated

**Comment by felipedrumond** [comment]
I forgot to mention that based on other 460 erros I got, this auth issue may be related to incorrect data or headers being sent to /accountinfo. What you can do in the case you want to get this sorted is to compare data and headers of the requests being made by your app and the ones made by https://www.easports.com/fifa/ultimate-team/web-app/

**Comment by totti240282** [comment]
auction house is used when relist player to market?

**Comment by felipedrumond** [comment]
Yes, you can relist all expired auctions using _ReListAsync()_ . The request url is 
https://utas.external.s3.fut.ea.com/ut/game/fifa20/**auctionhouse**/relist

However, you have never created an auction for an item before, you must specify the start biding price, buy now price and the auction duration (1hour, 3, 6, ...) which means you must call ListAuctionAsync(). Finally, if that auction expires with no winner, then you can just relist.

**Comment by totti240282** [comment]
The list says which ones don't have auctions and which ones already have them?

**Comment by felipedrumond** [comment]
Every item in auction has a TradeState (when you're trying to sell)
TradeState == "expired"
TradeState == null - when you bought an item and send it to the trade pile but have never tried to sell

When trying to buy via bidding, you have to check BidState
